// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package checksdb

import (
	"context"
)

type Querier interface {
	CreateCheckRun(ctx context.Context, db DBTX, arg CreateCheckRunParams) (CheckRun, error)
	GetCheckRun(ctx context.Context, db DBTX, id int64) (CheckRun, error)
	// ─── check_runs ──────────────────────────────────────────────────────
	// External-system create dedupe: lookup by (repo, head_sha, name,
	// external_id). NULL external_id never matches via this query.
	GetCheckRunByExternalID(ctx context.Context, db DBTX, arg GetCheckRunByExternalIDParams) (CheckRun, error)
	GetCheckSuite(ctx context.Context, db DBTX, id int64) (CheckSuite, error)
	// Required-check evaluator: most recent run with the given name on the
	// specified head_sha.
	GetLatestCheckRunByName(ctx context.Context, db DBTX, arg GetLatestCheckRunByNameParams) (CheckRun, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// ─── check_suites ────────────────────────────────────────────────────
	// Idempotent suite-by-(repo, head_sha, app_slug) lookup. Used by every
	// check-run create so consumers don't need to manage suite ids. ON
	// CONFLICT … DO UPDATE returns the existing row when the unique
	// (repo_id, head_sha, app_slug) already exists; otherwise returns the
	// freshly inserted one.
	GetOrCreateCheckSuite(ctx context.Context, db DBTX, arg GetOrCreateCheckSuiteParams) (CheckSuite, error)
	ListCheckRunsBySuite(ctx context.Context, db DBTX, suiteID int64) ([]CheckRun, error)
	ListCheckRunsForCommit(ctx context.Context, db DBTX, arg ListCheckRunsForCommitParams) ([]CheckRun, error)
	// Used by the stale-on-push hook to flip queued/in_progress suites on
	// the previous head to conclusion='stale'.
	ListCheckSuiteIDsForHead(ctx context.Context, db DBTX, arg ListCheckSuiteIDsForHeadParams) ([]int64, error)
	ListCheckSuitesForCommit(ctx context.Context, db DBTX, arg ListCheckSuitesForCommitParams) ([]CheckSuite, error)
	MarkCheckSuiteStale(ctx context.Context, db DBTX, id int64) error
	UpdateCheckRun(ctx context.Context, db DBTX, arg UpdateCheckRunParams) error
	// Persists the rollup result computed in Go (suite_rollup.go).
	UpdateCheckSuiteRollup(ctx context.Context, db DBTX, arg UpdateCheckSuiteRollupParams) error
}

var _ Querier = (*Queries)(nil)
