// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_scan_allowlist.sql

package secretscandb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyAllowlistToFindings = `-- name: ApplyAllowlistToFindings :exec
UPDATE secret_scan_findings
SET status = 'allowlisted', resolved_at = now()
WHERE repo_id = $1
  AND pattern = $2
  AND path = $3
  AND status = 'open'
`

type ApplyAllowlistToFindingsParams struct {
	RepoID  int64
	Pattern string
	Path    string
}

// Sweeps existing open findings against the allowlist after an entry
// is added: any matching (pattern, path) flips to status='allowlisted'.
func (q *Queries) ApplyAllowlistToFindings(ctx context.Context, db DBTX, arg ApplyAllowlistToFindingsParams) error {
	_, err := db.Exec(ctx, applyAllowlistToFindings, arg.RepoID, arg.Pattern, arg.Path)
	return err
}

const deleteSecretScanAllowlist = `-- name: DeleteSecretScanAllowlist :exec
DELETE FROM secret_scan_allowlist
WHERE id = $1 AND repo_id = $2
`

type DeleteSecretScanAllowlistParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) DeleteSecretScanAllowlist(ctx context.Context, db DBTX, arg DeleteSecretScanAllowlistParams) error {
	_, err := db.Exec(ctx, deleteSecretScanAllowlist, arg.ID, arg.RepoID)
	return err
}

const insertSecretScanAllowlist = `-- name: InsertSecretScanAllowlist :one

INSERT INTO secret_scan_allowlist (repo_id, pattern, path, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (repo_id, pattern, path) DO UPDATE
SET reason = EXCLUDED.reason,
    created_by = EXCLUDED.created_by
RETURNING id, repo_id, pattern, path, reason, created_by, created_at
`

type InsertSecretScanAllowlistParams struct {
	RepoID    int64
	Pattern   string
	Path      string
	Reason    string
	CreatedBy pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// PRO-EXT01-10c: secret-scan allowlist queries.
// Idempotent on (repo, pattern, path) — re-allowlisting an already-
// allowlisted finding just updates the reason via the UPSERT.
func (q *Queries) InsertSecretScanAllowlist(ctx context.Context, db DBTX, arg InsertSecretScanAllowlistParams) (SecretScanAllowlist, error) {
	row := db.QueryRow(ctx, insertSecretScanAllowlist,
		arg.RepoID,
		arg.Pattern,
		arg.Path,
		arg.Reason,
		arg.CreatedBy,
	)
	var i SecretScanAllowlist
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.Path,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isSecretScanAllowlisted = `-- name: IsSecretScanAllowlisted :one
SELECT EXISTS (
    SELECT 1 FROM secret_scan_allowlist
    WHERE repo_id = $1 AND pattern = $2 AND path = $3
) AS allowlisted
`

type IsSecretScanAllowlistedParams struct {
	RepoID  int64
	Pattern string
	Path    string
}

func (q *Queries) IsSecretScanAllowlisted(ctx context.Context, db DBTX, arg IsSecretScanAllowlistedParams) (bool, error) {
	row := db.QueryRow(ctx, isSecretScanAllowlisted, arg.RepoID, arg.Pattern, arg.Path)
	var allowlisted bool
	err := row.Scan(&allowlisted)
	return allowlisted, err
}

const listSecretScanAllowlistForRepo = `-- name: ListSecretScanAllowlistForRepo :many
SELECT id, repo_id, pattern, path, reason, created_by, created_at
FROM secret_scan_allowlist
WHERE repo_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSecretScanAllowlistForRepo(ctx context.Context, db DBTX, repoID int64) ([]SecretScanAllowlist, error) {
	rows, err := db.Query(ctx, listSecretScanAllowlistForRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretScanAllowlist{}
	for rows.Next() {
		var i SecretScanAllowlist
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Pattern,
			&i.Path,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
