// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_scan_alert_prefs.sql

package secretscandb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSecretScanAlertPrefs = `-- name: DeleteSecretScanAlertPrefs :exec
DELETE FROM secret_scan_alert_prefs WHERE user_id = $1
`

// The all-channels-off case maps to row deletion rather than
// preserving an empty row (the at_least_one check would reject it).
func (q *Queries) DeleteSecretScanAlertPrefs(ctx context.Context, db DBTX, userID int64) error {
	_, err := db.Exec(ctx, deleteSecretScanAlertPrefs, userID)
	return err
}

const getSecretScanAlertPrefs = `-- name: GetSecretScanAlertPrefs :one

SELECT user_id, email_enabled, webhook_url, webhook_secret, last_alerted_at, created_at, updated_at
FROM secret_scan_alert_prefs
WHERE user_id = $1
`

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// PRO-EXT01-10d: per-user alert preference CRUD.
// Returns the row or pgx.ErrNoRows; the handler treats absence as "no
// alerts configured" so the absence is the off state.
func (q *Queries) GetSecretScanAlertPrefs(ctx context.Context, db DBTX, userID int64) (SecretScanAlertPref, error) {
	row := db.QueryRow(ctx, getSecretScanAlertPrefs, userID)
	var i SecretScanAlertPref
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.LastAlertedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSecretScanAlertPrefsAlertedAt = `-- name: TouchSecretScanAlertPrefsAlertedAt :exec
UPDATE secret_scan_alert_prefs
SET last_alerted_at = now()
WHERE user_id = $1
`

// Recorded after a successful send so the worker can dedupe re-scans
// that re-surface a known finding (status=open → stale → open again).
func (q *Queries) TouchSecretScanAlertPrefsAlertedAt(ctx context.Context, db DBTX, userID int64) error {
	_, err := db.Exec(ctx, touchSecretScanAlertPrefsAlertedAt, userID)
	return err
}

const upsertSecretScanAlertPrefs = `-- name: UpsertSecretScanAlertPrefs :one
INSERT INTO secret_scan_alert_prefs (
    user_id, email_enabled, webhook_url, webhook_secret
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET email_enabled  = EXCLUDED.email_enabled,
    webhook_url    = EXCLUDED.webhook_url,
    webhook_secret = EXCLUDED.webhook_secret,
    updated_at     = now()
RETURNING user_id, email_enabled, webhook_url, webhook_secret, last_alerted_at, created_at, updated_at
`

type UpsertSecretScanAlertPrefsParams struct {
	UserID        int64
	EmailEnabled  bool
	WebhookUrl    pgtype.Text
	WebhookSecret []byte
}

// Settings handler calls this. The DB CHECK constraints reject the
// malformed configurations (webhook url without secret, no enabled
// channel) so the handler doesn't have to repeat that validation.
func (q *Queries) UpsertSecretScanAlertPrefs(ctx context.Context, db DBTX, arg UpsertSecretScanAlertPrefsParams) (SecretScanAlertPref, error) {
	row := db.QueryRow(ctx, upsertSecretScanAlertPrefs,
		arg.UserID,
		arg.EmailEnabled,
		arg.WebhookUrl,
		arg.WebhookSecret,
	)
	var i SecretScanAlertPref
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.LastAlertedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
