// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cursor.sql

package webhookdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoOwnerKindForFanout = `-- name: GetRepoOwnerKindForFanout :one
SELECT owner_user_id, owner_org_id
FROM repos
WHERE id = $1
`

type GetRepoOwnerKindForFanoutRow struct {
	OwnerUserID pgtype.Int8
	OwnerOrgID  pgtype.Int8
}

// Resolve a repo's owner so the fanout knows which webhooks to fire.
// Returns owner_kind 'user' or 'org' so the matcher knows what bucket
// to look in. (We use 'user' as a literal string here; the webhook
// machinery itself only stores 'repo'/'org' as owners — repo-owned
// webhooks attach to the repo regardless of who owns the repo.)
func (q *Queries) GetRepoOwnerKindForFanout(ctx context.Context, db DBTX, id int64) (GetRepoOwnerKindForFanoutRow, error) {
	row := db.QueryRow(ctx, getRepoOwnerKindForFanout, id)
	var i GetRepoOwnerKindForFanoutRow
	err := row.Scan(&i.OwnerUserID, &i.OwnerOrgID)
	return i, err
}

const getWebhookCursor = `-- name: GetWebhookCursor :one

SELECT consumer, last_event_id, updated_at
FROM domain_events_processed
WHERE consumer = $1
`

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Webhook fanout reads the same domain_events / cursor surface that
// notifications do — but with its own consumer row so progress
// doesn't collide with notify_fanout.
func (q *Queries) GetWebhookCursor(ctx context.Context, db DBTX, consumer string) (DomainEventsProcessed, error) {
	row := db.QueryRow(ctx, getWebhookCursor, consumer)
	var i DomainEventsProcessed
	err := row.Scan(&i.Consumer, &i.LastEventID, &i.UpdatedAt)
	return i, err
}

const listUnprocessedDomainEvents = `-- name: ListUnprocessedDomainEvents :many
SELECT id, actor_user_id, kind, repo_id, source_kind, source_id,
       public, payload, created_at
FROM domain_events
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListUnprocessedDomainEventsParams struct {
	ID    int64
	Limit int32
}

func (q *Queries) ListUnprocessedDomainEvents(ctx context.Context, db DBTX, arg ListUnprocessedDomainEventsParams) ([]DomainEvent, error) {
	rows, err := db.Query(ctx, listUnprocessedDomainEvents, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEvent{}
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Kind,
			&i.RepoID,
			&i.SourceKind,
			&i.SourceID,
			&i.Public,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWebhookCursor = `-- name: SetWebhookCursor :exec
INSERT INTO domain_events_processed (consumer, last_event_id)
VALUES ($1, $2)
ON CONFLICT (consumer)
DO UPDATE SET last_event_id = EXCLUDED.last_event_id,
              updated_at    = now()
`

type SetWebhookCursorParams struct {
	Consumer    string
	LastEventID int64
}

func (q *Queries) SetWebhookCursor(ctx context.Context, db DBTX, arg SetWebhookCursorParams) error {
	_, err := db.Exec(ctx, setWebhookCursor, arg.Consumer, arg.LastEventID)
	return err
}
