// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package webhookdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoDisableWebhook = `-- name: AutoDisableWebhook :exec
UPDATE webhooks
   SET disabled_at     = now(),
       disabled_reason = $2,
       updated_at      = now()
 WHERE id = $1
`

type AutoDisableWebhookParams struct {
	ID             int64
	DisabledReason pgtype.Text
}

func (q *Queries) AutoDisableWebhook(ctx context.Context, db DBTX, arg AutoDisableWebhookParams) error {
	_, err := db.Exec(ctx, autoDisableWebhook, arg.ID, arg.DisabledReason)
	return err
}

const claimDueDeliveries = `-- name: ClaimDueDeliveries :many
SELECT id FROM webhook_deliveries
WHERE status IN ('pending', 'failed_retry')
  AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY next_retry_at NULLS FIRST, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Hot-path for the deliver worker: picks up to $1 rows that are
// pending or in retry-ready state, FOR UPDATE SKIP LOCKED so concurrent
// workers don't double-send. The deliverer marks the row 'pending'
// with a far-future next_retry_at while it works on it (defense
// against re-claim during a long HTTP timeout).
func (q *Queries) ClaimDueDeliveries(ctx context.Context, db DBTX, limit int32) ([]int64, error) {
	rows, err := db.Query(ctx, claimDueDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO webhook_deliveries (
    webhook_id, event_kind, event_id, payload, request_headers,
    request_body, attempt, max_attempts, next_retry_at, status,
    idempotency_key, redeliver_of
) VALUES (
    $1, $2, $3::bigint,
    $4, $5, $6,
    $7, $8, $9::timestamptz,
    $10, $11, $12::bigint
)
RETURNING id, webhook_id, event_kind, event_id, delivery_uuid, payload, request_headers, request_body, response_status, response_headers, response_body, response_truncated, started_at, completed_at, attempt, max_attempts, next_retry_at, status, idempotency_key, error_summary, redeliver_of
`

type CreateDeliveryParams struct {
	WebhookID      int64
	EventKind      string
	EventID        pgtype.Int8
	Payload        []byte
	RequestHeaders []byte
	RequestBody    []byte
	Attempt        int32
	MaxAttempts    int32
	NextRetryAt    pgtype.Timestamptz
	Status         WebhookDeliveryStatus
	IdempotencyKey string
	RedeliverOf    pgtype.Int8
}

func (q *Queries) CreateDelivery(ctx context.Context, db DBTX, arg CreateDeliveryParams) (WebhookDelivery, error) {
	row := db.QueryRow(ctx, createDelivery,
		arg.WebhookID,
		arg.EventKind,
		arg.EventID,
		arg.Payload,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.Attempt,
		arg.MaxAttempts,
		arg.NextRetryAt,
		arg.Status,
		arg.IdempotencyKey,
		arg.RedeliverOf,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventKind,
		&i.EventID,
		&i.DeliveryUuid,
		&i.Payload,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseTruncated,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.ErrorSummary,
		&i.RedeliverOf,
	)
	return i, err
}

const createWebhook = `-- name: CreateWebhook :one

INSERT INTO webhooks (
    owner_kind, owner_id, url, content_type, events,
    secret_ciphertext, secret_nonce, active, ssl_verification,
    auto_disable_threshold, created_by_user_id
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10,
    $11::bigint
)
RETURNING id, owner_kind, owner_id, url, content_type, events, secret_ciphertext, secret_nonce, active, ssl_verification, consecutive_failures, auto_disable_threshold, disabled_at, disabled_reason, last_success_at, last_failure_at, created_by_user_id, created_at, updated_at
`

type CreateWebhookParams struct {
	OwnerKind            WebhookOwnerKind
	OwnerID              int64
	Url                  string
	ContentType          WebhookContentType
	Events               []string
	SecretCiphertext     []byte
	SecretNonce          []byte
	Active               bool
	SslVerification      bool
	AutoDisableThreshold int32
	CreatedByUserID      pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Query surface for the webhook package. Naming mirrors the verb the
// caller uses; visibility / ownership filters are applied by the
// handler layer (the queries are deliberately narrow on key columns).
func (q *Queries) CreateWebhook(ctx context.Context, db DBTX, arg CreateWebhookParams) (Webhook, error) {
	row := db.QueryRow(ctx, createWebhook,
		arg.OwnerKind,
		arg.OwnerID,
		arg.Url,
		arg.ContentType,
		arg.Events,
		arg.SecretCiphertext,
		arg.SecretNonce,
		arg.Active,
		arg.SslVerification,
		arg.AutoDisableThreshold,
		arg.CreatedByUserID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.Url,
		&i.ContentType,
		&i.Events,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Active,
		&i.SslVerification,
		&i.ConsecutiveFailures,
		&i.AutoDisableThreshold,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deleteWebhook, id)
	return err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, webhook_id, event_kind, event_id, delivery_uuid, payload, request_headers, request_body, response_status, response_headers, response_body, response_truncated, started_at, completed_at, attempt, max_attempts, next_retry_at, status, idempotency_key, error_summary, redeliver_of FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, db DBTX, id int64) (WebhookDelivery, error) {
	row := db.QueryRow(ctx, getDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventKind,
		&i.EventID,
		&i.DeliveryUuid,
		&i.Payload,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.ResponseTruncated,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.NextRetryAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.ErrorSummary,
		&i.RedeliverOf,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, owner_kind, owner_id, url, content_type, events, secret_ciphertext, secret_nonce, active, ssl_verification, consecutive_failures, auto_disable_threshold, disabled_at, disabled_reason, last_success_at, last_failure_at, created_by_user_id, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, db DBTX, id int64) (Webhook, error) {
	row := db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.Url,
		&i.ContentType,
		&i.Events,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.Active,
		&i.SslVerification,
		&i.ConsecutiveFailures,
		&i.AutoDisableThreshold,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhooksForOwner = `-- name: ListActiveWebhooksForOwner :many
SELECT id, owner_kind, owner_id, url, content_type, events, secret_ciphertext, secret_nonce, active, ssl_verification, consecutive_failures, auto_disable_threshold, disabled_at, disabled_reason, last_success_at, last_failure_at, created_by_user_id, created_at, updated_at FROM webhooks
WHERE owner_kind = $1 AND owner_id = $2
  AND active = true AND disabled_at IS NULL
`

type ListActiveWebhooksForOwnerParams struct {
	OwnerKind WebhookOwnerKind
	OwnerID   int64
}

// Used by fanout to find subscribers for an event.
func (q *Queries) ListActiveWebhooksForOwner(ctx context.Context, db DBTX, arg ListActiveWebhooksForOwnerParams) ([]Webhook, error) {
	rows, err := db.Query(ctx, listActiveWebhooksForOwner, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.OwnerID,
			&i.Url,
			&i.ContentType,
			&i.Events,
			&i.SecretCiphertext,
			&i.SecretNonce,
			&i.Active,
			&i.SslVerification,
			&i.ConsecutiveFailures,
			&i.AutoDisableThreshold,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesForWebhook = `-- name: ListDeliveriesForWebhook :many
SELECT id, webhook_id, event_kind, event_id, delivery_uuid, response_status,
       response_truncated, started_at, completed_at, attempt, max_attempts,
       next_retry_at, status, error_summary, redeliver_of
FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListDeliveriesForWebhookParams struct {
	WebhookID int64
	Limit     int32
}

type ListDeliveriesForWebhookRow struct {
	ID                int64
	WebhookID         int64
	EventKind         string
	EventID           pgtype.Int8
	DeliveryUuid      pgtype.UUID
	ResponseStatus    pgtype.Int4
	ResponseTruncated bool
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	Attempt           int32
	MaxAttempts       int32
	NextRetryAt       pgtype.Timestamptz
	Status            WebhookDeliveryStatus
	ErrorSummary      pgtype.Text
	RedeliverOf       pgtype.Int8
}

func (q *Queries) ListDeliveriesForWebhook(ctx context.Context, db DBTX, arg ListDeliveriesForWebhookParams) ([]ListDeliveriesForWebhookRow, error) {
	rows, err := db.Query(ctx, listDeliveriesForWebhook, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesForWebhookRow{}
	for rows.Next() {
		var i ListDeliveriesForWebhookRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventKind,
			&i.EventID,
			&i.DeliveryUuid,
			&i.ResponseStatus,
			&i.ResponseTruncated,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Attempt,
			&i.MaxAttempts,
			&i.NextRetryAt,
			&i.Status,
			&i.ErrorSummary,
			&i.RedeliverOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksForOwner = `-- name: ListWebhooksForOwner :many
SELECT id, owner_kind, owner_id, url, content_type, events, secret_ciphertext, secret_nonce, active, ssl_verification, consecutive_failures, auto_disable_threshold, disabled_at, disabled_reason, last_success_at, last_failure_at, created_by_user_id, created_at, updated_at FROM webhooks
WHERE owner_kind = $1 AND owner_id = $2
ORDER BY created_at DESC
`

type ListWebhooksForOwnerParams struct {
	OwnerKind WebhookOwnerKind
	OwnerID   int64
}

func (q *Queries) ListWebhooksForOwner(ctx context.Context, db DBTX, arg ListWebhooksForOwnerParams) ([]Webhook, error) {
	rows, err := db.Query(ctx, listWebhooksForOwner, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.OwnerID,
			&i.Url,
			&i.ContentType,
			&i.Events,
			&i.SecretCiphertext,
			&i.SecretNonce,
			&i.Active,
			&i.SslVerification,
			&i.ConsecutiveFailures,
			&i.AutoDisableThreshold,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryPermanentFailure = `-- name: MarkDeliveryPermanentFailure :exec
UPDATE webhook_deliveries
   SET status              = 'failed_permanent',
       response_status     = $1::int,
       response_headers    = $2::jsonb,
       response_body       = $3::bytea,
       response_truncated  = $4::bool,
       completed_at        = now(),
       error_summary       = $5::text
 WHERE id = $6::bigint
`

type MarkDeliveryPermanentFailureParams struct {
	ResponseStatus    pgtype.Int4
	ResponseHeaders   []byte
	ResponseBody      []byte
	ResponseTruncated bool
	ErrorSummary      string
	ID                int64
}

func (q *Queries) MarkDeliveryPermanentFailure(ctx context.Context, db DBTX, arg MarkDeliveryPermanentFailureParams) error {
	_, err := db.Exec(ctx, markDeliveryPermanentFailure,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseTruncated,
		arg.ErrorSummary,
		arg.ID,
	)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE webhook_deliveries
   SET status              = 'failed_retry',
       attempt             = attempt + 1,
       response_status     = $1::int,
       response_headers    = $2::jsonb,
       response_body       = $3::bytea,
       response_truncated  = $4::bool,
       next_retry_at       = $5::timestamptz,
       error_summary       = $6::text
 WHERE id = $7::bigint
`

type MarkDeliveryRetryParams struct {
	ResponseStatus    pgtype.Int4
	ResponseHeaders   []byte
	ResponseBody      []byte
	ResponseTruncated bool
	NextRetryAt       pgtype.Timestamptz
	ErrorSummary      string
	ID                int64
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, db DBTX, arg MarkDeliveryRetryParams) error {
	_, err := db.Exec(ctx, markDeliveryRetry,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseTruncated,
		arg.NextRetryAt,
		arg.ErrorSummary,
		arg.ID,
	)
	return err
}

const markDeliverySucceeded = `-- name: MarkDeliverySucceeded :exec
UPDATE webhook_deliveries
   SET status              = 'succeeded',
       response_status     = $2,
       response_headers    = $3,
       response_body       = $4,
       response_truncated  = $5,
       completed_at        = now(),
       error_summary       = NULL
 WHERE id = $1
`

type MarkDeliverySucceededParams struct {
	ID                int64
	ResponseStatus    pgtype.Int4
	ResponseHeaders   []byte
	ResponseBody      []byte
	ResponseTruncated bool
}

func (q *Queries) MarkDeliverySucceeded(ctx context.Context, db DBTX, arg MarkDeliverySucceededParams) error {
	_, err := db.Exec(ctx, markDeliverySucceeded,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ResponseTruncated,
	)
	return err
}

const purgeOldDeliveries = `-- name: PurgeOldDeliveries :execrows
DELETE FROM webhook_deliveries
WHERE status IN ('succeeded', 'failed_permanent')
  AND completed_at < now() - $1::interval
`

// Cron: drops terminal deliveries older than the retention window.
// pending/failed_retry rows are left alone so an in-flight retry isn't
// aborted out from under the worker.
func (q *Queries) PurgeOldDeliveries(ctx context.Context, db DBTX, retention pgtype.Interval) (int64, error) {
	result, err := db.Exec(ctx, purgeOldDeliveries, retention)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWebhookFailure = `-- name: RecordWebhookFailure :one
UPDATE webhooks
   SET consecutive_failures = consecutive_failures + 1,
       last_failure_at      = now(),
       updated_at           = now()
 WHERE id = $1
RETURNING consecutive_failures, auto_disable_threshold
`

type RecordWebhookFailureRow struct {
	ConsecutiveFailures  int32
	AutoDisableThreshold int32
}

// Increments the failure counter and reports the new value so the
// caller can decide whether to auto-disable.
func (q *Queries) RecordWebhookFailure(ctx context.Context, db DBTX, id int64) (RecordWebhookFailureRow, error) {
	row := db.QueryRow(ctx, recordWebhookFailure, id)
	var i RecordWebhookFailureRow
	err := row.Scan(&i.ConsecutiveFailures, &i.AutoDisableThreshold)
	return i, err
}

const recordWebhookSuccess = `-- name: RecordWebhookSuccess :exec
UPDATE webhooks
   SET consecutive_failures = 0,
       last_success_at      = now(),
       updated_at           = now()
 WHERE id = $1
`

func (q *Queries) RecordWebhookSuccess(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, recordWebhookSuccess, id)
	return err
}

const setWebhookActive = `-- name: SetWebhookActive :exec
UPDATE webhooks
   SET active               = $2,
       disabled_at          = NULL,
       disabled_reason      = NULL,
       consecutive_failures = 0,
       updated_at           = now()
 WHERE id = $1
`

type SetWebhookActiveParams struct {
	ID     int64
	Active bool
}

// Re-enables a previously auto-disabled webhook (UI affordance).
// Resets the failure counter and clears disabled_at/reason.
func (q *Queries) SetWebhookActive(ctx context.Context, db DBTX, arg SetWebhookActiveParams) error {
	_, err := db.Exec(ctx, setWebhookActive, arg.ID, arg.Active)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :exec
UPDATE webhooks
   SET url                    = $2,
       content_type           = $3,
       events                 = $4,
       active                 = $5,
       ssl_verification       = $6,
       auto_disable_threshold = $7,
       updated_at             = now()
 WHERE id = $1
`

type UpdateWebhookParams struct {
	ID                   int64
	Url                  string
	ContentType          WebhookContentType
	Events               []string
	Active               bool
	SslVerification      bool
	AutoDisableThreshold int32
}

func (q *Queries) UpdateWebhook(ctx context.Context, db DBTX, arg UpdateWebhookParams) error {
	_, err := db.Exec(ctx, updateWebhook,
		arg.ID,
		arg.Url,
		arg.ContentType,
		arg.Events,
		arg.Active,
		arg.SslVerification,
		arg.AutoDisableThreshold,
	)
	return err
}

const updateWebhookSecret = `-- name: UpdateWebhookSecret :exec
UPDATE webhooks
   SET secret_ciphertext = $2,
       secret_nonce      = $3,
       updated_at        = now()
 WHERE id = $1
`

type UpdateWebhookSecretParams struct {
	ID               int64
	SecretCiphertext []byte
	SecretNonce      []byte
}

func (q *Queries) UpdateWebhookSecret(ctx context.Context, db DBTX, arg UpdateWebhookSecretParams) error {
	_, err := db.Exec(ctx, updateWebhookSecret, arg.ID, arg.SecretCiphertext, arg.SecretNonce)
	return err
}
