// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_throttle.sql

package usersdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpAuthThrottle = `-- name: BumpAuthThrottle :one

INSERT INTO auth_throttle (scope, identifier, hits, window_started_at)
VALUES ($1, $2, 1, now())
ON CONFLICT (scope, identifier) DO UPDATE
SET hits = CASE
        WHEN auth_throttle.window_started_at < $3 THEN 1
        ELSE auth_throttle.hits + 1
    END,
    window_started_at = CASE
        WHEN auth_throttle.window_started_at < $3 THEN now()
        ELSE auth_throttle.window_started_at
    END
RETURNING hits, window_started_at
`

type BumpAuthThrottleParams struct {
	Scope           string
	Identifier      string
	WindowStartedAt pgtype.Timestamptz
}

type BumpAuthThrottleRow struct {
	Hits            int32
	WindowStartedAt pgtype.Timestamptz
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// Increments the hit counter for (scope, identifier). When the existing
// window is older than the supplied window-start cutoff, resets to 1 and
// starts a new window. Returns the post-bump (hits, window_started_at).
func (q *Queries) BumpAuthThrottle(ctx context.Context, db DBTX, arg BumpAuthThrottleParams) (BumpAuthThrottleRow, error) {
	row := db.QueryRow(ctx, bumpAuthThrottle, arg.Scope, arg.Identifier, arg.WindowStartedAt)
	var i BumpAuthThrottleRow
	err := row.Scan(&i.Hits, &i.WindowStartedAt)
	return i, err
}

const purgeStaleAuthThrottle = `-- name: PurgeStaleAuthThrottle :exec
DELETE FROM auth_throttle WHERE window_started_at < $1
`

func (q *Queries) PurgeStaleAuthThrottle(ctx context.Context, db DBTX, windowStartedAt pgtype.Timestamptz) error {
	_, err := db.Exec(ctx, purgeStaleAuthThrottle, windowStartedAt)
	return err
}

const resetAuthThrottle = `-- name: ResetAuthThrottle :exec
DELETE FROM auth_throttle WHERE scope = $1 AND identifier = $2
`

type ResetAuthThrottleParams struct {
	Scope      string
	Identifier string
}

func (q *Queries) ResetAuthThrottle(ctx context.Context, db DBTX, arg ResetAuthThrottleParams) error {
	_, err := db.Exec(ctx, resetAuthThrottle, arg.Scope, arg.Identifier)
	return err
}
