// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package usersdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :exec
UPDATE password_resets
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, consumePasswordReset, id)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :one

INSERT INTO password_resets (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) CreatePasswordReset(ctx context.Context, db DBTX, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, deleteExpiredPasswordResets)
	return err
}

const getPasswordResetByTokenHash = `-- name: GetPasswordResetByTokenHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM password_resets
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetByTokenHash(ctx context.Context, db DBTX, tokenHash []byte) (PasswordReset, error) {
	row := db.QueryRow(ctx, getPasswordResetByTokenHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
