// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Records the user's approval and links the freshly minted PAT.
	// Idempotency is preserved by the caller — the orchestrator only
	// calls this once per row.
	ApproveDeviceAuthorization(ctx context.Context, db DBTX, arg ApproveDeviceAuthorizationParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// Increments the hit counter for (scope, identifier). When the existing
	// window is older than the supplied window-start cutoff, resets to 1 and
	// starts a new window. Returns the post-bump (hits, window_started_at).
	BumpAuthThrottle(ctx context.Context, db DBTX, arg BumpAuthThrottleParams) (BumpAuthThrottleRow, error)
	// Atomically advances last_used_counter only when the proposed counter is
	// strictly greater. Returns rows affected — 0 means a replay attempt and
	// the caller should reject the code.
	BumpTOTPCounter(ctx context.Context, db DBTX, arg BumpTOTPCounterParams) (int64, error)
	BumpUserSessionEpoch(ctx context.Context, db DBTX, id int64) error
	// Sets confirmed_at on a pending row. Returns the number of rows updated;
	// callers MUST check this to handle the parallel-enrollment race
	// (only one of two concurrent confirms wins).
	ConfirmUserTOTP(ctx context.Context, db DBTX, arg ConfirmUserTOTPParams) (int64, error)
	ConsumeEmailVerification(ctx context.Context, db DBTX, id int64) error
	ConsumePasswordReset(ctx context.Context, db DBTX, id int64) error
	// Atomically marks a code as used iff it exists for the user, matches the
	// supplied hash, and isn't already used. Rows-affected==1 means accepted;
	// 0 means rejected.
	ConsumeRecoveryCode(ctx context.Context, db DBTX, arg ConsumeRecoveryCodeParams) (int64, error)
	CountActiveUserTokens(ctx context.Context, db DBTX, userID int64) (int64, error)
	// Drives the 3-changes-per-60d cap.
	CountRecentUsernameChanges(ctx context.Context, db DBTX, arg CountRecentUsernameChangesParams) (int64, error)
	CountUnusedRecoveryCodes(ctx context.Context, db DBTX, userID int64) (int64, error)
	// Excludes revoked rows so the per-user cap (100) counts live keys.
	CountUserGPGKeys(ctx context.Context, db DBTX, userID int64) (int64, error)
	CountUserSSHKeys(ctx context.Context, db DBTX, userID int64) (int64, error)
	CountUserSSHKeysByKind(ctx context.Context, db DBTX, arg CountUserSSHKeysByKindParams) (int64, error)
	CountUsernameReservationsForUser(ctx context.Context, db DBTX, userID int64) (int64, error)
	CountUsers(ctx context.Context, db DBTX) (int64, error)
	CountVerifiedUserEmails(ctx context.Context, db DBTX, userID int64) (int64, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	CreateEmailVerification(ctx context.Context, db DBTX, arg CreateEmailVerificationParams) (EmailVerification, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	CreatePasswordReset(ctx context.Context, db DBTX, arg CreatePasswordResetParams) (PasswordReset, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	CreateUserEmail(ctx context.Context, db DBTX, arg CreateUserEmailParams) (UserEmail, error)
	// Janitor invocation: a small forensics window past expiry is fine,
	// but eventually drop the row so the user_code index stays small.
	DeleteExpiredDeviceAuthorizations(ctx context.Context, db DBTX) error
	DeleteExpiredEmailVerifications(ctx context.Context, db DBTX) error
	DeleteExpiredPasswordResets(ctx context.Context, db DBTX) error
	// Scoped delete: caller must pass owning user_id. Refuses to delete
	// the primary email (UI must guide the user to set a different primary first).
	DeleteUserEmail(ctx context.Context, db DBTX, arg DeleteUserEmailParams) (int64, error)
	DeleteUserNotificationPref(ctx context.Context, db DBTX, arg DeleteUserNotificationPrefParams) error
	DeleteUserRecoveryCodes(ctx context.Context, db DBTX, userID int64) error
	// Scoped delete: caller must pass the owning user_id so a hijacked
	// handler can never delete keys it doesn't own.
	DeleteUserSSHKey(ctx context.Context, db DBTX, arg DeleteUserSSHKeyParams) (int64, error)
	DeleteUserTOTP(ctx context.Context, db DBTX, userID int64) error
	// Scoped by user_id so a misaddressed request can't delete another
	// user's reservation by id-guess.
	DeleteUsernameReservation(ctx context.Context, db DBTX, arg DeleteUsernameReservationParams) error
	DenyDeviceAuthorization(ctx context.Context, db DBTX, id int64) error
	// Hot path for the polling /access_token endpoint. The middleware
	// enforces interval_seconds via last_polled_at downstream.
	GetDeviceAuthorizationByCodeHash(ctx context.Context, db DBTX, deviceCodeHash []byte) (DeviceAuthorization, error)
	// Lookup path for the verification page. Returns even non-pending rows
	// so the handler can render a clean "already approved" / "expired" page
	// instead of a generic 404.
	GetDeviceAuthorizationByUserCode(ctx context.Context, db DBTX, userCode string) (DeviceAuthorization, error)
	GetEmailVerificationByTokenHash(ctx context.Context, db DBTX, tokenHash []byte) (EmailVerification, error)
	GetPasswordResetByTokenHash(ctx context.Context, db DBTX, tokenHash []byte) (PasswordReset, error)
	GetUserByID(ctx context.Context, db DBTX, id int64) (User, error)
	GetUserByUsername(ctx context.Context, db DBTX, username string) (User, error)
	GetUserByUsernameIncludingDeleted(ctx context.Context, db DBTX, username string) (User, error)
	GetUserEmailByAddress(ctx context.Context, db DBTX, email string) (UserEmail, error)
	GetUserEmailByID(ctx context.Context, db DBTX, id int64) (UserEmail, error)
	GetUserEmailByVerificationHash(ctx context.Context, db DBTX, verificationTokenHash []byte) (UserEmail, error)
	// Scoped single-key lookup for REST GET-by-id. user_id filter prevents
	// cross-user reads (existence-leak-safe: returns no row if the id
	// belongs to another user). Excludes soft-deleted rows so the public
	// surface mirrors a hard delete from the consumer's perspective;
	// verification (which needs historical attribution) uses
	// GetUserGPGKeyForVerification which has no revoked filter.
	GetUserGPGKey(ctx context.Context, db DBTX, arg GetUserGPGKeyParams) (UserGpgKey, error)
	// Uniqueness probe used by the add path to surface a friendly
	// "this key is already registered" error before the unique index
	// violation. Returns any row matching the fingerprint regardless of
	// which user owns it (global uniqueness is the contract).
	GetUserGPGKeyByFingerprint(ctx context.Context, db DBTX, fingerprint string) (UserGpgKey, error)
	// Non-user-scoped lookup used by the verification path. Unlike
	// GetUserGPGKey this query does NOT filter on user_id — the caller
	// already validated the subkey resolution and needs the parent
	// record's user_id to drive the email cross-check. Includes revoked
	// rows so historical commit verifications can still resolve their
	// signer attribution.
	GetUserGPGKeyForVerification(ctx context.Context, db DBTX, id int64) (UserGpgKey, error)
	// Hot path for commit/tag signature verification. The signature
	// packet carries the signing subkey's fingerprint; this query
	// resolves it back to the primary key (and via FK to the user).
	// Index lookup via the partial unique index.
	GetUserGPGSubkeyByFingerprint(ctx context.Context, db DBTX, fingerprint string) (UserGpgSubkey, error)
	// Like GetUserByID but returns the row even when deleted_at IS NOT NULL.
	GetUserIncludingDeleted(ctx context.Context, db DBTX, id int64) (User, error)
	// Single-key lookup for the REST GET-by-id endpoint. user_id filter so
	// one caller can't read another's key by ID.
	GetUserSSHKey(ctx context.Context, db DBTX, arg GetUserSSHKeyParams) (UserSshKey, error)
	// Hot path for sshd's AuthorizedKeysCommand. Index lookup via the UNIQUE
	// index on fingerprint_sha256.
	GetUserSSHKeyByFingerprint(ctx context.Context, db DBTX, fingerprintSha256 string) (UserSshKey, error)
	GetUserSessionEpoch(ctx context.Context, db DBTX, id int64) (int32, error)
	GetUserTOTP(ctx context.Context, db DBTX, userID int64) (UserTotp, error)
	// Hot path for the auth middleware. token_hash is UNIQUE; returns at
	// most one row. Caller MUST also check revoked_at IS NULL and
	// expires_at handling.
	GetUserTokenByHash(ctx context.Context, db DBTX, tokenHash []byte) (UserToken, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	InsertAuditLog(ctx context.Context, db DBTX, arg InsertAuditLogParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	InsertDeviceAuthorization(ctx context.Context, db DBTX, arg InsertDeviceAuthorizationParams) (DeviceAuthorization, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	InsertRecoveryCode(ctx context.Context, db DBTX, arg InsertRecoveryCodeParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// Inserts a parsed primary GPG key. Subkeys land in user_gpg_subkeys
	// in the same transaction (see InsertUserGPGSubkey). expires_at is
	// nullable; many keys have no expiration. revoked_at stays NULL on
	// insert; soft-delete sets it.
	InsertUserGPGKey(ctx context.Context, db DBTX, arg InsertUserGPGKeyParams) (UserGpgKey, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// One row per subkey of a primary key. Always inserted in the same
	// transaction as the parent InsertUserGPGKey so the verification
	// hot path's fingerprint lookup is consistent with the REST nested
	// shape.
	InsertUserGPGSubkey(ctx context.Context, db DBTX, arg InsertUserGPGSubkeyParams) (UserGpgSubkey, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	InsertUserSSHKey(ctx context.Context, db DBTX, arg InsertUserSSHKeyParams) (UserSshKey, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	InsertUserToken(ctx context.Context, db DBTX, arg InsertUserTokenParams) (UserToken, error)
	// Used by the S10 username-change flow to record an old name. The
	// redirect itself doubles as a 30-day reservation (the row stays for at
	// least that long).
	InsertUsernameRedirect(ctx context.Context, db DBTX, arg InsertUsernameRedirectParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	//
	// PRO-EXT01-05: vanity username reservations.
	InsertUsernameReservation(ctx context.Context, db DBTX, arg InsertUsernameReservationParams) (UserUsernameReservation, error)
	// Returns true when the handle is reserved by a user OTHER than the
	// caller. Used at signup time (`except_user_id = 0` matches all rows)
	// and at rename time (the caller's own reservation is the one they're
	// about to convert, so it should not block them).
	IsUsernameReservedByAnother(ctx context.Context, db DBTX, arg IsUsernameReservedByAnotherParams) (bool, error)
	// Sets the FK only. Does NOT flip users.email_verified — that happens via
	// MarkUserEmailPrimaryVerified after the user clicks the verification link.
	LinkUserPrimaryEmail(ctx context.Context, db DBTX, arg LinkUserPrimaryEmailParams) error
	ListAuditLogForTarget(ctx context.Context, db DBTX, arg ListAuditLogForTargetParams) ([]AuthAuditLog, error)
	// Reads all live subkeys for one primary; used when invalidating the
	// verification cache on primary soft-delete (every dependent subkey
	// needs its cache rows stamped invalidated too).
	ListSubkeysForGPGKey(ctx context.Context, db DBTX, gpgKeyID int64) ([]UserGpgSubkey, error)
	ListUserEmailsForUser(ctx context.Context, db DBTX, userID int64) ([]UserEmail, error)
	// Paginated list for the REST surface; HTML settings page reuses with
	// a generous limit and no offset.
	ListUserGPGKeys(ctx context.Context, db DBTX, arg ListUserGPGKeysParams) ([]UserGpgKey, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	ListUserNotificationPrefs(ctx context.Context, db DBTX, userID int64) ([]UserNotificationPref, error)
	ListUserSSHKeys(ctx context.Context, db DBTX, userID int64) ([]UserSshKey, error)
	// Paginated kind-filtered list used by the REST surface. Order matches
	// ListUserSSHKeys so callers can swap between them without observing a
	// reshuffle.
	ListUserSSHKeysByKind(ctx context.Context, db DBTX, arg ListUserSSHKeysByKindParams) ([]UserSshKey, error)
	ListUserTokens(ctx context.Context, db DBTX, userID int64) ([]UserToken, error)
	ListUsernameReservationsForUser(ctx context.Context, db DBTX, userID int64) ([]UserUsernameReservation, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// Resolve an old username to the current username via the user_id FK.
	// Returns ErrNoRows when no redirect exists.
	LookupUsernameRedirect(ctx context.Context, db DBTX, oldUsername string) (LookupUsernameRedirectRow, error)
	// Called after MarkUserEmailVerified for the primary email, to flip the
	// denormalized users.email_verified flag.
	MarkUserEmailPrimaryVerified(ctx context.Context, db DBTX, id int64) error
	MarkUserEmailVerified(ctx context.Context, db DBTX, id int64) error
	PurgeStaleAuthThrottle(ctx context.Context, db DBTX, windowStartedAt pgtype.Timestamptz) error
	// Wrapped by the username-change flow inside a tx that also writes
	// username_redirects, so the old name becomes a redirect target atomically.
	RenameUser(ctx context.Context, db DBTX, arg RenameUserParams) error
	ResetAuthThrottle(ctx context.Context, db DBTX, arg ResetAuthThrottleParams) error
	// Clears deleted_at; called when a user logs in within the 14-day grace
	// window. The login handler enforces the window check before calling.
	RestoreUserAccount(ctx context.Context, db DBTX, id int64) error
	// Used by user suspension to revoke every active token in one statement.
	RevokeAllUserTokens(ctx context.Context, db DBTX, userID int64) error
	// Scoped revoke: caller must pass owning user_id so a hijacked handler
	// can never revoke tokens it doesn't own. No-op on already-revoked rows.
	RevokeUserToken(ctx context.Context, db DBTX, arg RevokeUserTokenParams) (int64, error)
	// Atomically unset the existing primary and set the supplied row as
	// primary. Caller MUST have already verified the row belongs to the
	// user and is verified.
	SetUserEmailPrimary(ctx context.Context, db DBTX, arg SetUserEmailPrimaryParams) error
	SetVerificationToken(ctx context.Context, db DBTX, arg SetVerificationTokenParams) error
	// Stamps revoked_at on every live subkey of a primary. Called in the
	// same transaction as SoftDeleteUserGPGKey so the partial unique index
	// frees up the fingerprint for re-upload if the user rotates.
	SoftDeleteSubkeysForGPGKey(ctx context.Context, db DBTX, gpgKeyID int64) error
	SoftDeleteUser(ctx context.Context, db DBTX, id int64) error
	// Scoped soft-delete: stamps revoked_at, preserves the row for audit
	// continuity. Returns the number of rows affected so the handler can
	// distinguish "not found" from "deleted" without a follow-up query.
	SoftDeleteUserGPGKey(ctx context.Context, db DBTX, arg SoftDeleteUserGPGKeyParams) (int64, error)
	SuspendUser(ctx context.Context, db DBTX, arg SuspendUserParams) error
	TouchDeviceAuthorizationPoll(ctx context.Context, db DBTX, id int64) error
	TouchSSHKeyLastUsed(ctx context.Context, db DBTX, arg TouchSSHKeyLastUsedParams) error
	// Best-effort last-used stamp called from the verification path when
	// a signature successfully resolves to this key. No timeout / error
	// propagation; the caller fires-and-forgets via a goroutine.
	TouchUserGPGKeyLastUsed(ctx context.Context, db DBTX, id int64) error
	TouchUserLastLogin(ctx context.Context, db DBTX, id int64) error
	TouchUserTokenLastUsed(ctx context.Context, db DBTX, arg TouchUserTokenLastUsedParams) error
	// Clears the suspended state. Mirrors SuspendUser; used by the
	// /admin/users/{id}/unsuspend handler. Replaces an inline UPDATE
	// in admin/users.go (SR2 M2).
	UnsuspendUser(ctx context.Context, db DBTX, id int64) error
	UpdateUserAvatarKey(ctx context.Context, db DBTX, arg UpdateUserAvatarKeyParams) error
	UpdateUserPassword(ctx context.Context, db DBTX, arg UpdateUserPasswordParams) error
	UpdateUserPrivateContributions(ctx context.Context, db DBTX, arg UpdateUserPrivateContributionsParams) error
	UpdateUserProfile(ctx context.Context, db DBTX, arg UpdateUserProfileParams) error
	// PRO-EXT01-04: writes the Pro-tier vanity settings (accent color +
	// pin layout). Handler guards the write behind FeatureProfileVanity;
	// inputs are pre-validated against the column CHECK constraints so
	// this query trusts its arguments.
	UpdateUserProfileVanity(ctx context.Context, db DBTX, arg UpdateUserProfileVanityParams) error
	UpdateUserTheme(ctx context.Context, db DBTX, arg UpdateUserThemeParams) error
	UpsertUserNotificationPref(ctx context.Context, db DBTX, arg UpsertUserNotificationPrefParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// Inserts a new pending TOTP row, or replaces an existing pending row for
	// the same user. Confirmed rows are NOT replaced — disable+regenerate
	// must go through the dedicated query.
	UpsertUserTOTP(ctx context.Context, db DBTX, arg UpsertUserTOTPParams) (UserTotp, error)
}

var _ Querier = (*Queries)(nil)
