// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_recovery_codes.sql

package usersdb

import (
	"context"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
UPDATE user_recovery_codes
SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

// Atomically marks a code as used iff it exists for the user, matches the
// supplied hash, and isn't already used. Rows-affected==1 means accepted;
// 0 means rejected.
func (q *Queries) ConsumeRecoveryCode(ctx context.Context, db DBTX, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := db.Exec(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM user_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, db DBTX, userID int64) (int64, error) {
	row := db.QueryRow(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserRecoveryCodes = `-- name: DeleteUserRecoveryCodes :exec
DELETE FROM user_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteUserRecoveryCodes(ctx context.Context, db DBTX, userID int64) error {
	_, err := db.Exec(ctx, deleteUserRecoveryCodes, userID)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec

INSERT INTO user_recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) InsertRecoveryCode(ctx context.Context, db DBTX, arg InsertRecoveryCodeParams) error {
	_, err := db.Exec(ctx, insertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}
