// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_ssh_keys.sql

package usersdb

import (
	"context"
	"net/netip"
)

const countUserSSHKeys = `-- name: CountUserSSHKeys :one
SELECT count(*) FROM user_ssh_keys WHERE user_id = $1
`

func (q *Queries) CountUserSSHKeys(ctx context.Context, db DBTX, userID int64) (int64, error) {
	row := db.QueryRow(ctx, countUserSSHKeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserSSHKeysByKind = `-- name: CountUserSSHKeysByKind :one
SELECT count(*) FROM user_ssh_keys WHERE user_id = $1 AND kind = $2
`

type CountUserSSHKeysByKindParams struct {
	UserID int64
	Kind   string
}

func (q *Queries) CountUserSSHKeysByKind(ctx context.Context, db DBTX, arg CountUserSSHKeysByKindParams) (int64, error) {
	row := db.QueryRow(ctx, countUserSSHKeysByKind, arg.UserID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserSSHKey = `-- name: DeleteUserSSHKey :execrows
DELETE FROM user_ssh_keys WHERE id = $1 AND user_id = $2
`

type DeleteUserSSHKeyParams struct {
	ID     int64
	UserID int64
}

// Scoped delete: caller must pass the owning user_id so a hijacked
// handler can never delete keys it doesn't own.
func (q *Queries) DeleteUserSSHKey(ctx context.Context, db DBTX, arg DeleteUserSSHKeyParams) (int64, error) {
	result, err := db.Exec(ctx, deleteUserSSHKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserSSHKey = `-- name: GetUserSSHKey :one
SELECT id, user_id, title, fingerprint_sha256, key_type, key_bits, public_key,
       last_used_at, last_used_ip, created_at, kind
FROM user_ssh_keys
WHERE id = $1 AND user_id = $2
`

type GetUserSSHKeyParams struct {
	ID     int64
	UserID int64
}

// Single-key lookup for the REST GET-by-id endpoint. user_id filter so
// one caller can't read another's key by ID.
func (q *Queries) GetUserSSHKey(ctx context.Context, db DBTX, arg GetUserSSHKeyParams) (UserSshKey, error) {
	row := db.QueryRow(ctx, getUserSSHKey, arg.ID, arg.UserID)
	var i UserSshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.FingerprintSha256,
		&i.KeyType,
		&i.KeyBits,
		&i.PublicKey,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const getUserSSHKeyByFingerprint = `-- name: GetUserSSHKeyByFingerprint :one
SELECT id, user_id, title, fingerprint_sha256, key_type, key_bits, public_key,
       last_used_at, last_used_ip, created_at, kind
FROM user_ssh_keys
WHERE fingerprint_sha256 = $1 AND kind = 'authentication'
`

// Hot path for sshd's AuthorizedKeysCommand. Only authentication keys may
// open git protocol sessions; signing-only keys are deliberately invisible
// here even though the fingerprint is globally unique.
func (q *Queries) GetUserSSHKeyByFingerprint(ctx context.Context, db DBTX, fingerprintSha256 string) (UserSshKey, error) {
	row := db.QueryRow(ctx, getUserSSHKeyByFingerprint, fingerprintSha256)
	var i UserSshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.FingerprintSha256,
		&i.KeyType,
		&i.KeyBits,
		&i.PublicKey,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const insertUserSSHKey = `-- name: InsertUserSSHKey :one

INSERT INTO user_ssh_keys (user_id, title, fingerprint_sha256, key_type, key_bits, public_key, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, fingerprint_sha256, key_type, key_bits, public_key,
          last_used_at, last_used_ip, created_at, kind
`

type InsertUserSSHKeyParams struct {
	UserID            int64
	Title             string
	FingerprintSha256 string
	KeyType           string
	KeyBits           int32
	PublicKey         string
	Kind              string
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) InsertUserSSHKey(ctx context.Context, db DBTX, arg InsertUserSSHKeyParams) (UserSshKey, error) {
	row := db.QueryRow(ctx, insertUserSSHKey,
		arg.UserID,
		arg.Title,
		arg.FingerprintSha256,
		arg.KeyType,
		arg.KeyBits,
		arg.PublicKey,
		arg.Kind,
	)
	var i UserSshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.FingerprintSha256,
		&i.KeyType,
		&i.KeyBits,
		&i.PublicKey,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const listUserSSHKeys = `-- name: ListUserSSHKeys :many
SELECT id, user_id, title, fingerprint_sha256, key_type, key_bits, public_key,
       last_used_at, last_used_ip, created_at, kind
FROM user_ssh_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserSSHKeys(ctx context.Context, db DBTX, userID int64) ([]UserSshKey, error) {
	rows, err := db.Query(ctx, listUserSSHKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSshKey{}
	for rows.Next() {
		var i UserSshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.FingerprintSha256,
			&i.KeyType,
			&i.KeyBits,
			&i.PublicKey,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSSHKeysByKind = `-- name: ListUserSSHKeysByKind :many
SELECT id, user_id, title, fingerprint_sha256, key_type, key_bits, public_key,
       last_used_at, last_used_ip, created_at, kind
FROM user_ssh_keys
WHERE user_id = $1 AND kind = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserSSHKeysByKindParams struct {
	UserID int64
	Kind   string
	Limit  int32
	Offset int32
}

// Paginated kind-filtered list used by the REST surface. Order matches
// ListUserSSHKeys so callers can swap between them without observing a
// reshuffle.
func (q *Queries) ListUserSSHKeysByKind(ctx context.Context, db DBTX, arg ListUserSSHKeysByKindParams) ([]UserSshKey, error) {
	rows, err := db.Query(ctx, listUserSSHKeysByKind,
		arg.UserID,
		arg.Kind,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSshKey{}
	for rows.Next() {
		var i UserSshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.FingerprintSha256,
			&i.KeyType,
			&i.KeyBits,
			&i.PublicKey,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSSHKeyLastUsed = `-- name: TouchSSHKeyLastUsed :exec
UPDATE user_ssh_keys
SET last_used_at = now(),
    last_used_ip = $2
WHERE id = $1
`

type TouchSSHKeyLastUsedParams struct {
	ID         int64
	LastUsedIp *netip.Addr
}

func (q *Queries) TouchSSHKeyLastUsed(ctx context.Context, db DBTX, arg TouchSSHKeyLastUsedParams) error {
	_, err := db.Exec(ctx, touchSSHKeyLastUsed, arg.ID, arg.LastUsedIp)
	return err
}
