// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_token_usage_events.sql

package usersdb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserTokenUsageSince = `-- name: CountUserTokenUsageSince :one
SELECT count(*) FROM user_token_usage_events
WHERE token_id = $1 AND occurred_at >= $2
`

type CountUserTokenUsageSinceParams struct {
	TokenID    int64
	OccurredAt pgtype.Timestamptz
}

// Total request count for the token since `since`. Used for the
// analytics summary card.
func (q *Queries) CountUserTokenUsageSince(ctx context.Context, db DBTX, arg CountUserTokenUsageSinceParams) (int64, error) {
	row := db.QueryRow(ctx, countUserTokenUsageSince, arg.TokenID, arg.OccurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserTokenByIDForUser = `-- name: GetUserTokenByIDForUser :one
SELECT id, user_id, name, token_hash, token_prefix, scopes,
       expires_at, last_used_at, last_used_ip, revoked_at, created_at,
       ip_allowlist, repo_id
FROM user_tokens
WHERE id = $1 AND user_id = $2
`

type GetUserTokenByIDForUserParams struct {
	ID     int64
	UserID int64
}

type GetUserTokenByIDForUserRow struct {
	ID          int64
	UserID      int64
	Name        string
	TokenHash   []byte
	TokenPrefix string
	Scopes      []string
	ExpiresAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	LastUsedIp  *netip.Addr
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	IpAllowlist []string
	RepoID      pgtype.Int8
}

// Scoped fetch: only returns the row if it belongs to user_id. Used by
// the analytics handler to verify ownership before rendering.
func (q *Queries) GetUserTokenByIDForUser(ctx context.Context, db DBTX, arg GetUserTokenByIDForUserParams) (GetUserTokenByIDForUserRow, error) {
	row := db.QueryRow(ctx, getUserTokenByIDForUser, arg.ID, arg.UserID)
	var i GetUserTokenByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.IpAllowlist,
		&i.RepoID,
	)
	return i, err
}

const insertUserTokenUsageEvent = `-- name: InsertUserTokenUsageEvent :exec

INSERT INTO user_token_usage_events (token_id, method, route_prefix, status_code)
VALUES ($1, $2, $3, $4)
`

type InsertUserTokenUsageEventParams struct {
	TokenID     int64
	Method      string
	RoutePrefix string
	StatusCode  int16
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// Fire-and-forget from the PAT middleware. Non-fatal: a failed insert
// never affects request authorization.
func (q *Queries) InsertUserTokenUsageEvent(ctx context.Context, db DBTX, arg InsertUserTokenUsageEventParams) error {
	_, err := db.Exec(ctx, insertUserTokenUsageEvent,
		arg.TokenID,
		arg.Method,
		arg.RoutePrefix,
		arg.StatusCode,
	)
	return err
}

const listUserTokenTopRoutes = `-- name: ListUserTokenTopRoutes :many
SELECT method, route_prefix, count(*)::bigint AS event_count
FROM user_token_usage_events
WHERE token_id = $1 AND occurred_at >= $2
GROUP BY method, route_prefix
ORDER BY event_count DESC
LIMIT $3
`

type ListUserTokenTopRoutesParams struct {
	TokenID    int64
	OccurredAt pgtype.Timestamptz
	Limit      int32
}

type ListUserTokenTopRoutesRow struct {
	Method      string
	RoutePrefix string
	EventCount  int64
}

// Top N (method, route_prefix) tuples by request count over a window.
// Drives the "where this token is being used" table on the analytics
// page.
func (q *Queries) ListUserTokenTopRoutes(ctx context.Context, db DBTX, arg ListUserTokenTopRoutesParams) ([]ListUserTokenTopRoutesRow, error) {
	rows, err := db.Query(ctx, listUserTokenTopRoutes, arg.TokenID, arg.OccurredAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTokenTopRoutesRow{}
	for rows.Next() {
		var i ListUserTokenTopRoutesRow
		if err := rows.Scan(&i.Method, &i.RoutePrefix, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTokenUsageByDay = `-- name: ListUserTokenUsageByDay :many
SELECT date_trunc('day', occurred_at)::timestamptz AS day, count(*)::bigint AS event_count
FROM user_token_usage_events
WHERE token_id = $1 AND occurred_at >= $2
GROUP BY day
ORDER BY day
`

type ListUserTokenUsageByDayParams struct {
	TokenID    int64
	OccurredAt pgtype.Timestamptz
}

type ListUserTokenUsageByDayRow struct {
	Day        pgtype.Timestamptz
	EventCount int64
}

// Day-bucketed counts for the analytics chart. Returns at most one
// row per day; gaps mean zero traffic that day (the renderer fills
// them in).
func (q *Queries) ListUserTokenUsageByDay(ctx context.Context, db DBTX, arg ListUserTokenUsageByDayParams) ([]ListUserTokenUsageByDayRow, error) {
	rows, err := db.Query(ctx, listUserTokenUsageByDay, arg.TokenID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTokenUsageByDayRow{}
	for rows.Next() {
		var i ListUserTokenUsageByDayRow
		if err := rows.Scan(&i.Day, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
