// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_notification_prefs.sql

package usersdb

import (
	"context"
)

const deleteUserNotificationPref = `-- name: DeleteUserNotificationPref :exec
DELETE FROM user_notification_prefs WHERE user_id = $1 AND key = $2
`

type DeleteUserNotificationPrefParams struct {
	UserID int64
	Key    string
}

func (q *Queries) DeleteUserNotificationPref(ctx context.Context, db DBTX, arg DeleteUserNotificationPrefParams) error {
	_, err := db.Exec(ctx, deleteUserNotificationPref, arg.UserID, arg.Key)
	return err
}

const listUserNotificationPrefs = `-- name: ListUserNotificationPrefs :many

SELECT user_id, key, value, updated_at
FROM user_notification_prefs
WHERE user_id = $1
ORDER BY key
`

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) ListUserNotificationPrefs(ctx context.Context, db DBTX, userID int64) ([]UserNotificationPref, error) {
	rows, err := db.Query(ctx, listUserNotificationPrefs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserNotificationPref{}
	for rows.Next() {
		var i UserNotificationPref
		if err := rows.Scan(
			&i.UserID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserNotificationPref = `-- name: UpsertUserNotificationPref :exec
INSERT INTO user_notification_prefs (user_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE
SET value = EXCLUDED.value
`

type UpsertUserNotificationPrefParams struct {
	UserID int64
	Key    string
	Value  []byte
}

func (q *Queries) UpsertUserNotificationPref(ctx context.Context, db DBTX, arg UpsertUserNotificationPrefParams) error {
	_, err := db.Exec(ctx, upsertUserNotificationPref, arg.UserID, arg.Key, arg.Value)
	return err
}
