// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: username_redirects.sql

package usersdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUsernameRedirect = `-- name: InsertUsernameRedirect :exec
INSERT INTO username_redirects (old_username, user_id) VALUES ($1, $2)
`

type InsertUsernameRedirectParams struct {
	OldUsername string
	UserID      int64
}

// Used by the S10 username-change flow to record an old name. The
// redirect itself doubles as a 30-day reservation (the row stays for at
// least that long).
func (q *Queries) InsertUsernameRedirect(ctx context.Context, db DBTX, arg InsertUsernameRedirectParams) error {
	_, err := db.Exec(ctx, insertUsernameRedirect, arg.OldUsername, arg.UserID)
	return err
}

const lookupUsernameRedirect = `-- name: LookupUsernameRedirect :one

SELECT u.username, r.changed_at
FROM username_redirects r
JOIN users u ON u.id = r.user_id
WHERE r.old_username = $1 AND u.deleted_at IS NULL
`

type LookupUsernameRedirectRow struct {
	Username  string
	ChangedAt pgtype.Timestamptz
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// Resolve an old username to the current username via the user_id FK.
// Returns ErrNoRows when no redirect exists.
func (q *Queries) LookupUsernameRedirect(ctx context.Context, db DBTX, oldUsername string) (LookupUsernameRedirectRow, error) {
	row := db.QueryRow(ctx, lookupUsernameRedirect, oldUsername)
	var i LookupUsernameRedirectRow
	err := row.Scan(&i.Username, &i.ChangedAt)
	return i, err
}
