// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_saved_replies.sql

package usersdb

import (
	"context"
)

const countSavedRepliesForUser = `-- name: CountSavedRepliesForUser :one
SELECT count(*) FROM user_saved_replies WHERE user_id = $1
`

func (q *Queries) CountSavedRepliesForUser(ctx context.Context, db DBTX, userID int64) (int64, error) {
	row := db.QueryRow(ctx, countSavedRepliesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSavedReply = `-- name: DeleteSavedReply :exec
DELETE FROM user_saved_replies
WHERE id = $1 AND user_id = $2
`

type DeleteSavedReplyParams struct {
	ID     int64
	UserID int64
}

// Scoped by user_id; idempotent on missing rows.
func (q *Queries) DeleteSavedReply(ctx context.Context, db DBTX, arg DeleteSavedReplyParams) error {
	_, err := db.Exec(ctx, deleteSavedReply, arg.ID, arg.UserID)
	return err
}

const getSavedReply = `-- name: GetSavedReply :one
SELECT id, user_id, name, body, created_at, updated_at
FROM user_saved_replies
WHERE id = $1 AND user_id = $2
`

type GetSavedReplyParams struct {
	ID     int64
	UserID int64
}

// Scoped by user_id so an id-guess from another user is a no-op.
func (q *Queries) GetSavedReply(ctx context.Context, db DBTX, arg GetSavedReplyParams) (UserSavedReply, error) {
	row := db.QueryRow(ctx, getSavedReply, arg.ID, arg.UserID)
	var i UserSavedReply
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSavedReply = `-- name: InsertSavedReply :one

INSERT INTO user_saved_replies (user_id, name, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, body, created_at, updated_at
`

type InsertSavedReplyParams struct {
	UserID int64
	Name   string
	Body   string
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// PRO-EXT01-07a: saved replies.
func (q *Queries) InsertSavedReply(ctx context.Context, db DBTX, arg InsertSavedReplyParams) (UserSavedReply, error) {
	row := db.QueryRow(ctx, insertSavedReply, arg.UserID, arg.Name, arg.Body)
	var i UserSavedReply
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSavedRepliesForUser = `-- name: ListSavedRepliesForUser :many
SELECT id, user_id, name, body, created_at, updated_at
FROM user_saved_replies
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListSavedRepliesForUser(ctx context.Context, db DBTX, userID int64) ([]UserSavedReply, error) {
	rows, err := db.Query(ctx, listSavedRepliesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSavedReply{}
	for rows.Next() {
		var i UserSavedReply
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedReply = `-- name: UpdateSavedReply :exec
UPDATE user_saved_replies
SET name = $3, body = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateSavedReplyParams struct {
	ID     int64
	UserID int64
	Name   string
	Body   string
}

// Scoped by user_id; updated_at refreshed on every write so the picker
// can surface "most recently edited" if the UI wants to sort that way.
func (q *Queries) UpdateSavedReply(ctx context.Context, db DBTX, arg UpdateSavedReplyParams) error {
	_, err := db.Exec(ctx, updateSavedReply,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Body,
	)
	return err
}
