---
# SPDX-License-Identifier: AGPL-3.0-or-later

shithub_runner_enabled: false
shithub_runner_server_url: "https://{{ shithub_domain }}"
shithub_runner_token: ""
shithub_runner_labels:
  - self-hosted
  - linux
  - ubuntu-latest
  - x64
shithub_runner_capacity: 1
shithub_runner_poll_interval: 5s
shithub_runner_workspace_root: /var/lib/shithubd-runner/workspaces
shithub_runner_workspace_ttl: 24h
shithub_runner_network_allowlist:
  - api.github.com
  - auth.docker.io
  - codeload.github.com
  - github.com
  - objects.githubusercontent.com
  - production.cloudflare.docker.com
  - registry-1.docker.io
  - "*.githubusercontent.com"
shithub_runner_engine: docker
shithub_runner_default_image: ghcr.io/tenseleyflow/shithub/runner-nix:1.1
shithub_runner_network: shithub-actions
shithub_runner_network_bridge: shact0
shithub_runner_network_subnet: 172.30.0.0/24
shithub_runner_network_gateway: 172.30.0.1
shithub_runner_dns_servers:
  - "{{ shithub_runner_network_gateway }}"
shithub_runner_dnsmasq_config: /etc/dnsmasq.d/shithubd-runner.conf
shithub_runner_dnsmasq_upstream: 1.1.1.1
shithub_runner_ipset_name: shithub_actions_allowed
shithub_runner_firewall_script: /usr/local/sbin/shithub-runner-firewall
shithub_runner_memory: 2g
shithub_runner_cpus: "2"
shithub_runner_seccomp_profile: /etc/shithubd-runner/seccomp.json
shithub_runner_container_user: "auto"
shithub_runner_pids_limit: 512
shithub_runner_log_level: info
shithub_runner_log_format: text
