// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package metadb

import (
	"context"
)

type Querier interface {
	DeleteMeta(ctx context.Context, db DBTX, key string) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	GetMeta(ctx context.Context, db DBTX, key string) (Meta, error)
	ListMeta(ctx context.Context, db DBTX) ([]Meta, error)
	SetMeta(ctx context.Context, db DBTX, arg SetMetaParams) error
}

var _ Querier = (*Queries)(nil)
