// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package orgsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptOrgInvitation = `-- name: AcceptOrgInvitation :exec
UPDATE org_invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptOrgInvitation(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, acceptOrgInvitation, id)
	return err
}

const cancelOrgInvitation = `-- name: CancelOrgInvitation :exec
UPDATE org_invitations SET canceled_at = now() WHERE id = $1
`

func (q *Queries) CancelOrgInvitation(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, cancelOrgInvitation, id)
	return err
}

const createOrgInvitation = `-- name: CreateOrgInvitation :one


INSERT INTO org_invitations (
    org_id, invited_by_user_id, target_user_id, target_email,
    role, token_hash, expires_at
) VALUES (
    $1, $2, $6::bigint, $7::citext,
    $3, $4, $5
)
RETURNING id, org_id, invited_by_user_id, target_user_id, target_email, role, token_hash, expires_at, accepted_at, declined_at, canceled_at, created_at
`

type CreateOrgInvitationParams struct {
	OrgID           int64
	InvitedByUserID pgtype.Int8
	Role            OrgRole
	TokenHash       []byte
	ExpiresAt       pgtype.Timestamptz
	TargetUserID    pgtype.Int8
	TargetEmail     pgtype.Text
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// ─── org_invitations ───────────────────────────────────────────────
func (q *Queries) CreateOrgInvitation(ctx context.Context, db DBTX, arg CreateOrgInvitationParams) (OrgInvitation, error) {
	row := db.QueryRow(ctx, createOrgInvitation,
		arg.OrgID,
		arg.InvitedByUserID,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.TargetUserID,
		arg.TargetEmail,
	)
	var i OrgInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InvitedByUserID,
		&i.TargetUserID,
		&i.TargetEmail,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CanceledAt,
		&i.CreatedAt,
	)
	return i, err
}

const declineOrgInvitation = `-- name: DeclineOrgInvitation :exec
UPDATE org_invitations SET declined_at = now() WHERE id = $1
`

func (q *Queries) DeclineOrgInvitation(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, declineOrgInvitation, id)
	return err
}

const getExistingPendingInvitation = `-- name: GetExistingPendingInvitation :one
SELECT id, org_id, invited_by_user_id, target_user_id, target_email, role, token_hash, expires_at, accepted_at, declined_at, canceled_at, created_at FROM org_invitations
WHERE org_id = $1
  AND ( (target_user_id = $2::bigint)
     OR (target_email   = $3::citext) )
  AND accepted_at IS NULL
  AND declined_at IS NULL
  AND canceled_at IS NULL
  AND expires_at > now()
LIMIT 1
`

type GetExistingPendingInvitationParams struct {
	OrgID        int64
	TargetUserID pgtype.Int8
	TargetEmail  pgtype.Text
}

// Idempotency check before creating a new invite — so a re-issued
// invite to the same target doesn't accumulate stale rows.
func (q *Queries) GetExistingPendingInvitation(ctx context.Context, db DBTX, arg GetExistingPendingInvitationParams) (OrgInvitation, error) {
	row := db.QueryRow(ctx, getExistingPendingInvitation, arg.OrgID, arg.TargetUserID, arg.TargetEmail)
	var i OrgInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InvitedByUserID,
		&i.TargetUserID,
		&i.TargetEmail,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CanceledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgInvitationByID = `-- name: GetOrgInvitationByID :one
SELECT id, org_id, invited_by_user_id, target_user_id, target_email, role, token_hash, expires_at, accepted_at, declined_at, canceled_at, created_at FROM org_invitations WHERE id = $1
`

func (q *Queries) GetOrgInvitationByID(ctx context.Context, db DBTX, id int64) (OrgInvitation, error) {
	row := db.QueryRow(ctx, getOrgInvitationByID, id)
	var i OrgInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InvitedByUserID,
		&i.TargetUserID,
		&i.TargetEmail,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CanceledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgInvitationByTokenHash = `-- name: GetOrgInvitationByTokenHash :one
SELECT id, org_id, invited_by_user_id, target_user_id, target_email, role, token_hash, expires_at, accepted_at, declined_at, canceled_at, created_at FROM org_invitations WHERE token_hash = $1
`

func (q *Queries) GetOrgInvitationByTokenHash(ctx context.Context, db DBTX, tokenHash []byte) (OrgInvitation, error) {
	row := db.QueryRow(ctx, getOrgInvitationByTokenHash, tokenHash)
	var i OrgInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.InvitedByUserID,
		&i.TargetUserID,
		&i.TargetEmail,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CanceledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitationsForEmail = `-- name: ListPendingInvitationsForEmail :many
SELECT i.id, i.org_id, i.invited_by_user_id, i.target_user_id, i.target_email, i.role, i.token_hash, i.expires_at, i.accepted_at, i.declined_at, i.canceled_at, i.created_at, o.slug AS org_slug, o.display_name AS org_display_name
FROM org_invitations i
JOIN orgs o ON o.id = i.org_id
WHERE i.target_email = $1
  AND i.accepted_at IS NULL
  AND i.declined_at IS NULL
  AND i.canceled_at IS NULL
  AND i.expires_at > now()
  AND o.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListPendingInvitationsForEmailRow struct {
	ID              int64
	OrgID           int64
	InvitedByUserID pgtype.Int8
	TargetUserID    pgtype.Int8
	TargetEmail     pgtype.Text
	Role            OrgRole
	TokenHash       []byte
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	DeclinedAt      pgtype.Timestamptz
	CanceledAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	OrgSlug         string
	OrgDisplayName  string
}

func (q *Queries) ListPendingInvitationsForEmail(ctx context.Context, db DBTX, targetEmail pgtype.Text) ([]ListPendingInvitationsForEmailRow, error) {
	rows, err := db.Query(ctx, listPendingInvitationsForEmail, targetEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForEmailRow{}
	for rows.Next() {
		var i ListPendingInvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.InvitedByUserID,
			&i.TargetUserID,
			&i.TargetEmail,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.OrgSlug,
			&i.OrgDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForOrg = `-- name: ListPendingInvitationsForOrg :many
SELECT i.id, i.org_id, i.invited_by_user_id, i.target_user_id, i.target_email, i.role, i.token_hash, i.expires_at, i.accepted_at, i.declined_at, i.canceled_at, i.created_at, u.username AS target_username, ib.username AS invited_by_username
FROM org_invitations i
LEFT JOIN users u  ON u.id  = i.target_user_id
LEFT JOIN users ib ON ib.id = i.invited_by_user_id
WHERE i.org_id = $1
  AND i.accepted_at IS NULL
  AND i.declined_at IS NULL
  AND i.canceled_at IS NULL
  AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type ListPendingInvitationsForOrgRow struct {
	ID                int64
	OrgID             int64
	InvitedByUserID   pgtype.Int8
	TargetUserID      pgtype.Int8
	TargetEmail       pgtype.Text
	Role              OrgRole
	TokenHash         []byte
	ExpiresAt         pgtype.Timestamptz
	AcceptedAt        pgtype.Timestamptz
	DeclinedAt        pgtype.Timestamptz
	CanceledAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	TargetUsername    pgtype.Text
	InvitedByUsername pgtype.Text
}

func (q *Queries) ListPendingInvitationsForOrg(ctx context.Context, db DBTX, orgID int64) ([]ListPendingInvitationsForOrgRow, error) {
	rows, err := db.Query(ctx, listPendingInvitationsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForOrgRow{}
	for rows.Next() {
		var i ListPendingInvitationsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.InvitedByUserID,
			&i.TargetUserID,
			&i.TargetEmail,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.TargetUsername,
			&i.InvitedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForUser = `-- name: ListPendingInvitationsForUser :many
SELECT i.id, i.org_id, i.invited_by_user_id, i.target_user_id, i.target_email, i.role, i.token_hash, i.expires_at, i.accepted_at, i.declined_at, i.canceled_at, i.created_at, o.slug AS org_slug, o.display_name AS org_display_name
FROM org_invitations i
JOIN orgs o ON o.id = i.org_id
WHERE i.target_user_id = $1
  AND i.accepted_at IS NULL
  AND i.declined_at IS NULL
  AND i.canceled_at IS NULL
  AND i.expires_at > now()
  AND o.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListPendingInvitationsForUserRow struct {
	ID              int64
	OrgID           int64
	InvitedByUserID pgtype.Int8
	TargetUserID    pgtype.Int8
	TargetEmail     pgtype.Text
	Role            OrgRole
	TokenHash       []byte
	ExpiresAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	DeclinedAt      pgtype.Timestamptz
	CanceledAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	OrgSlug         string
	OrgDisplayName  string
}

// Two flavors: by user_id (already-claimed invites) and by email
// (claim-on-signup). Caller unions the two lookups when surfacing
// to the user.
func (q *Queries) ListPendingInvitationsForUser(ctx context.Context, db DBTX, targetUserID pgtype.Int8) ([]ListPendingInvitationsForUserRow, error) {
	rows, err := db.Query(ctx, listPendingInvitationsForUser, targetUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForUserRow{}
	for rows.Next() {
		var i ListPendingInvitationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.InvitedByUserID,
			&i.TargetUserID,
			&i.TargetEmail,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.OrgSlug,
			&i.OrgDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
