// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package orgsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :exec


INSERT INTO org_members (org_id, user_id, role, invited_by_user_id)
VALUES ($1, $2, $3, $4::bigint)
ON CONFLICT (org_id, user_id) DO NOTHING
`

type AddOrgMemberParams struct {
	OrgID           int64
	UserID          int64
	Role            OrgRole
	InvitedByUserID pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// ─── org_members ───────────────────────────────────────────────────
// Idempotent on (org_id, user_id): re-adding a member is a no-op
// rather than an error. The role is taken from the supplied row when
// the member is new; existing rows keep their current role (use
// ChangeOrgMemberRole to update).
func (q *Queries) AddOrgMember(ctx context.Context, db DBTX, arg AddOrgMemberParams) error {
	_, err := db.Exec(
		ctx, addOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.InvitedByUserID,
	)
	return err
}

const changeOrgMemberRole = `-- name: ChangeOrgMemberRole :exec
UPDATE org_members SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type ChangeOrgMemberRoleParams struct {
	OrgID  int64
	UserID int64
	Role   OrgRole
}

func (q *Queries) ChangeOrgMemberRole(ctx context.Context, db DBTX, arg ChangeOrgMemberRoleParams) error {
	_, err := db.Exec(ctx, changeOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const countOrgOwners = `-- name: CountOrgOwners :one
SELECT count(*) FROM org_members WHERE org_id = $1 AND role = 'owner'
`

// Used by the last-owner protection: refuses to remove or demote the
// only owner. Caller compares `count = 1` before allowing the change.
func (q *Queries) CountOrgOwners(ctx context.Context, db DBTX, orgID int64) (int64, error) {
	row := db.QueryRow(ctx, countOrgOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role, invited_by_user_id, joined_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  int64
	UserID int64
}

func (q *Queries) GetOrgMember(ctx context.Context, db DBTX, arg GetOrgMemberParams) (OrgMember, error) {
	row := db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.InvitedByUserID,
		&i.JoinedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT m.org_id, m.user_id, m.role, m.invited_by_user_id, m.joined_at,
       u.username, u.display_name, u.plan
FROM org_members m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
  AND u.deleted_at IS NULL
ORDER BY m.role ASC, u.username ASC
`

type ListOrgMembersRow struct {
	OrgID           int64
	UserID          int64
	Role            OrgRole
	InvitedByUserID pgtype.Int8
	JoinedAt        pgtype.Timestamptz
	Username        string
	DisplayName     string
	Plan            UserPlan
}

// Members of an org with usernames + roles for the people page.
// PRO-EXT_SR2-15: select u.plan so the people list renders a Pro
// badge next to Pro user accounts (org owners get the org-paid
// treatment in a separate sprint).
func (q *Queries) ListOrgMembers(ctx context.Context, db DBTX, orgID int64) ([]ListOrgMembersRow, error) {
	rows, err := db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.InvitedByUserID,
			&i.JoinedAt,
			&i.Username,
			&i.DisplayName,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT m.org_id, m.role, o.slug, o.display_name, o.avatar_object_key
FROM org_members m
JOIN orgs o ON o.id = m.org_id
WHERE m.user_id = $1
  AND o.deleted_at IS NULL
ORDER BY o.slug ASC
`

type ListOrgsForUserRow struct {
	OrgID           int64
	Role            OrgRole
	Slug            string
	DisplayName     string
	AvatarObjectKey pgtype.Text
}

// Profile-page input: every org a user is a member of, with role.
func (q *Queries) ListOrgsForUser(ctx context.Context, db DBTX, userID int64) ([]ListOrgsForUserRow, error) {
	rows, err := db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgsForUserRow{}
	for rows.Next() {
		var i ListOrgsForUserRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Role,
			&i.Slug,
			&i.DisplayName,
			&i.AvatarObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrgID  int64
	UserID int64
}

func (q *Queries) RemoveOrgMember(ctx context.Context, db DBTX, arg RemoveOrgMemberParams) error {
	_, err := db.Exec(ctx, removeOrgMember, arg.OrgID, arg.UserID)
	return err
}
