// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package orgsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one


INSERT INTO orgs (slug, display_name, description, billing_email, created_by_user_id)
VALUES ($1, $2, $3, $4, $5::bigint)
RETURNING id, slug, display_name, description, avatar_object_key, location, website, billing_email, plan, allow_member_repo_create, created_by_user_id, suspended_at, suspended_reason, deleted_at, created_at, updated_at
`

type CreateOrgParams struct {
	Slug            string
	DisplayName     string
	Description     string
	BillingEmail    string
	CreatedByUserID pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// ─── orgs ──────────────────────────────────────────────────────────
// Inserts a new org. The trigger on `orgs` populates `principals` for
// /{slug} resolution; the caller adds the creator as owner in the same
// tx (separate query so the orchestrator owns ordering).
func (q *Queries) CreateOrg(ctx context.Context, db DBTX, arg CreateOrgParams) (Org, error) {
	row := db.QueryRow(ctx, createOrg,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.BillingEmail,
		arg.CreatedByUserID,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.Location,
		&i.Website,
		&i.BillingEmail,
		&i.Plan,
		&i.AllowMemberRepoCreate,
		&i.CreatedByUserID,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, slug, display_name, description, avatar_object_key, location, website, billing_email, plan, allow_member_repo_create, created_by_user_id, suspended_at, suspended_reason, deleted_at, created_at, updated_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, db DBTX, id int64) (Org, error) {
	row := db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.Location,
		&i.Website,
		&i.BillingEmail,
		&i.Plan,
		&i.AllowMemberRepoCreate,
		&i.CreatedByUserID,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, slug, display_name, description, avatar_object_key, location, website, billing_email, plan, allow_member_repo_create, created_by_user_id, suspended_at, suspended_reason, deleted_at, created_at, updated_at FROM orgs
WHERE slug = $1
  AND deleted_at IS NULL
`

// Slug is citext so the comparison is case-insensitive. Soft-deleted
// orgs are filtered out so a slug freed by deletion is invisible to
// normal lookups (the resolver still sees the row via the deleted_at
// column for grace-period restore).
func (q *Queries) GetOrgBySlug(ctx context.Context, db DBTX, slug string) (Org, error) {
	row := db.QueryRow(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.Location,
		&i.Website,
		&i.BillingEmail,
		&i.Plan,
		&i.AllowMemberRepoCreate,
		&i.CreatedByUserID,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgBySlugIncludingDeleted = `-- name: GetOrgBySlugIncludingDeleted :one
SELECT id, slug, display_name, description, avatar_object_key, location, website, billing_email, plan, allow_member_repo_create, created_by_user_id, suspended_at, suspended_reason, deleted_at, created_at, updated_at FROM orgs WHERE slug = $1
`

func (q *Queries) GetOrgBySlugIncludingDeleted(ctx context.Context, db DBTX, slug string) (Org, error) {
	row := db.QueryRow(ctx, getOrgBySlugIncludingDeleted, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.AvatarObjectKey,
		&i.Location,
		&i.Website,
		&i.BillingEmail,
		&i.Plan,
		&i.AllowMemberRepoCreate,
		&i.CreatedByUserID,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolvePrincipal = `-- name: ResolvePrincipal :one

SELECT slug, kind, id FROM principals WHERE slug = $1
`

// ─── principals (read-only from this domain) ───────────────────────
// Single-query /{slug} resolver. Returns the (kind, id) tuple that
// /{slug}/* routes use to dispatch to the user-profile or org-profile
// handler. Both kinds share the slug PK so collisions are
// impossible at the DB layer.
func (q *Queries) ResolvePrincipal(ctx context.Context, db DBTX, slug string) (Principal, error) {
	row := db.QueryRow(ctx, resolvePrincipal, slug)
	var i Principal
	err := row.Scan(&i.Slug, &i.Kind, &i.ID)
	return i, err
}

const restoreOrg = `-- name: RestoreOrg :exec
UPDATE orgs SET deleted_at = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) RestoreOrg(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, restoreOrg, id)
	return err
}

const setOrgAllowMemberRepoCreate = `-- name: SetOrgAllowMemberRepoCreate :exec
UPDATE orgs SET allow_member_repo_create = $2, updated_at = now() WHERE id = $1
`

type SetOrgAllowMemberRepoCreateParams struct {
	ID                    int64
	AllowMemberRepoCreate bool
}

func (q *Queries) SetOrgAllowMemberRepoCreate(ctx context.Context, db DBTX, arg SetOrgAllowMemberRepoCreateParams) error {
	_, err := db.Exec(ctx, setOrgAllowMemberRepoCreate, arg.ID, arg.AllowMemberRepoCreate)
	return err
}

const setOrgAvatarKey = `-- name: SetOrgAvatarKey :exec
UPDATE orgs SET avatar_object_key = $2, updated_at = now() WHERE id = $1
`

type SetOrgAvatarKeyParams struct {
	ID              int64
	AvatarObjectKey pgtype.Text
}

func (q *Queries) SetOrgAvatarKey(ctx context.Context, db DBTX, arg SetOrgAvatarKeyParams) error {
	_, err := db.Exec(ctx, setOrgAvatarKey, arg.ID, arg.AvatarObjectKey)
	return err
}

const setOrgSuspended = `-- name: SetOrgSuspended :exec
UPDATE orgs
   SET suspended_at = CASE WHEN $2::boolean THEN now() ELSE NULL END,
       suspended_reason = CASE WHEN $2::boolean THEN $3 ELSE NULL END,
       updated_at = now()
 WHERE id = $1
`

type SetOrgSuspendedParams struct {
	ID              int64
	Column2         bool
	SuspendedReason pgtype.Text
}

func (q *Queries) SetOrgSuspended(ctx context.Context, db DBTX, arg SetOrgSuspendedParams) error {
	_, err := db.Exec(ctx, setOrgSuspended, arg.ID, arg.Column2, arg.SuspendedReason)
	return err
}

const softDeleteOrg = `-- name: SoftDeleteOrg :exec
UPDATE orgs SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteOrg(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, softDeleteOrg, id)
	return err
}

const updateOrgProfile = `-- name: UpdateOrgProfile :exec
UPDATE orgs
   SET display_name = $2,
       description  = $3,
       location     = $4,
       website      = $5,
       billing_email = $6,
       updated_at   = now()
 WHERE id = $1
`

type UpdateOrgProfileParams struct {
	ID           int64
	DisplayName  string
	Description  string
	Location     string
	Website      string
	BillingEmail string
}

func (q *Queries) UpdateOrgProfile(ctx context.Context, db DBTX, arg UpdateOrgProfileParams) error {
	_, err := db.Exec(ctx, updateOrgProfile,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.Location,
		arg.Website,
		arg.BillingEmail,
	)
	return err
}
