// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_reminders.sql

package orgsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceOrgScheduledReminder = `-- name: AdvanceOrgScheduledReminder :exec
UPDATE org_scheduled_reminders
SET next_run_at = $2,
    last_run_at = now(),
    last_run_status = $3,
    last_run_error = $4
WHERE id = $1
`

type AdvanceOrgScheduledReminderParams struct {
	ID            int64
	NextRunAt     pgtype.Timestamptz
	LastRunStatus OrgScheduledReminderStatus
	LastRunError  pgtype.Text
}

func (q *Queries) AdvanceOrgScheduledReminder(ctx context.Context, db DBTX, arg AdvanceOrgScheduledReminderParams) error {
	_, err := db.Exec(ctx, advanceOrgScheduledReminder,
		arg.ID,
		arg.NextRunAt,
		arg.LastRunStatus,
		arg.LastRunError,
	)
	return err
}

const claimDueOrgScheduledReminders = `-- name: ClaimDueOrgScheduledReminders :many
SELECT id, org_id, name, target, repo_id, team_id, cron_expr, timezone, next_run_at, last_run_at, last_run_status, last_run_error, condition_review_requested, condition_team_review_requested, min_age_minutes, paused_at, created_by_user_id, created_at, updated_at
FROM org_scheduled_reminders
WHERE paused_at IS NULL
  AND next_run_at <= now()
ORDER BY next_run_at ASC, id ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimDueOrgScheduledReminders(ctx context.Context, db DBTX, limit int32) ([]OrgScheduledReminder, error) {
	rows, err := db.Query(ctx, claimDueOrgScheduledReminders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgScheduledReminder{}
	for rows.Next() {
		var i OrgScheduledReminder
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Target,
			&i.RepoID,
			&i.TeamID,
			&i.CronExpr,
			&i.Timezone,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.LastRunError,
			&i.ConditionReviewRequested,
			&i.ConditionTeamReviewRequested,
			&i.MinAgeMinutes,
			&i.PausedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimOrgScheduledReminderDelivery = `-- name: ClaimOrgScheduledReminderDelivery :one
INSERT INTO org_scheduled_reminder_deliveries (
    schedule_id, run_key, pr_issue_id, recipient_user_id
) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING schedule_id, run_key, pr_issue_id, recipient_user_id, notification_id, delivered_at
`

type ClaimOrgScheduledReminderDeliveryParams struct {
	ScheduleID      int64
	RunKey          pgtype.Timestamptz
	PrIssueID       int64
	RecipientUserID int64
}

func (q *Queries) ClaimOrgScheduledReminderDelivery(ctx context.Context, db DBTX, arg ClaimOrgScheduledReminderDeliveryParams) (OrgScheduledReminderDelivery, error) {
	row := db.QueryRow(ctx, claimOrgScheduledReminderDelivery,
		arg.ScheduleID,
		arg.RunKey,
		arg.PrIssueID,
		arg.RecipientUserID,
	)
	var i OrgScheduledReminderDelivery
	err := row.Scan(
		&i.ScheduleID,
		&i.RunKey,
		&i.PrIssueID,
		&i.RecipientUserID,
		&i.NotificationID,
		&i.DeliveredAt,
	)
	return i, err
}

const countPrivateReposForScheduledReminderTarget = `-- name: CountPrivateReposForScheduledReminderTarget :one
SELECT count(*)::int
FROM repos r
WHERE r.owner_org_id = $1
  AND r.deleted_at IS NULL
  AND r.visibility = 'private'
  AND (
    $2::org_scheduled_reminder_target = 'all_repositories'
    OR ($2::org_scheduled_reminder_target = 'repository' AND r.id = $3::bigint)
    OR (
      $2::org_scheduled_reminder_target = 'team'
      AND EXISTS (
        SELECT 1
        FROM team_repo_access tra
        WHERE tra.repo_id = r.id
          AND tra.team_id = $4::bigint
      )
    )
  )
`

type CountPrivateReposForScheduledReminderTargetParams struct {
	OwnerOrgID pgtype.Int8
	Target     OrgScheduledReminderTarget
	RepoID     pgtype.Int8
	TeamID     pgtype.Int8
}

func (q *Queries) CountPrivateReposForScheduledReminderTarget(ctx context.Context, db DBTX, arg CountPrivateReposForScheduledReminderTargetParams) (int32, error) {
	row := db.QueryRow(ctx, countPrivateReposForScheduledReminderTarget,
		arg.OwnerOrgID,
		arg.Target,
		arg.RepoID,
		arg.TeamID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrgScheduledReminder = `-- name: CreateOrgScheduledReminder :one


INSERT INTO org_scheduled_reminders (
    org_id, name, target, repo_id, team_id, cron_expr, timezone,
    next_run_at, condition_review_requested,
    condition_team_review_requested, min_age_minutes, created_by_user_id
) VALUES (
    $1, $2, $3, $10::bigint, $11::bigint,
    $4, $5, $6, $7, $8, $9, $12::bigint
)
RETURNING id, org_id, name, target, repo_id, team_id, cron_expr, timezone, next_run_at, last_run_at, last_run_status, last_run_error, condition_review_requested, condition_team_review_requested, min_age_minutes, paused_at, created_by_user_id, created_at, updated_at
`

type CreateOrgScheduledReminderParams struct {
	OrgID                        int64
	Name                         string
	Target                       OrgScheduledReminderTarget
	CronExpr                     string
	Timezone                     string
	NextRunAt                    pgtype.Timestamptz
	ConditionReviewRequested     bool
	ConditionTeamReviewRequested bool
	MinAgeMinutes                int32
	RepoID                       pgtype.Int8
	TeamID                       pgtype.Int8
	CreatedByUserID              pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// ─── org_scheduled_reminders ─────────────────────────────────────
func (q *Queries) CreateOrgScheduledReminder(ctx context.Context, db DBTX, arg CreateOrgScheduledReminderParams) (OrgScheduledReminder, error) {
	row := db.QueryRow(ctx, createOrgScheduledReminder,
		arg.OrgID,
		arg.Name,
		arg.Target,
		arg.CronExpr,
		arg.Timezone,
		arg.NextRunAt,
		arg.ConditionReviewRequested,
		arg.ConditionTeamReviewRequested,
		arg.MinAgeMinutes,
		arg.RepoID,
		arg.TeamID,
		arg.CreatedByUserID,
	)
	var i OrgScheduledReminder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Target,
		&i.RepoID,
		&i.TeamID,
		&i.CronExpr,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.LastRunError,
		&i.ConditionReviewRequested,
		&i.ConditionTeamReviewRequested,
		&i.MinAgeMinutes,
		&i.PausedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgScheduledReminder = `-- name: DeleteOrgScheduledReminder :exec
DELETE FROM org_scheduled_reminders WHERE id = $1 AND org_id = $2
`

type DeleteOrgScheduledReminderParams struct {
	ID    int64
	OrgID int64
}

func (q *Queries) DeleteOrgScheduledReminder(ctx context.Context, db DBTX, arg DeleteOrgScheduledReminderParams) error {
	_, err := db.Exec(ctx, deleteOrgScheduledReminder, arg.ID, arg.OrgID)
	return err
}

const getOrgScheduledReminder = `-- name: GetOrgScheduledReminder :one
SELECT id, org_id, name, target, repo_id, team_id, cron_expr, timezone, next_run_at, last_run_at, last_run_status, last_run_error, condition_review_requested, condition_team_review_requested, min_age_minutes, paused_at, created_by_user_id, created_at, updated_at FROM org_scheduled_reminders WHERE id = $1
`

func (q *Queries) GetOrgScheduledReminder(ctx context.Context, db DBTX, id int64) (OrgScheduledReminder, error) {
	row := db.QueryRow(ctx, getOrgScheduledReminder, id)
	var i OrgScheduledReminder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Target,
		&i.RepoID,
		&i.TeamID,
		&i.CronExpr,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.LastRunError,
		&i.ConditionReviewRequested,
		&i.ConditionTeamReviewRequested,
		&i.MinAgeMinutes,
		&i.PausedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDirectReviewReminderCandidates = `-- name: ListDirectReviewReminderCandidates :many
SELECT rr.id AS review_request_id,
       i.id AS pr_issue_id,
       i.number AS pr_number,
       i.title AS pr_title,
       i.author_user_id,
       r.id AS repo_id,
       r.owner_user_id,
       r.owner_org_id,
       r.visibility::text AS repo_visibility,
       r.is_archived,
       r.deleted_at,
       r.is_paused,
       u.id AS recipient_user_id,
       u.username AS recipient_username,
       (u.suspended_at IS NOT NULL)::bool AS recipient_suspended,
       u.is_site_admin AS recipient_site_admin
FROM org_scheduled_reminders sr
JOIN repos r ON r.owner_org_id = sr.org_id
JOIN issues i ON i.repo_id = r.id AND i.kind = 'pr' AND i.state = 'open'
JOIN pull_requests pr ON pr.issue_id = i.id
JOIN pr_review_requests rr ON rr.pr_issue_id = i.id
JOIN users u ON u.id = rr.requested_user_id
WHERE sr.id = $1
  AND sr.condition_review_requested = true
  AND sr.paused_at IS NULL
  AND r.deleted_at IS NULL
  AND r.is_archived = false
  AND rr.requested_user_id IS NOT NULL
  AND rr.dismissed_at IS NULL
  AND rr.satisfied_by_review_id IS NULL
  AND u.deleted_at IS NULL
  AND i.updated_at <= now() - (sr.min_age_minutes * interval '1 minute')
  AND (
    sr.target = 'all_repositories'
    OR (sr.target = 'repository' AND r.id = sr.repo_id)
    OR (
      sr.target = 'team'
      AND EXISTS (
        SELECT 1 FROM team_members tm
        WHERE tm.team_id = sr.team_id
          AND tm.user_id = rr.requested_user_id
      )
    )
  )
ORDER BY r.id ASC, i.number ASC, u.username ASC
`

type ListDirectReviewReminderCandidatesRow struct {
	ReviewRequestID    int64
	PrIssueID          int64
	PrNumber           int64
	PrTitle            string
	AuthorUserID       pgtype.Int8
	RepoID             int64
	OwnerUserID        pgtype.Int8
	OwnerOrgID         pgtype.Int8
	RepoVisibility     string
	IsArchived         bool
	DeletedAt          pgtype.Timestamptz
	IsPaused           bool
	RecipientUserID    int64
	RecipientUsername  string
	RecipientSuspended bool
	RecipientSiteAdmin bool
}

func (q *Queries) ListDirectReviewReminderCandidates(ctx context.Context, db DBTX, id int64) ([]ListDirectReviewReminderCandidatesRow, error) {
	rows, err := db.Query(ctx, listDirectReviewReminderCandidates, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectReviewReminderCandidatesRow{}
	for rows.Next() {
		var i ListDirectReviewReminderCandidatesRow
		if err := rows.Scan(
			&i.ReviewRequestID,
			&i.PrIssueID,
			&i.PrNumber,
			&i.PrTitle,
			&i.AuthorUserID,
			&i.RepoID,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.RepoVisibility,
			&i.IsArchived,
			&i.DeletedAt,
			&i.IsPaused,
			&i.RecipientUserID,
			&i.RecipientUsername,
			&i.RecipientSuspended,
			&i.RecipientSiteAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgScheduledReminders = `-- name: ListOrgScheduledReminders :many
SELECT sr.id, sr.org_id, sr.name, sr.target, sr.repo_id, sr.team_id, sr.cron_expr, sr.timezone, sr.next_run_at, sr.last_run_at, sr.last_run_status, sr.last_run_error, sr.condition_review_requested, sr.condition_team_review_requested, sr.min_age_minutes, sr.paused_at, sr.created_by_user_id, sr.created_at, sr.updated_at,
       coalesce(r.name, '') AS repo_name,
       coalesce(t.slug, '') AS team_slug,
       coalesce(t.display_name, '') AS team_display_name
FROM org_scheduled_reminders sr
LEFT JOIN repos r ON r.id = sr.repo_id
LEFT JOIN teams t ON t.id = sr.team_id
WHERE sr.org_id = $1
ORDER BY sr.created_at DESC, sr.id DESC
`

type ListOrgScheduledRemindersRow struct {
	ID                           int64
	OrgID                        int64
	Name                         string
	Target                       OrgScheduledReminderTarget
	RepoID                       pgtype.Int8
	TeamID                       pgtype.Int8
	CronExpr                     string
	Timezone                     string
	NextRunAt                    pgtype.Timestamptz
	LastRunAt                    pgtype.Timestamptz
	LastRunStatus                OrgScheduledReminderStatus
	LastRunError                 pgtype.Text
	ConditionReviewRequested     bool
	ConditionTeamReviewRequested bool
	MinAgeMinutes                int32
	PausedAt                     pgtype.Timestamptz
	CreatedByUserID              pgtype.Int8
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	RepoName                     string
	TeamSlug                     string
	TeamDisplayName              string
}

func (q *Queries) ListOrgScheduledReminders(ctx context.Context, db DBTX, orgID int64) ([]ListOrgScheduledRemindersRow, error) {
	rows, err := db.Query(ctx, listOrgScheduledReminders, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgScheduledRemindersRow{}
	for rows.Next() {
		var i ListOrgScheduledRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Target,
			&i.RepoID,
			&i.TeamID,
			&i.CronExpr,
			&i.Timezone,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.LastRunError,
			&i.ConditionReviewRequested,
			&i.ConditionTeamReviewRequested,
			&i.MinAgeMinutes,
			&i.PausedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoName,
			&i.TeamSlug,
			&i.TeamDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamReviewReminderCandidates = `-- name: ListTeamReviewReminderCandidates :many
SELECT rr.id AS review_request_id,
       i.id AS pr_issue_id,
       i.number AS pr_number,
       i.title AS pr_title,
       i.author_user_id,
       r.id AS repo_id,
       r.owner_user_id,
       r.owner_org_id,
       r.visibility::text AS repo_visibility,
       r.is_archived,
       r.deleted_at,
       r.is_paused,
       u.id AS recipient_user_id,
       u.username AS recipient_username,
       (u.suspended_at IS NOT NULL)::bool AS recipient_suspended,
       u.is_site_admin AS recipient_site_admin
FROM org_scheduled_reminders sr
JOIN repos r ON r.owner_org_id = sr.org_id
JOIN issues i ON i.repo_id = r.id AND i.kind = 'pr' AND i.state = 'open'
JOIN pull_requests pr ON pr.issue_id = i.id
JOIN pr_review_requests rr ON rr.pr_issue_id = i.id
JOIN teams requested_team ON requested_team.id = rr.requested_team_id
JOIN team_members tm ON tm.team_id = requested_team.id
JOIN users u ON u.id = tm.user_id
WHERE sr.id = $1
  AND sr.condition_team_review_requested = true
  AND sr.paused_at IS NULL
  AND r.deleted_at IS NULL
  AND r.is_archived = false
  AND rr.requested_team_id IS NOT NULL
  AND requested_team.org_id = sr.org_id
  AND rr.dismissed_at IS NULL
  AND rr.satisfied_by_review_id IS NULL
  AND u.deleted_at IS NULL
  AND i.updated_at <= now() - (sr.min_age_minutes * interval '1 minute')
  AND (
    sr.target = 'all_repositories'
    OR (sr.target = 'repository' AND r.id = sr.repo_id)
    OR (sr.target = 'team' AND requested_team.id = sr.team_id)
  )
ORDER BY r.id ASC, i.number ASC, u.username ASC
`

type ListTeamReviewReminderCandidatesRow struct {
	ReviewRequestID    int64
	PrIssueID          int64
	PrNumber           int64
	PrTitle            string
	AuthorUserID       pgtype.Int8
	RepoID             int64
	OwnerUserID        pgtype.Int8
	OwnerOrgID         pgtype.Int8
	RepoVisibility     string
	IsArchived         bool
	DeletedAt          pgtype.Timestamptz
	IsPaused           bool
	RecipientUserID    int64
	RecipientUsername  string
	RecipientSuspended bool
	RecipientSiteAdmin bool
}

func (q *Queries) ListTeamReviewReminderCandidates(ctx context.Context, db DBTX, id int64) ([]ListTeamReviewReminderCandidatesRow, error) {
	rows, err := db.Query(ctx, listTeamReviewReminderCandidates, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamReviewReminderCandidatesRow{}
	for rows.Next() {
		var i ListTeamReviewReminderCandidatesRow
		if err := rows.Scan(
			&i.ReviewRequestID,
			&i.PrIssueID,
			&i.PrNumber,
			&i.PrTitle,
			&i.AuthorUserID,
			&i.RepoID,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.RepoVisibility,
			&i.IsArchived,
			&i.DeletedAt,
			&i.IsPaused,
			&i.RecipientUserID,
			&i.RecipientUsername,
			&i.RecipientSuspended,
			&i.RecipientSiteAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrgScheduledReminderDeliverySent = `-- name: MarkOrgScheduledReminderDeliverySent :exec
UPDATE org_scheduled_reminder_deliveries
SET notification_id = $5,
    delivered_at = now()
WHERE schedule_id = $1
  AND run_key = $2
  AND pr_issue_id = $3
  AND recipient_user_id = $4
`

type MarkOrgScheduledReminderDeliverySentParams struct {
	ScheduleID      int64
	RunKey          pgtype.Timestamptz
	PrIssueID       int64
	RecipientUserID int64
	NotificationID  pgtype.Int8
}

func (q *Queries) MarkOrgScheduledReminderDeliverySent(ctx context.Context, db DBTX, arg MarkOrgScheduledReminderDeliverySentParams) error {
	_, err := db.Exec(ctx, markOrgScheduledReminderDeliverySent,
		arg.ScheduleID,
		arg.RunKey,
		arg.PrIssueID,
		arg.RecipientUserID,
		arg.NotificationID,
	)
	return err
}

const pauseOrgScheduledReminder = `-- name: PauseOrgScheduledReminder :exec
UPDATE org_scheduled_reminders
SET paused_at = coalesce(paused_at, now())
WHERE id = $1 AND org_id = $2
`

type PauseOrgScheduledReminderParams struct {
	ID    int64
	OrgID int64
}

func (q *Queries) PauseOrgScheduledReminder(ctx context.Context, db DBTX, arg PauseOrgScheduledReminderParams) error {
	_, err := db.Exec(ctx, pauseOrgScheduledReminder, arg.ID, arg.OrgID)
	return err
}

const resumeOrgScheduledReminder = `-- name: ResumeOrgScheduledReminder :one
UPDATE org_scheduled_reminders
SET paused_at = NULL,
    next_run_at = $3,
    last_run_status = 'pending',
    last_run_error = NULL
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, target, repo_id, team_id, cron_expr, timezone, next_run_at, last_run_at, last_run_status, last_run_error, condition_review_requested, condition_team_review_requested, min_age_minutes, paused_at, created_by_user_id, created_at, updated_at
`

type ResumeOrgScheduledReminderParams struct {
	ID        int64
	OrgID     int64
	NextRunAt pgtype.Timestamptz
}

func (q *Queries) ResumeOrgScheduledReminder(ctx context.Context, db DBTX, arg ResumeOrgScheduledReminderParams) (OrgScheduledReminder, error) {
	row := db.QueryRow(ctx, resumeOrgScheduledReminder, arg.ID, arg.OrgID, arg.NextRunAt)
	var i OrgScheduledReminder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Target,
		&i.RepoID,
		&i.TeamID,
		&i.CronExpr,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.LastRunError,
		&i.ConditionReviewRequested,
		&i.ConditionTeamReviewRequested,
		&i.MinAgeMinutes,
		&i.PausedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgScheduledReminder = `-- name: UpdateOrgScheduledReminder :one
UPDATE org_scheduled_reminders
SET name = $2,
    target = $3,
    repo_id = $11::bigint,
    team_id = $12::bigint,
    cron_expr = $4,
    timezone = $5,
    next_run_at = $6,
    condition_review_requested = $7,
    condition_team_review_requested = $8,
    min_age_minutes = $9,
    paused_at = $13::timestamptz,
    last_run_status = 'pending',
    last_run_error = NULL
WHERE id = $1 AND org_id = $10
RETURNING id, org_id, name, target, repo_id, team_id, cron_expr, timezone, next_run_at, last_run_at, last_run_status, last_run_error, condition_review_requested, condition_team_review_requested, min_age_minutes, paused_at, created_by_user_id, created_at, updated_at
`

type UpdateOrgScheduledReminderParams struct {
	ID                           int64
	Name                         string
	Target                       OrgScheduledReminderTarget
	CronExpr                     string
	Timezone                     string
	NextRunAt                    pgtype.Timestamptz
	ConditionReviewRequested     bool
	ConditionTeamReviewRequested bool
	MinAgeMinutes                int32
	OrgID                        int64
	RepoID                       pgtype.Int8
	TeamID                       pgtype.Int8
	PausedAt                     pgtype.Timestamptz
}

func (q *Queries) UpdateOrgScheduledReminder(ctx context.Context, db DBTX, arg UpdateOrgScheduledReminderParams) (OrgScheduledReminder, error) {
	row := db.QueryRow(ctx, updateOrgScheduledReminder,
		arg.ID,
		arg.Name,
		arg.Target,
		arg.CronExpr,
		arg.Timezone,
		arg.NextRunAt,
		arg.ConditionReviewRequested,
		arg.ConditionTeamReviewRequested,
		arg.MinAgeMinutes,
		arg.OrgID,
		arg.RepoID,
		arg.TeamID,
		arg.PausedAt,
	)
	var i OrgScheduledReminder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Target,
		&i.RepoID,
		&i.TeamID,
		&i.CronExpr,
		&i.Timezone,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.LastRunError,
		&i.ConditionReviewRequested,
		&i.ConditionTeamReviewRequested,
		&i.MinAgeMinutes,
		&i.PausedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
