// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package orgsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :exec

INSERT INTO team_members (team_id, user_id, role, added_by_user_id)
VALUES ($1, $2, $3, $4::bigint)
ON CONFLICT (team_id, user_id) DO NOTHING
`

type AddTeamMemberParams struct {
	TeamID        int64
	UserID        int64
	Role          TeamRole
	AddedByUserID pgtype.Int8
}

// ─── team_members ─────────────────────────────────────────────────
func (q *Queries) AddTeamMember(ctx context.Context, db DBTX, arg AddTeamMemberParams) error {
	_, err := db.Exec(ctx, addTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.AddedByUserID,
	)
	return err
}

const createTeam = `-- name: CreateTeam :one


INSERT INTO teams (org_id, slug, display_name, description, parent_team_id, privacy, created_by_user_id)
VALUES ($1, $2, $3, $4, $6::bigint, $5, $7::bigint)
RETURNING id, org_id, slug, display_name, description, parent_team_id, privacy, created_by_user_id, created_at, updated_at
`

type CreateTeamParams struct {
	OrgID           int64
	Slug            string
	DisplayName     string
	Description     string
	Privacy         TeamPrivacy
	ParentTeamID    pgtype.Int8
	CreatedByUserID pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
// ─── teams ─────────────────────────────────────────────────────────
func (q *Queries) CreateTeam(ctx context.Context, db DBTX, arg CreateTeamParams) (Team, error) {
	row := db.QueryRow(ctx, createTeam,
		arg.OrgID,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.Privacy,
		arg.ParentTeamID,
		arg.CreatedByUserID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ParentTeamID,
		&i.Privacy,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

// Children's parent_team_id flips to NULL via the FK ON DELETE SET NULL,
// promoting them to top-level — matches the "deleting parent doesn't
// delete children" intent in the spec's pitfalls.
func (q *Queries) DeleteTeam(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, org_id, slug, display_name, description, parent_team_id, privacy, created_by_user_id, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, db DBTX, id int64) (Team, error) {
	row := db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ParentTeamID,
		&i.Privacy,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByOrgAndSlug = `-- name: GetTeamByOrgAndSlug :one
SELECT id, org_id, slug, display_name, description, parent_team_id, privacy, created_by_user_id, created_at, updated_at FROM teams WHERE org_id = $1 AND slug = $2
`

type GetTeamByOrgAndSlugParams struct {
	OrgID int64
	Slug  string
}

func (q *Queries) GetTeamByOrgAndSlug(ctx context.Context, db DBTX, arg GetTeamByOrgAndSlugParams) (Team, error) {
	row := db.QueryRow(ctx, getTeamByOrgAndSlug, arg.OrgID, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.ParentTeamID,
		&i.Privacy,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamRepoAccess = `-- name: GetTeamRepoAccess :one
SELECT team_id, repo_id, role, added_by_user_id, added_at FROM team_repo_access WHERE team_id = $1 AND repo_id = $2
`

type GetTeamRepoAccessParams struct {
	TeamID int64
	RepoID int64
}

func (q *Queries) GetTeamRepoAccess(ctx context.Context, db DBTX, arg GetTeamRepoAccessParams) (TeamRepoAccess, error) {
	row := db.QueryRow(ctx, getTeamRepoAccess, arg.TeamID, arg.RepoID)
	var i TeamRepoAccess
	err := row.Scan(
		&i.TeamID,
		&i.RepoID,
		&i.Role,
		&i.AddedByUserID,
		&i.AddedAt,
	)
	return i, err
}

const grantTeamRepoAccess = `-- name: GrantTeamRepoAccess :exec

INSERT INTO team_repo_access (team_id, repo_id, role, added_by_user_id)
VALUES ($1, $2, $3, $4::bigint)
ON CONFLICT (team_id, repo_id) DO UPDATE SET role = EXCLUDED.role
`

type GrantTeamRepoAccessParams struct {
	TeamID        int64
	RepoID        int64
	Role          TeamRepoRole
	AddedByUserID pgtype.Int8
}

// ─── team_repo_access ─────────────────────────────────────────────
func (q *Queries) GrantTeamRepoAccess(ctx context.Context, db DBTX, arg GrantTeamRepoAccessParams) error {
	_, err := db.Exec(ctx, grantTeamRepoAccess,
		arg.TeamID,
		arg.RepoID,
		arg.Role,
		arg.AddedByUserID,
	)
	return err
}

const listChildTeams = `-- name: ListChildTeams :many
SELECT id, org_id, slug, display_name, description, parent_team_id, privacy, created_by_user_id, created_at, updated_at FROM teams WHERE parent_team_id = $1 ORDER BY slug ASC
`

func (q *Queries) ListChildTeams(ctx context.Context, db DBTX, parentTeamID pgtype.Int8) ([]Team, error) {
	rows, err := db.Query(ctx, listChildTeams, parentTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ParentTeamID,
			&i.Privacy,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoTeamGrants = `-- name: ListRepoTeamGrants :many
SELECT a.team_id, a.repo_id, a.role, a.added_by_user_id, a.added_at,
       t.slug AS team_slug, t.display_name AS team_display_name,
       t.privacy::text AS team_privacy
FROM team_repo_access a
JOIN teams t ON t.id = a.team_id
WHERE a.repo_id = $1
ORDER BY t.slug ASC
`

type ListRepoTeamGrantsRow struct {
	TeamID          int64
	RepoID          int64
	Role            TeamRepoRole
	AddedByUserID   pgtype.Int8
	AddedAt         pgtype.Timestamptz
	TeamSlug        string
	TeamDisplayName string
	TeamPrivacy     string
}

// All teams with grants on a single repo; for repo settings/access page.
func (q *Queries) ListRepoTeamGrants(ctx context.Context, db DBTX, repoID int64) ([]ListRepoTeamGrantsRow, error) {
	rows, err := db.Query(ctx, listRepoTeamGrants, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoTeamGrantsRow{}
	for rows.Next() {
		var i ListRepoTeamGrantsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.RepoID,
			&i.Role,
			&i.AddedByUserID,
			&i.AddedAt,
			&i.TeamSlug,
			&i.TeamDisplayName,
			&i.TeamPrivacy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamAccessForRepoAndTeams = `-- name: ListTeamAccessForRepoAndTeams :many
SELECT team_id, repo_id, role
FROM team_repo_access
WHERE repo_id = $1 AND team_id = ANY($2::bigint[])
`

type ListTeamAccessForRepoAndTeamsParams struct {
	RepoID  int64
	Column2 []int64
}

type ListTeamAccessForRepoAndTeamsRow struct {
	TeamID int64
	RepoID int64
	Role   TeamRepoRole
}

// Policy hot-path: given a repo and a set of team_ids the actor
// belongs to (incl. inherited), return the access rows. Caller picks
// the highest role.
func (q *Queries) ListTeamAccessForRepoAndTeams(ctx context.Context, db DBTX, arg ListTeamAccessForRepoAndTeamsParams) ([]ListTeamAccessForRepoAndTeamsRow, error) {
	rows, err := db.Query(ctx, listTeamAccessForRepoAndTeams, arg.RepoID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamAccessForRepoAndTeamsRow{}
	for rows.Next() {
		var i ListTeamAccessForRepoAndTeamsRow
		if err := rows.Scan(&i.TeamID, &i.RepoID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT m.team_id, m.user_id, m.role, m.added_by_user_id, m.added_at,
       u.username, u.display_name
FROM team_members m
JOIN users u ON u.id = m.user_id
WHERE m.team_id = $1 AND u.deleted_at IS NULL
ORDER BY m.role ASC, u.username ASC
`

type ListTeamMembersRow struct {
	TeamID        int64
	UserID        int64
	Role          TeamRole
	AddedByUserID pgtype.Int8
	AddedAt       pgtype.Timestamptz
	Username      string
	DisplayName   string
}

func (q *Queries) ListTeamMembers(ctx context.Context, db DBTX, teamID int64) ([]ListTeamMembersRow, error) {
	rows, err := db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.AddedByUserID,
			&i.AddedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRepoAccess = `-- name: ListTeamRepoAccess :many
SELECT a.team_id, a.repo_id, a.role, a.added_by_user_id, a.added_at,
       r.name AS repo_name, r.visibility::text AS visibility
FROM team_repo_access a
JOIN repos r ON r.id = a.repo_id
WHERE a.team_id = $1 AND r.deleted_at IS NULL
ORDER BY r.name ASC
`

type ListTeamRepoAccessRow struct {
	TeamID        int64
	RepoID        int64
	Role          TeamRepoRole
	AddedByUserID pgtype.Int8
	AddedAt       pgtype.Timestamptz
	RepoName      string
	Visibility    string
}

// All repos the team has any grant on; for the team-view page.
func (q *Queries) ListTeamRepoAccess(ctx context.Context, db DBTX, teamID int64) ([]ListTeamRepoAccessRow, error) {
	rows, err := db.Query(ctx, listTeamRepoAccess, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamRepoAccessRow{}
	for rows.Next() {
		var i ListTeamRepoAccessRow
		if err := rows.Scan(
			&i.TeamID,
			&i.RepoID,
			&i.Role,
			&i.AddedByUserID,
			&i.AddedAt,
			&i.RepoName,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForOrg = `-- name: ListTeamsForOrg :many
SELECT id, org_id, slug, display_name, description, parent_team_id, privacy, created_by_user_id, created_at, updated_at FROM teams WHERE org_id = $1 ORDER BY slug ASC
`

func (q *Queries) ListTeamsForOrg(ctx context.Context, db DBTX, orgID int64) ([]Team, error) {
	rows, err := db.Query(ctx, listTeamsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ParentTeamID,
			&i.Privacy,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUserInOrg = `-- name: ListTeamsForUserInOrg :many
SELECT t.id, t.org_id, t.slug, t.display_name, t.description,
       t.parent_team_id, t.privacy, t.created_by_user_id,
       t.created_at, t.updated_at,
       m.role AS member_role
FROM team_members m
JOIN teams t ON t.id = m.team_id
WHERE t.org_id = $1 AND m.user_id = $2
`

type ListTeamsForUserInOrgParams struct {
	OrgID  int64
	UserID int64
}

type ListTeamsForUserInOrgRow struct {
	ID              int64
	OrgID           int64
	Slug            string
	DisplayName     string
	Description     string
	ParentTeamID    pgtype.Int8
	Privacy         TeamPrivacy
	CreatedByUserID pgtype.Int8
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	MemberRole      TeamRole
}

// Returns the teams a user directly belongs to within an org. The
// policy aggregator unions this with each row's parent_team_id to
// get the inherited set.
func (q *Queries) ListTeamsForUserInOrg(ctx context.Context, db DBTX, arg ListTeamsForUserInOrgParams) ([]ListTeamsForUserInOrgRow, error) {
	rows, err := db.Query(ctx, listTeamsForUserInOrg, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForUserInOrgRow{}
	for rows.Next() {
		var i ListTeamsForUserInOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.ParentTeamID,
			&i.Privacy,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID int64
	UserID int64
}

func (q *Queries) RemoveTeamMember(ctx context.Context, db DBTX, arg RemoveTeamMemberParams) error {
	_, err := db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const revokeTeamRepoAccess = `-- name: RevokeTeamRepoAccess :exec
DELETE FROM team_repo_access WHERE team_id = $1 AND repo_id = $2
`

type RevokeTeamRepoAccessParams struct {
	TeamID int64
	RepoID int64
}

func (q *Queries) RevokeTeamRepoAccess(ctx context.Context, db DBTX, arg RevokeTeamRepoAccessParams) error {
	_, err := db.Exec(ctx, revokeTeamRepoAccess, arg.TeamID, arg.RepoID)
	return err
}

const setTeamMemberRole = `-- name: SetTeamMemberRole :exec
UPDATE team_members SET role = $3 WHERE team_id = $1 AND user_id = $2
`

type SetTeamMemberRoleParams struct {
	TeamID int64
	UserID int64
	Role   TeamRole
}

func (q *Queries) SetTeamMemberRole(ctx context.Context, db DBTX, arg SetTeamMemberRoleParams) error {
	_, err := db.Exec(ctx, setTeamMemberRole, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const setTeamParent = `-- name: SetTeamParent :exec
UPDATE teams SET parent_team_id = $2::bigint, updated_at = now()
WHERE id = $1
`

type SetTeamParentParams struct {
	ID           int64
	ParentTeamID pgtype.Int8
}

// The one-level-nesting BEFORE trigger blocks invalid moves; the
// caller surfaces the SQLSTATE 23514 as a friendly error.
func (q *Queries) SetTeamParent(ctx context.Context, db DBTX, arg SetTeamParentParams) error {
	_, err := db.Exec(ctx, setTeamParent, arg.ID, arg.ParentTeamID)
	return err
}

const updateTeamProfile = `-- name: UpdateTeamProfile :exec
UPDATE teams SET display_name = $2, description = $3, privacy = $4, updated_at = now()
WHERE id = $1
`

type UpdateTeamProfileParams struct {
	ID          int64
	DisplayName string
	Description string
	Privacy     TeamPrivacy
}

func (q *Queries) UpdateTeamProfile(ctx context.Context, db DBTX, arg UpdateTeamProfileParams) error {
	_, err := db.Exec(ctx, updateTeamProfile,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.Privacy,
	)
	return err
}
