// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package packagesdb

import (
	"context"
)

type Querier interface {
	DeleteRepoPackage(ctx context.Context, db DBTX, arg DeleteRepoPackageParams) (int64, error)
	EnsureRepoPackageVersion(ctx context.Context, db DBTX, arg EnsureRepoPackageVersionParams) (RepoPackageVersion, error)
	GetRepoPackageFile(ctx context.Context, db DBTX, arg GetRepoPackageFileParams) (GetRepoPackageFileRow, error)
	GetRepoPackageForRepo(ctx context.Context, db DBTX, arg GetRepoPackageForRepoParams) (RepoPackage, error)
	InsertRepoPackageFile(ctx context.Context, db DBTX, arg InsertRepoPackageFileParams) (RepoPackageFile, error)
	ListRepoPackageFiles(ctx context.Context, db DBTX, arg ListRepoPackageFilesParams) ([]ListRepoPackageFilesRow, error)
	ListRepoPackageObjectKeys(ctx context.Context, db DBTX, arg ListRepoPackageObjectKeysParams) ([]string, error)
	ListRepoPackageVersions(ctx context.Context, db DBTX, arg ListRepoPackageVersionsParams) ([]ListRepoPackageVersionsRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	ListRepoPackages(ctx context.Context, db DBTX, repoID int64) ([]ListRepoPackagesRow, error)
	RefreshRepoPackageStats(ctx context.Context, db DBTX, packageID int64) (RepoPackage, error)
	RefreshRepoPackageVersionStats(ctx context.Context, db DBTX, versionID int64) (RepoPackageVersion, error)
	UpsertRepoPackage(ctx context.Context, db DBTX, arg UpsertRepoPackageParams) (RepoPackage, error)
}

var _ Querier = (*Queries)(nil)
