// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events_pending.sql

package workerdb

import (
	"context"
)

const insertWebhookEventPending = `-- name: InsertWebhookEventPending :one

INSERT INTO webhook_events_pending (repo_id, event_kind, payload)
VALUES ($1, $2, $3)
RETURNING id, repo_id, event_kind, payload, created_at
`

type InsertWebhookEventPendingParams struct {
	RepoID    int64
	EventKind string
	Payload   []byte
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The S33 webhook deliverer drains this. S14 only inserts; the
// accumulator is intentionally separate from the generic jobs table so
// S33 controls its own retry / batching / fan-out shape.
func (q *Queries) InsertWebhookEventPending(ctx context.Context, db DBTX, arg InsertWebhookEventPendingParams) (WebhookEventsPending, error) {
	row := db.QueryRow(ctx, insertWebhookEventPending, arg.RepoID, arg.EventKind, arg.Payload)
	var i WebhookEventsPending
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.EventKind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
