// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package issuesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ─── issue ↔ label ───────────────────────────────────────────────────
	AddIssueLabel(ctx context.Context, db DBTX, arg AddIssueLabelParams) error
	// UPDATE … RETURNING is concurrency-safe: each row update is
	// serialized by the row lock; concurrent transactions see different
	// values. The caller wraps this in the same tx as the issue insert.
	AllocateIssueNumber(ctx context.Context, db DBTX, repoID int64) (int64, error)
	// ─── assignees ───────────────────────────────────────────────────────
	AssignUserToIssue(ctx context.Context, db DBTX, arg AssignUserToIssueParams) error
	CountIssueAssignees(ctx context.Context, db DBTX, issueID int64) (int64, error)
	// I7a (audit-I12): gh-compat issue/PR responses expose a `comments`
	// count distinct from the `/comments` collection endpoint. One COUNT
	// per fetched issue; covered by the existing issue_comments(issue_id)
	// index.
	CountIssueComments(ctx context.Context, db DBTX, issueID int64) (int64, error)
	CountIssueEvents(ctx context.Context, db DBTX, issueID int64) (int64, error)
	CountIssues(ctx context.Context, db DBTX, arg CountIssuesParams) (int64, error)
	// ─── issues ──────────────────────────────────────────────────────────
	CreateIssue(ctx context.Context, db DBTX, arg CreateIssueParams) (Issue, error)
	// ─── comments ────────────────────────────────────────────────────────
	CreateIssueComment(ctx context.Context, db DBTX, arg CreateIssueCommentParams) (IssueComment, error)
	// ─── labels ──────────────────────────────────────────────────────────
	CreateLabel(ctx context.Context, db DBTX, arg CreateLabelParams) (Label, error)
	// ─── milestones ──────────────────────────────────────────────────────
	CreateMilestone(ctx context.Context, db DBTX, arg CreateMilestoneParams) (Milestone, error)
	// G8 (F45): hard-delete an issue row. The `issues` table has every
	// child relation wired ON DELETE CASCADE (comments, labels, assignees,
	// milestones, events, references, search index, …), so the cascade
	// does the rest. Caller is responsible for the policy gate
	// (ActionRepoAdmin) and audit emission.
	DeleteIssue(ctx context.Context, db DBTX, id int64) error
	DeleteIssueComment(ctx context.Context, db DBTX, id int64) error
	DeleteLabel(ctx context.Context, db DBTX, id int64) error
	DeleteMilestone(ctx context.Context, db DBTX, id int64) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// ─── per-repo numbering ───────────────────────────────────────────────
	// Lazy-initialize the counter row. Idempotent — invoked from repo
	// create AND from the first issue insert (defensive in case someone
	// migrates an old repo that predates S21).
	EnsureRepoIssueCounter(ctx context.Context, db DBTX, repoID int64) error
	GetIssueByID(ctx context.Context, db DBTX, id int64) (Issue, error)
	GetIssueByNumber(ctx context.Context, db DBTX, arg GetIssueByNumberParams) (Issue, error)
	GetIssueComment(ctx context.Context, db DBTX, id int64) (IssueComment, error)
	GetLabelByName(ctx context.Context, db DBTX, arg GetLabelByNameParams) (Label, error)
	GetMilestone(ctx context.Context, db DBTX, id int64) (Milestone, error)
	// ─── events + references ─────────────────────────────────────────────
	InsertIssueEvent(ctx context.Context, db DBTX, arg InsertIssueEventParams) (IssueEvent, error)
	InsertIssueReference(ctx context.Context, db DBTX, arg InsertIssueReferenceParams) error
	IssueAssigneeExists(ctx context.Context, db DBTX, arg IssueAssigneeExistsParams) (bool, error)
	ListIssueAssignees(ctx context.Context, db DBTX, issueID int64) ([]ListIssueAssigneesRow, error)
	ListIssueComments(ctx context.Context, db DBTX, issueID int64) ([]IssueComment, error)
	ListIssueEvents(ctx context.Context, db DBTX, issueID int64) ([]IssueEvent, error)
	// Paginated timeline shape for the REST `/issues/{n}/events` endpoint:
	// the same event rows ListIssueEvents returns, but LEFT-joined to users
	// so the response can carry `actor_username` without a second round-trip.
	// Suspended/deleted actor rows still appear (the timeline is historical
	// truth), with NULL username when the user row is unrecoverable.
	ListIssueEventsWithActor(ctx context.Context, db DBTX, arg ListIssueEventsWithActorParams) ([]ListIssueEventsWithActorRow, error)
	// Filterable list. Caller passes a state filter (open/closed/all
	// where 'all' is encoded as NULL); label/assignee/author/milestone
	// filtering happens after this query in Go for v1 — see the
	// internal/issues/list.go composer. Per-page hardcoded at 25 in the
	// handler; offset is the (page-1)*25.
	ListIssues(ctx context.Context, db DBTX, arg ListIssuesParams) ([]Issue, error)
	ListLabels(ctx context.Context, db DBTX, repoID int64) ([]Label, error)
	ListLabelsOnIssue(ctx context.Context, db DBTX, issueID int64) ([]Label, error)
	ListMilestones(ctx context.Context, db DBTX, repoID int64) ([]Milestone, error)
	// Cross-repository profile contribution activity. The handler performs the
	// final repo visibility gate with policy.IsVisibleTo so private issues and
	// PRs never leak through the public profile timeline.
	ListProfileAuthoredIssuesForUser(ctx context.Context, db DBTX, arg ListProfileAuthoredIssuesForUserParams) ([]ListProfileAuthoredIssuesForUserRow, error)
	// Open + closed counts for the milestone progress bar.
	MilestoneIssueCounts(ctx context.Context, db DBTX, milestoneID pgtype.Int8) (MilestoneIssueCountsRow, error)
	RemoveIssueLabel(ctx context.Context, db DBTX, arg RemoveIssueLabelParams) error
	SetIssueLock(ctx context.Context, db DBTX, arg SetIssueLockParams) error
	SetIssueMilestone(ctx context.Context, db DBTX, arg SetIssueMilestoneParams) error
	// H15 / H14: gate on the state actually changing. Pre-fix
	// `setState` unconditionally rewrote state_reason + closed_at even
	// when the state value was already the requested one — so two
	// concurrent close-with-comment calls each succeeded AND emitted a
	// "closed" timeline event AND posted a comment, persisting both. The
	// `WHERE state != $2` clause makes the UPDATE a no-op for already-
	// closed-and-now-closed (and same for open), and the :execrows
	// variant lets the caller observe whether a transition actually
	// happened so it can gate downstream side-effects (event emit, audit
	// record, CLI's success line).
	SetIssueState(ctx context.Context, db DBTX, arg SetIssueStateParams) (int64, error)
	SetMilestoneState(ctx context.Context, db DBTX, arg SetMilestoneStateParams) error
	UnassignUserFromIssue(ctx context.Context, db DBTX, arg UnassignUserFromIssueParams) error
	UpdateIssueCommentBody(ctx context.Context, db DBTX, arg UpdateIssueCommentBodyParams) error
	UpdateIssueTitleBody(ctx context.Context, db DBTX, arg UpdateIssueTitleBodyParams) error
	UpdateLabel(ctx context.Context, db DBTX, arg UpdateLabelParams) error
	UpdateMilestone(ctx context.Context, db DBTX, arg UpdateMilestoneParams) error
}

var _ Querier = (*Queries)(nil)
