---
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: daemon-reload
  systemd: { daemon_reload: yes }

- name: restart dnsmasq
  systemd: { name: dnsmasq, state: restarted, enabled: yes }

- name: restart shithub-runner-firewall
  systemd: { name: shithub-runner-firewall, state: restarted, enabled: yes, daemon_reload: yes }

- name: restart shithubd-runner
  systemd: { name: shithubd-runner, state: restarted, enabled: yes }
