// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branch_protection.sql

package reposdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBranchProtectionRule = `-- name: DeleteBranchProtectionRule :exec
DELETE FROM branch_protection_rules WHERE id = $1
`

func (q *Queries) DeleteBranchProtectionRule(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, deleteBranchProtectionRule, id)
	return err
}

const getBranchProtectionRule = `-- name: GetBranchProtectionRule :one
SELECT id, repo_id, pattern,
       prevent_force_push, prevent_deletion, require_pr_for_push,
       allowed_pusher_user_ids,
       require_signed_commits, status_checks_required,
       created_at, updated_at, created_by_user_id,
       required_review_count, dismiss_stale_reviews_on_push, require_code_owner_review
FROM branch_protection_rules
WHERE id = $1
`

func (q *Queries) GetBranchProtectionRule(ctx context.Context, db DBTX, id int64) (BranchProtectionRule, error) {
	row := db.QueryRow(ctx, getBranchProtectionRule, id)
	var i BranchProtectionRule
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Pattern,
		&i.PreventForcePush,
		&i.PreventDeletion,
		&i.RequirePrForPush,
		&i.AllowedPusherUserIds,
		&i.RequireSignedCommits,
		&i.StatusChecksRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserID,
		&i.RequiredReviewCount,
		&i.DismissStaleReviewsOnPush,
		&i.RequireCodeOwnerReview,
	)
	return i, err
}

const listBranchProtectionRules = `-- name: ListBranchProtectionRules :many

SELECT id, repo_id, pattern,
       prevent_force_push, prevent_deletion, require_pr_for_push,
       allowed_pusher_user_ids,
       require_signed_commits, status_checks_required,
       created_at, updated_at, created_by_user_id,
       required_review_count, dismiss_stale_reviews_on_push, require_code_owner_review
FROM branch_protection_rules
WHERE repo_id = $1
ORDER BY pattern
`

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) ListBranchProtectionRules(ctx context.Context, db DBTX, repoID int64) ([]BranchProtectionRule, error) {
	rows, err := db.Query(ctx, listBranchProtectionRules, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchProtectionRule{}
	for rows.Next() {
		var i BranchProtectionRule
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Pattern,
			&i.PreventForcePush,
			&i.PreventDeletion,
			&i.RequirePrForPush,
			&i.AllowedPusherUserIds,
			&i.RequireSignedCommits,
			&i.StatusChecksRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUserID,
			&i.RequiredReviewCount,
			&i.DismissStaleReviewsOnPush,
			&i.RequireCodeOwnerReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranchProtectionReviewSettings = `-- name: UpdateBranchProtectionReviewSettings :exec
UPDATE branch_protection_rules
SET required_review_count = $2,
    dismiss_stale_reviews_on_push = $3,
    require_code_owner_review = $4
WHERE id = $1
`

type UpdateBranchProtectionReviewSettingsParams struct {
	ID                        int64
	RequiredReviewCount       int32
	DismissStaleReviewsOnPush bool
	RequireCodeOwnerReview    bool
}

// S23 surface for the review-related knobs. Branch-protection edit
// handler calls this alongside UpdateBranchProtectionRule.
func (q *Queries) UpdateBranchProtectionReviewSettings(ctx context.Context, db DBTX, arg UpdateBranchProtectionReviewSettingsParams) error {
	_, err := db.Exec(ctx, updateBranchProtectionReviewSettings,
		arg.ID,
		arg.RequiredReviewCount,
		arg.DismissStaleReviewsOnPush,
		arg.RequireCodeOwnerReview,
	)
	return err
}

const updateBranchProtectionRule = `-- name: UpdateBranchProtectionRule :exec
UPDATE branch_protection_rules
SET pattern = $2,
    prevent_force_push = $3,
    prevent_deletion = $4,
    require_pr_for_push = $5,
    allowed_pusher_user_ids = $6
WHERE id = $1
`

type UpdateBranchProtectionRuleParams struct {
	ID                   int64
	Pattern              string
	PreventForcePush     bool
	PreventDeletion      bool
	RequirePrForPush     bool
	AllowedPusherUserIds []int64
}

func (q *Queries) UpdateBranchProtectionRule(ctx context.Context, db DBTX, arg UpdateBranchProtectionRuleParams) error {
	_, err := db.Exec(ctx, updateBranchProtectionRule,
		arg.ID,
		arg.Pattern,
		arg.PreventForcePush,
		arg.PreventDeletion,
		arg.RequirePrForPush,
		arg.AllowedPusherUserIds,
	)
	return err
}

const updateRepoDefaultBranch = `-- name: UpdateRepoDefaultBranch :exec
UPDATE repos SET default_branch = $2, updated_at = now() WHERE id = $1
`

type UpdateRepoDefaultBranchParams struct {
	ID            int64
	DefaultBranch string
}

// Used by the default-branch settings handler. The on-disk HEAD update
// is a separate step done via `git symbolic-ref` from the orchestrator.
func (q *Queries) UpdateRepoDefaultBranch(ctx context.Context, db DBTX, arg UpdateRepoDefaultBranchParams) error {
	_, err := db.Exec(ctx, updateRepoDefaultBranch, arg.ID, arg.DefaultBranch)
	return err
}

const upsertBranchProtectionRule = `-- name: UpsertBranchProtectionRule :one
INSERT INTO branch_protection_rules (
    repo_id, pattern,
    prevent_force_push, prevent_deletion, require_pr_for_push,
    allowed_pusher_user_ids, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7::bigint
)
RETURNING id
`

type UpsertBranchProtectionRuleParams struct {
	RepoID               int64
	Pattern              string
	PreventForcePush     bool
	PreventDeletion      bool
	RequirePrForPush     bool
	AllowedPusherUserIds []int64
	CreatedByUserID      pgtype.Int8
}

func (q *Queries) UpsertBranchProtectionRule(ctx context.Context, db DBTX, arg UpsertBranchProtectionRuleParams) (int64, error) {
	row := db.QueryRow(ctx, upsertBranchProtectionRule,
		arg.RepoID,
		arg.Pattern,
		arg.PreventForcePush,
		arg.PreventDeletion,
		arg.RequirePrForPush,
		arg.AllowedPusherUserIds,
		arg.CreatedByUserID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
