// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: code_scanning.sql

package reposdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCodeSecurityCampaignAlert = `-- name: AddCodeSecurityCampaignAlert :exec
INSERT INTO code_security_campaign_alerts (campaign_id, alert_id)
SELECT $1, a.id
FROM code_scanning_alerts a
JOIN code_security_campaigns c ON c.id = $1
WHERE a.id = $2
  AND a.repo_id = c.repo_id
ON CONFLICT DO NOTHING
`

type AddCodeSecurityCampaignAlertParams struct {
	CampaignID int64
	ID         int64
}

func (q *Queries) AddCodeSecurityCampaignAlert(ctx context.Context, db DBTX, arg AddCodeSecurityCampaignAlertParams) error {
	_, err := db.Exec(ctx, addCodeSecurityCampaignAlert, arg.CampaignID, arg.ID)
	return err
}

const codeScanningSummaryForRepo = `-- name: CodeScanningSummaryForRepo :one
SELECT
    count(*) FILTER (WHERE status = 'open')::bigint AS open_alert_count,
    count(*) FILTER (WHERE status = 'dismissed')::bigint AS dismissed_alert_count,
    count(*) FILTER (WHERE status = 'fixed')::bigint AS fixed_alert_count,
    count(*) FILTER (WHERE status = 'open' AND severity = 'critical')::bigint AS critical_alert_count,
    count(*) FILTER (WHERE status = 'open' AND severity = 'high')::bigint AS high_alert_count,
    count(*)::bigint AS total_alert_count
FROM code_scanning_alerts
WHERE repo_id = $1
`

type CodeScanningSummaryForRepoRow struct {
	OpenAlertCount      int64
	DismissedAlertCount int64
	FixedAlertCount     int64
	CriticalAlertCount  int64
	HighAlertCount      int64
	TotalAlertCount     int64
}

func (q *Queries) CodeScanningSummaryForRepo(ctx context.Context, db DBTX, repoID int64) (CodeScanningSummaryForRepoRow, error) {
	row := db.QueryRow(ctx, codeScanningSummaryForRepo, repoID)
	var i CodeScanningSummaryForRepoRow
	err := row.Scan(
		&i.OpenAlertCount,
		&i.DismissedAlertCount,
		&i.FixedAlertCount,
		&i.CriticalAlertCount,
		&i.HighAlertCount,
		&i.TotalAlertCount,
	)
	return i, err
}

const createCodeScanningUpload = `-- name: CreateCodeScanningUpload :one

INSERT INTO code_scanning_uploads (
    repo_id, tool_name, tool_guid, category, commit_sha, ref_name,
    alert_count, raw_sarif_sha256, uploaded_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9::bigint
)
RETURNING id, repo_id, tool_name, tool_guid, category, commit_sha, ref_name, alert_count, raw_sarif_sha256, uploaded_by, uploaded_at
`

type CreateCodeScanningUploadParams struct {
	RepoID         int64
	ToolName       string
	ToolGuid       string
	Category       string
	CommitSha      string
	RefName        string
	AlertCount     int32
	RawSarifSha256 string
	UploadedBy     pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SP27 code scanning / SARIF upload queries.
func (q *Queries) CreateCodeScanningUpload(ctx context.Context, db DBTX, arg CreateCodeScanningUploadParams) (CodeScanningUpload, error) {
	row := db.QueryRow(ctx, createCodeScanningUpload,
		arg.RepoID,
		arg.ToolName,
		arg.ToolGuid,
		arg.Category,
		arg.CommitSha,
		arg.RefName,
		arg.AlertCount,
		arg.RawSarifSha256,
		arg.UploadedBy,
	)
	var i CodeScanningUpload
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ToolName,
		&i.ToolGuid,
		&i.Category,
		&i.CommitSha,
		&i.RefName,
		&i.AlertCount,
		&i.RawSarifSha256,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const createCodeSecurityCampaign = `-- name: CreateCodeSecurityCampaign :one
INSERT INTO code_security_campaigns (
    repo_id, title, description, created_by
) VALUES (
    $1, $2, $3, $4::bigint
)
RETURNING id, repo_id, title, description, state, created_by, closed_at, created_at, updated_at
`

type CreateCodeSecurityCampaignParams struct {
	RepoID      int64
	Title       string
	Description string
	CreatedBy   pgtype.Int8
}

func (q *Queries) CreateCodeSecurityCampaign(ctx context.Context, db DBTX, arg CreateCodeSecurityCampaignParams) (CodeSecurityCampaign, error) {
	row := db.QueryRow(ctx, createCodeSecurityCampaign,
		arg.RepoID,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
	)
	var i CodeSecurityCampaign
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Title,
		&i.Description,
		&i.State,
		&i.CreatedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dismissCodeScanningAlert = `-- name: DismissCodeScanningAlert :exec
UPDATE code_scanning_alerts
SET status = 'dismissed',
    dismissal_note = $3,
    dismissed_by = $4::bigint,
    dismissed_at = now(),
    fixed_at = NULL
WHERE id = $1
  AND repo_id = $2
`

type DismissCodeScanningAlertParams struct {
	ID            int64
	RepoID        int64
	DismissalNote string
	DismissedBy   pgtype.Int8
}

func (q *Queries) DismissCodeScanningAlert(ctx context.Context, db DBTX, arg DismissCodeScanningAlertParams) error {
	_, err := db.Exec(ctx, dismissCodeScanningAlert,
		arg.ID,
		arg.RepoID,
		arg.DismissalNote,
		arg.DismissedBy,
	)
	return err
}

const getCodeScanningAlert = `-- name: GetCodeScanningAlert :one
SELECT id, repo_id, tool_name, tool_guid, rule_id, rule_name, severity, message, path, start_line, end_line, start_column, end_column, fingerprint, commit_sha, ref_name, status, dismissal_note, dismissed_by, dismissed_at, fixed_at, first_seen_at, last_seen_at, updated_at
FROM code_scanning_alerts
WHERE id = $1 AND repo_id = $2
`

type GetCodeScanningAlertParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) GetCodeScanningAlert(ctx context.Context, db DBTX, arg GetCodeScanningAlertParams) (CodeScanningAlert, error) {
	row := db.QueryRow(ctx, getCodeScanningAlert, arg.ID, arg.RepoID)
	var i CodeScanningAlert
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ToolName,
		&i.ToolGuid,
		&i.RuleID,
		&i.RuleName,
		&i.Severity,
		&i.Message,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.StartColumn,
		&i.EndColumn,
		&i.Fingerprint,
		&i.CommitSha,
		&i.RefName,
		&i.Status,
		&i.DismissalNote,
		&i.DismissedBy,
		&i.DismissedAt,
		&i.FixedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCodeScanningAlertsForRepo = `-- name: ListCodeScanningAlertsForRepo :many
SELECT id, repo_id, tool_name, tool_guid, rule_id, rule_name, severity, message, path, start_line, end_line, start_column, end_column, fingerprint, commit_sha, ref_name, status, dismissal_note, dismissed_by, dismissed_at, fixed_at, first_seen_at, last_seen_at, updated_at
FROM code_scanning_alerts
WHERE repo_id = $1
  AND ($4::text = ''
       OR status = $4::text)
ORDER BY
    CASE severity
        WHEN 'critical' THEN 0
        WHEN 'high' THEN 1
        WHEN 'moderate' THEN 2
        ELSE 3
    END,
    last_seen_at DESC,
    lower(path),
    start_line,
    lower(rule_id)
LIMIT $2 OFFSET $3
`

type ListCodeScanningAlertsForRepoParams struct {
	RepoID       int64
	Limit        int32
	Offset       int32
	StatusFilter string
}

func (q *Queries) ListCodeScanningAlertsForRepo(ctx context.Context, db DBTX, arg ListCodeScanningAlertsForRepoParams) ([]CodeScanningAlert, error) {
	rows, err := db.Query(ctx, listCodeScanningAlertsForRepo,
		arg.RepoID,
		arg.Limit,
		arg.Offset,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeScanningAlert{}
	for rows.Next() {
		var i CodeScanningAlert
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.ToolName,
			&i.ToolGuid,
			&i.RuleID,
			&i.RuleName,
			&i.Severity,
			&i.Message,
			&i.Path,
			&i.StartLine,
			&i.EndLine,
			&i.StartColumn,
			&i.EndColumn,
			&i.Fingerprint,
			&i.CommitSha,
			&i.RefName,
			&i.Status,
			&i.DismissalNote,
			&i.DismissedBy,
			&i.DismissedAt,
			&i.FixedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeSecurityCampaignsForRepo = `-- name: ListCodeSecurityCampaignsForRepo :many
SELECT
    c.id, c.repo_id, c.title, c.description, c.state, c.created_by, c.closed_at, c.created_at, c.updated_at,
    COALESCE(alert_counts.alert_count, 0)::bigint AS alert_count,
    COALESCE(alert_counts.open_alert_count, 0)::bigint AS open_alert_count
FROM code_security_campaigns c
LEFT JOIN LATERAL (
    SELECT
        count(*) AS alert_count,
        count(*) FILTER (WHERE a.status = 'open') AS open_alert_count
    FROM code_security_campaign_alerts ca
    JOIN code_scanning_alerts a ON a.id = ca.alert_id
    WHERE ca.campaign_id = c.id
) alert_counts ON true
WHERE c.repo_id = $1
ORDER BY
    CASE c.state WHEN 'open' THEN 0 ELSE 1 END,
    c.updated_at DESC
`

type ListCodeSecurityCampaignsForRepoRow struct {
	ID             int64
	RepoID         int64
	Title          string
	Description    string
	State          string
	CreatedBy      pgtype.Int8
	ClosedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AlertCount     int64
	OpenAlertCount int64
}

func (q *Queries) ListCodeSecurityCampaignsForRepo(ctx context.Context, db DBTX, repoID int64) ([]ListCodeSecurityCampaignsForRepoRow, error) {
	rows, err := db.Query(ctx, listCodeSecurityCampaignsForRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodeSecurityCampaignsForRepoRow{}
	for rows.Next() {
		var i ListCodeSecurityCampaignsForRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Title,
			&i.Description,
			&i.State,
			&i.CreatedBy,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AlertCount,
			&i.OpenAlertCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgCodeScanningAlerts = `-- name: ListOrgCodeScanningAlerts :many
SELECT
    a.id,
    a.repo_id,
    r.name AS repo_name,
    r.visibility AS repo_visibility,
    a.tool_name,
    a.rule_id,
    a.rule_name,
    a.severity,
    a.message,
    a.path,
    a.start_line,
    a.fingerprint,
    a.commit_sha,
    a.ref_name,
    a.first_seen_at,
    a.last_seen_at
FROM code_scanning_alerts a
JOIN repos r ON r.id = a.repo_id
WHERE r.owner_org_id = $1
  AND r.deleted_at IS NULL
  AND a.status = 'open'
ORDER BY
    CASE a.severity
        WHEN 'critical' THEN 0
        WHEN 'high' THEN 1
        WHEN 'moderate' THEN 2
        ELSE 3
    END,
    a.last_seen_at DESC,
    lower(r.name),
    lower(a.path),
    a.start_line
LIMIT $2 OFFSET $3
`

type ListOrgCodeScanningAlertsParams struct {
	OwnerOrgID pgtype.Int8
	Limit      int32
	Offset     int32
}

type ListOrgCodeScanningAlertsRow struct {
	ID             int64
	RepoID         int64
	RepoName       string
	RepoVisibility RepoVisibility
	ToolName       string
	RuleID         string
	RuleName       string
	Severity       string
	Message        string
	Path           string
	StartLine      int32
	Fingerprint    string
	CommitSha      string
	RefName        string
	FirstSeenAt    pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
}

func (q *Queries) ListOrgCodeScanningAlerts(ctx context.Context, db DBTX, arg ListOrgCodeScanningAlertsParams) ([]ListOrgCodeScanningAlertsRow, error) {
	rows, err := db.Query(ctx, listOrgCodeScanningAlerts, arg.OwnerOrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgCodeScanningAlertsRow{}
	for rows.Next() {
		var i ListOrgCodeScanningAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RepoName,
			&i.RepoVisibility,
			&i.ToolName,
			&i.RuleID,
			&i.RuleName,
			&i.Severity,
			&i.Message,
			&i.Path,
			&i.StartLine,
			&i.Fingerprint,
			&i.CommitSha,
			&i.RefName,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgCodeScanningSummary = `-- name: OrgCodeScanningSummary :one
WITH org_repos AS (
    SELECT id
    FROM repos
    WHERE owner_org_id = $1
      AND deleted_at IS NULL
),
open_alerts AS (
    SELECT a.id, a.repo_id, a.tool_name, a.tool_guid, a.rule_id, a.rule_name, a.severity, a.message, a.path, a.start_line, a.end_line, a.start_column, a.end_column, a.fingerprint, a.commit_sha, a.ref_name, a.status, a.dismissal_note, a.dismissed_by, a.dismissed_at, a.fixed_at, a.first_seen_at, a.last_seen_at, a.updated_at
    FROM code_scanning_alerts a
    JOIN org_repos r ON r.id = a.repo_id
    WHERE a.status = 'open'
)
SELECT
    count(*)::bigint AS open_code_alert_count,
    count(*) FILTER (WHERE severity = 'critical')::bigint AS critical_code_alert_count,
    count(*) FILTER (WHERE severity = 'high')::bigint AS high_code_alert_count,
    count(DISTINCT repo_id)::bigint AS affected_repo_count
FROM open_alerts
`

type OrgCodeScanningSummaryRow struct {
	OpenCodeAlertCount     int64
	CriticalCodeAlertCount int64
	HighCodeAlertCount     int64
	AffectedRepoCount      int64
}

func (q *Queries) OrgCodeScanningSummary(ctx context.Context, db DBTX, ownerOrgID pgtype.Int8) (OrgCodeScanningSummaryRow, error) {
	row := db.QueryRow(ctx, orgCodeScanningSummary, ownerOrgID)
	var i OrgCodeScanningSummaryRow
	err := row.Scan(
		&i.OpenCodeAlertCount,
		&i.CriticalCodeAlertCount,
		&i.HighCodeAlertCount,
		&i.AffectedRepoCount,
	)
	return i, err
}

const reopenCodeScanningAlert = `-- name: ReopenCodeScanningAlert :exec
UPDATE code_scanning_alerts
SET status = 'open',
    dismissal_note = '',
    dismissed_by = NULL,
    dismissed_at = NULL,
    fixed_at = NULL
WHERE id = $1
  AND repo_id = $2
`

type ReopenCodeScanningAlertParams struct {
	ID     int64
	RepoID int64
}

func (q *Queries) ReopenCodeScanningAlert(ctx context.Context, db DBTX, arg ReopenCodeScanningAlertParams) error {
	_, err := db.Exec(ctx, reopenCodeScanningAlert, arg.ID, arg.RepoID)
	return err
}

const upsertCodeScanningAlert = `-- name: UpsertCodeScanningAlert :one
INSERT INTO code_scanning_alerts (
    repo_id, tool_name, tool_guid, rule_id, rule_name, severity,
    message, path, start_line, end_line, start_column, end_column,
    fingerprint, commit_sha, ref_name
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15
)
ON CONFLICT (repo_id, tool_name, rule_id, path, start_line, fingerprint) DO UPDATE
SET tool_guid = EXCLUDED.tool_guid,
    rule_name = EXCLUDED.rule_name,
    severity = EXCLUDED.severity,
    message = EXCLUDED.message,
    end_line = EXCLUDED.end_line,
    start_column = EXCLUDED.start_column,
    end_column = EXCLUDED.end_column,
    commit_sha = EXCLUDED.commit_sha,
    ref_name = EXCLUDED.ref_name,
    status = CASE
        WHEN code_scanning_alerts.status = 'dismissed' THEN code_scanning_alerts.status
        ELSE 'open'
    END,
    fixed_at = CASE
        WHEN code_scanning_alerts.status = 'dismissed' THEN code_scanning_alerts.fixed_at
        ELSE NULL
    END,
    last_seen_at = now()
RETURNING id, repo_id, tool_name, tool_guid, rule_id, rule_name, severity, message, path, start_line, end_line, start_column, end_column, fingerprint, commit_sha, ref_name, status, dismissal_note, dismissed_by, dismissed_at, fixed_at, first_seen_at, last_seen_at, updated_at
`

type UpsertCodeScanningAlertParams struct {
	RepoID      int64
	ToolName    string
	ToolGuid    string
	RuleID      string
	RuleName    string
	Severity    string
	Message     string
	Path        string
	StartLine   int32
	EndLine     int32
	StartColumn int32
	EndColumn   int32
	Fingerprint string
	CommitSha   string
	RefName     string
}

func (q *Queries) UpsertCodeScanningAlert(ctx context.Context, db DBTX, arg UpsertCodeScanningAlertParams) (CodeScanningAlert, error) {
	row := db.QueryRow(ctx, upsertCodeScanningAlert,
		arg.RepoID,
		arg.ToolName,
		arg.ToolGuid,
		arg.RuleID,
		arg.RuleName,
		arg.Severity,
		arg.Message,
		arg.Path,
		arg.StartLine,
		arg.EndLine,
		arg.StartColumn,
		arg.EndColumn,
		arg.Fingerprint,
		arg.CommitSha,
		arg.RefName,
	)
	var i CodeScanningAlert
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.ToolName,
		&i.ToolGuid,
		&i.RuleID,
		&i.RuleName,
		&i.Severity,
		&i.Message,
		&i.Path,
		&i.StartLine,
		&i.EndLine,
		&i.StartColumn,
		&i.EndColumn,
		&i.Fingerprint,
		&i.CommitSha,
		&i.RefName,
		&i.Status,
		&i.DismissalNote,
		&i.DismissedBy,
		&i.DismissedAt,
		&i.FixedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}
