// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reposdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptTransferRequest(ctx context.Context, db DBTX, id int64) error
	AddIssueToRepoProject(ctx context.Context, db DBTX, arg AddIssueToRepoProjectParams) (RepoProjectItem, error)
	// Bypasses the soft-delete grace window (admin only — S34): set
	// deleted_at to a year ago so the next lifecycle sweep hard-deletes
	// without waiting. Replaces the inline UPDATE in admin/repos.go
	// (SR2 M2).
	AdminForceDeleteRepo(ctx context.Context, db DBTX, id int64) error
	ArchiveRepo(ctx context.Context, db DBTX, id int64) error
	CancelTransferRequest(ctx context.Context, db DBTX, id int64) error
	CountForksOfRepo(ctx context.Context, db DBTX, forkOfRepoID pgtype.Int8) (int64, error)
	CountPublicReposForOwnerOrg(ctx context.Context, db DBTX, ownerOrgID pgtype.Int8) (int64, error)
	CountPublicReposForOwnerUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) (int64, error)
	// ─── rename rate limit support ─────────────────────────────────────────
	// Used to enforce the 5-per-30-days rename rate limit. The redirect
	// row is the audit trail for renames; counting them per repo gives a
	// reliable cap.
	CountRecentRedirectsForRepo(ctx context.Context, db DBTX, repoID int64) (int32, error)
	CountRepoWikiPages(ctx context.Context, db DBTX, repoID int64) (int64, error)
	CountReposForOwnerOrg(ctx context.Context, db DBTX, ownerOrgID pgtype.Int8) (int64, error)
	CountReposForOwnerUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) (int64, error)
	// ─── S27 forks ─────────────────────────────────────────────────────
	// Insert a fork shell. Distinct from CreateRepo because forks set
	// `fork_of_repo_id` (which fires the fork_count trigger) and start
	// at init_status='init_pending' so the worker job can flip them to
	// 'initialized' once `git clone --bare --shared` finishes.
	CreateForkRepo(ctx context.Context, db DBTX, arg CreateForkRepoParams) (Repo, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	CreateRepo(ctx context.Context, db DBTX, arg CreateRepoParams) (Repo, error)
	// PRO-EXT01-06pre-b: insert a template-init shell. Mirrors
	// CreateForkRepo's `init_status='init_pending'` semantics so the
	// worker can flip to 'initialized' once the clone finishes, but
	// WITHOUT setting fork_of_repo_id — the new repo is independent
	// of the template (no alternates, no fork-count bump).
	CreateRepoFromTemplate(ctx context.Context, db DBTX, arg CreateRepoFromTemplateParams) (Repo, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// ─── repo projects ─────────────────────────────────────────────────
	CreateRepoProject(ctx context.Context, db DBTX, arg CreateRepoProjectParams) (RepoProject, error)
	// ─── repo wiki pages ───────────────────────────────────────────────
	CreateRepoWikiPage(ctx context.Context, db DBTX, arg CreateRepoWikiPageParams) (RepoWikiPage, error)
	DeclineTransferRequest(ctx context.Context, db DBTX, id int64) error
	DeleteBranchProtectionRule(ctx context.Context, db DBTX, id int64) error
	// Used by tests to reset cache state between cases. Not called from
	// production code paths.
	DeleteCommitVerification(ctx context.Context, db DBTX, arg DeleteCommitVerificationParams) error
	DeleteProfilePinsForSet(ctx context.Context, db DBTX, setID int64) error
	// Used by the rename compensator: drop a single redirect row when
	// the rename has to be rolled back due to a filesystem failure. We
	// avoided raw SQL here at the audit's request (S00-S25, M).
	DeleteRedirectByUserOwnerOldName(ctx context.Context, db DBTX, arg DeleteRedirectByUserOwnerOldNameParams) error
	// Used by hard-delete: drop the redirect rows pointing at this repo
	// (they would dangle once the repos row is gone; the FK ON DELETE
	// CASCADE would handle it, but explicit is auditable).
	DeleteRedirectsForRepo(ctx context.Context, db DBTX, repoID int64) error
	DeleteRepoInsightSnapshot(ctx context.Context, db DBTX, repoID int64) error
	DeleteRepoProject(ctx context.Context, db DBTX, arg DeleteRepoProjectParams) error
	DeleteRepoSourceRemote(ctx context.Context, db DBTX, repoID int64) error
	DeleteRepoWikiPage(ctx context.Context, db DBTX, arg DeleteRepoWikiPageParams) error
	ExistsRepoForOwnerOrg(ctx context.Context, db DBTX, arg ExistsRepoForOwnerOrgParams) (bool, error)
	ExistsRepoForOwnerUser(ctx context.Context, db DBTX, arg ExistsRepoForOwnerUserParams) (bool, error)
	// Called by the periodic worker (transfers:expire) — flips pending
	// offers past their expires_at to the expired terminal state.
	ExpirePendingTransfers(ctx context.Context, db DBTX) (int64, error)
	GetBranchProtectionRule(ctx context.Context, db DBTX, id int64) (BranchProtectionRule, error)
	// Single-commit read. Used by the single-commit page renderer and the
	// REST commits/{sha} response. Returns no row when the commit hasn't
	// been verified yet; caller treats that as "compute on demand".
	GetCommitVerification(ctx context.Context, db DBTX, arg GetCommitVerificationParams) (CommitVerificationCache, error)
	// Batch read for the commit-list page. Takes an array of OIDs and
	// returns existing rows; missing OIDs are absent from the result and
	// the renderer treats them as "not yet verified".
	GetCommitVerificationsForOIDs(ctx context.Context, db DBTX, arg GetCommitVerificationsForOIDsParams) ([]CommitVerificationCache, error)
	GetProfilePinSetForOrg(ctx context.Context, db DBTX, ownerOrgID pgtype.Int8) (int64, error)
	// ─── profile/org pinned repositories ───────────────────────────────
	GetProfilePinSetForUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) (int64, error)
	GetRepoByID(ctx context.Context, db DBTX, id int64) (Repo, error)
	// S30: org-owner mirror of GetRepoByOwnerUserAndName. The (owner_org_id,
	// name) partial unique index from 0017 backs this lookup with the same
	// O(1) cost the user-side path enjoys.
	GetRepoByOwnerOrgAndName(ctx context.Context, db DBTX, arg GetRepoByOwnerOrgAndNameParams) (Repo, error)
	GetRepoByOwnerUserAndName(ctx context.Context, db DBTX, arg GetRepoByOwnerUserAndNameParams) (Repo, error)
	// Lookup the per-repo backfill metadata. Mirrors the row shape of
	// ListAllActiveReposWithOwner so the per-repo job handler can run
	// the same code path the bulk handler uses.
	GetRepoForBackfill(ctx context.Context, db DBTX, id int64) (GetRepoForBackfillRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	GetRepoInsightSnapshot(ctx context.Context, db DBTX, repoID int64) (RepoInsightSnapshot, error)
	// Returns the owner slug for a repo. Used by size-recalc, indexing, and
	// other jobs that need the bare-repo on-disk path. Org-owned repos use the
	// org slug in the same path position as user-owned repos.
	GetRepoOwnerUsernameByID(ctx context.Context, db DBTX, id int64) (GetRepoOwnerUsernameByIDRow, error)
	GetRepoProject(ctx context.Context, db DBTX, arg GetRepoProjectParams) (RepoProject, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	GetRepoSourceRemote(ctx context.Context, db DBTX, repoID int64) (RepoSourceRemote, error)
	GetRepoWikiPageBySlug(ctx context.Context, db DBTX, arg GetRepoWikiPageBySlugParams) (RepoWikiPage, error)
	GetSoftDeletedRepoByOwnerOrgAndName(ctx context.Context, db DBTX, arg GetSoftDeletedRepoByOwnerOrgAndNameParams) (Repo, error)
	GetSoftDeletedRepoByOwnerUserAndName(ctx context.Context, db DBTX, arg GetSoftDeletedRepoByOwnerUserAndNameParams) (Repo, error)
	GetTransferRequest(ctx context.Context, db DBTX, id int64) (RepoTransferRequest, error)
	HardDeleteRepo(ctx context.Context, db DBTX, id int64) error
	InsertProfilePin(ctx context.Context, db DBTX, arg InsertProfilePinParams) error
	// ─── redirects ─────────────────────────────────────────────────────────
	// Both old-owner FKs are nullable; pass exactly one. The CHECK
	// constraint on the table enforces the xor shape.
	InsertRepoRedirect(ctx context.Context, db DBTX, arg InsertRepoRedirectParams) error
	InsertRepoTopic(ctx context.Context, db DBTX, arg InsertRepoTopicParams) error
	// ─── transfer requests ─────────────────────────────────────────────────
	InsertTransferRequest(ctx context.Context, db DBTX, arg InsertTransferRequestParams) (RepoTransferRequest, error)
	// Stamps invalidated_at on every cache row whose signer_subkey_id
	// matches. Called from the GPG-key soft-delete path in the same tx as
	// SoftDeleteSubkeysForGPGKey so the cache and the keyring stay in
	// sync. The next read of an invalidated row triggers a re-verify.
	InvalidateVerificationsForSubkey(ctx context.Context, db DBTX, signerSubkeyID pgtype.Int8) error
	ListActiveReposForOwnerUserByName(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) ([]Repo, error)
	// Used by the GPG verification backfill (S51) to enumerate every
	// active repo system-wide. Unlike ListAllRepoFullNames this query
	// handles BOTH user-owned and org-owned repos via a COALESCE between
	// users.username and orgs.slug; the owner string is whatever
	// RepoFS.RepoPath expects.
	ListAllActiveReposWithOwner(ctx context.Context, db DBTX) ([]ListAllActiveReposWithOwnerRow, error)
	// Used by `shithubd hooks reinstall --all` to enumerate every active
	// bare repo on disk and re-link its hooks.
	ListAllRepoFullNames(ctx context.Context, db DBTX) ([]ListAllRepoFullNamesRow, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	ListBranchProtectionRules(ctx context.Context, db DBTX, repoID int64) ([]BranchProtectionRule, error)
	// Forks of a given source repo, paginated, recency-sorted. Joined
	// with users for the owner display name. Excludes soft-deleted.
	ListForksOfRepo(ctx context.Context, db DBTX, arg ListForksOfRepoParams) ([]ListForksOfRepoRow, error)
	// Used by S16's hard-delete cascade (S27 amendment): before deleting
	// a source repo, every fork must `git repack -a -d --no-shared` so
	// it has its own copy of the objects. Returns just enough to locate
	// the bare repo on disk.
	ListForksOfRepoForRepack(ctx context.Context, db DBTX, forkOfRepoID pgtype.Int8) ([]ListForksOfRepoForRepackRow, error)
	// Inbox view: pending offers a user can act on.
	ListPendingTransfersForUser(ctx context.Context, db DBTX, toPrincipalID int64) ([]RepoTransferRequest, error)
	ListProfilePinCandidateReposForUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) ([]ListProfilePinCandidateReposForUserRow, error)
	ListProfilePinsForSet(ctx context.Context, db DBTX, setID int64) ([]ListProfilePinsForSetRow, error)
	ListPublicContributionRepos(ctx context.Context, db DBTX, limit int32) ([]ListPublicContributionReposRow, error)
	// Public-only org repo listing for non-member callers (and the no-auth
	// public-discovery REST view).
	ListPublicReposForOwnerOrg(ctx context.Context, db DBTX, arg ListPublicReposForOwnerOrgParams) ([]Repo, error)
	// Public-only view of a user's repos for the "list another user's repos"
	// REST endpoint. Hidden behind the same updated_at ordering.
	ListPublicReposForOwnerUser(ctx context.Context, db DBTX, arg ListPublicReposForOwnerUserParams) ([]Repo, error)
	// ─── soft-delete sweep query ───────────────────────────────────────────
	// The repo:hard_delete enqueuer queries this to find rows ready for
	// destruction. The 7-day grace is hard-coded here; if we add a config
	// knob later, change this to a parameter.
	ListRepoIDsPastSoftDeleteGrace(ctx context.Context, db DBTX) ([]int64, error)
	ListRepoProjectItems(ctx context.Context, db DBTX, projectID int64) ([]ListRepoProjectItemsRow, error)
	ListRepoProjects(ctx context.Context, db DBTX, repoID int64) ([]RepoProject, error)
	ListRepoProjectsForIssue(ctx context.Context, db DBTX, issueID int64) ([]RepoProject, error)
	// ─── repo_topics (S32) ─────────────────────────────────────────────
	ListRepoTopics(ctx context.Context, db DBTX, repoID int64) ([]string, error)
	ListRepoWikiPages(ctx context.Context, db DBTX, repoID int64) ([]RepoWikiPage, error)
	ListReposForOwnerOrg(ctx context.Context, db DBTX, ownerOrgID pgtype.Int8) ([]Repo, error)
	// Paginated mirror of ListReposForOwnerOrg for the REST list endpoint
	// when the viewer is an org member and may see private repos.
	ListReposForOwnerOrgPaged(ctx context.Context, db DBTX, arg ListReposForOwnerOrgPagedParams) ([]Repo, error)
	ListReposForOwnerUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) ([]Repo, error)
	// Paginated mirror of ListReposForOwnerUser. Used by the REST surface
	// where the caller is the owner (or a site admin) and is allowed to see
	// private repos. Order matches the un-paginated form so callers can
	// swap between them without observing a reshuffle.
	ListReposForOwnerUserPaged(ctx context.Context, db DBTX, arg ListReposForOwnerUserPagedParams) ([]Repo, error)
	// S28 code-search reconciler: returns repos whose default_branch_oid
	// has advanced past last_indexed_oid (or last_indexed_oid is NULL
	// and a default exists). Limited so a single tick of the cron
	// doesn't try to re-index the whole world.
	ListReposNeedingReindex(ctx context.Context, db DBTX, limit int32) ([]ListReposNeedingReindexRow, error)
	// /settings/repositories/restore page lists these.
	ListSoftDeletedReposForOwner(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) ([]ListSoftDeletedReposForOwnerRow, error)
	// Sender / repo-settings view.
	ListTransfersForRepo(ctx context.Context, db DBTX, repoID int64) ([]RepoTransferRequest, error)
	// Serializes DB + filesystem operations for one logical owner/name
	// pair. Create, soft-delete, restore, and hard-delete all touch the
	// canonical bare path; a transaction-scoped advisory lock keeps those
	// cross-resource moves from racing.
	LockRepoOwnerName(ctx context.Context, db DBTX, hashtextextended string) error
	// Returns the current repo_id when (old_owner_user_id, old_name) hits
	// a redirect row.
	LookupRedirectByUserOwner(ctx context.Context, db DBTX, arg LookupRedirectByUserOwnerParams) (int64, error)
	MarkRepoSourceRemoteFetchError(ctx context.Context, db DBTX, arg MarkRepoSourceRemoteFetchErrorParams) error
	MarkRepoSourceRemoteFetched(ctx context.Context, db DBTX, repoID int64) error
	// ─── fork-anchor cleanup on hard delete ────────────────────────────────
	// Children pointing at this repo lose their fork-of pointer. Mirrors
	// GitHub's behavior when an upstream is deleted.
	OrphanForksOf(ctx context.Context, db DBTX, forkOfRepoID pgtype.Int8) (int64, error)
	// PRO-EXT01-15. Owner-initiated pause. The (is_archived, is_paused)
	// mutex is enforced by the repos_pause_archive_mutex check; the
	// handler guarantees we don't pause an already-archived repo, but
	// the constraint defends in depth.
	PauseRepo(ctx context.Context, db DBTX, arg PauseRepoParams) error
	RemoveIssueFromRepoProject(ctx context.Context, db DBTX, arg RemoveIssueFromRepoProjectParams) error
	// SPDX-License-Identifier: AGPL-3.0-or-later
	//
	// S16 lifecycle queries. Kept in a separate file from repos.sql so the
	// mainline CRUD stays easy to read.
	// ─── repo mutations ────────────────────────────────────────────────────
	// Same-owner rename. The handler validates the new name shape and the
	// redirect row is INSERTed in the same tx.
	RenameRepo(ctx context.Context, db DBTX, arg RenameRepoParams) error
	// Atomic full-replace: callers compose the new topic set in Go,
	// then replace the existing rows in one tx (DELETE + INSERT). The
	// caller's tx wraps both calls for atomicity.
	ReplaceRepoTopics(ctx context.Context, db DBTX, repoID int64) error
	RestoreRepo(ctx context.Context, db DBTX, id int64) error
	// S28 code-search: the worker writes the OID it finished indexing
	// so the reconciler can detect drift (default_branch_oid moved but
	// last_indexed_oid lagged).
	SetLastIndexedOID(ctx context.Context, db DBTX, arg SetLastIndexedOIDParams) error
	// Promotes a fork from init_pending to initialized (or init_failed).
	// The DB row is created up-front so the URL resolves immediately and
	// the user sees a "preparing your fork" placeholder while the worker
	// runs `git clone --bare --shared`.
	SetRepoInitStatus(ctx context.Context, db DBTX, arg SetRepoInitStatusParams) error
	SetRepoProjectState(ctx context.Context, db DBTX, arg SetRepoProjectStateParams) (RepoProject, error)
	SetRepoVisibility(ctx context.Context, db DBTX, arg SetRepoVisibilityParams) error
	SoftDeleteRepo(ctx context.Context, db DBTX, id int64) error
	// Distinct name from S11's SoftDeleteRepo so future code that wants to
	// preserve the lifecycle audit-emission shape can find this one.
	SoftDeleteRepoLifecycle(ctx context.Context, db DBTX, id int64) error
	// Sets owner_user_id (or owner_org_id post-S31) on accept. The xor
	// check on the table enforces the shape. Also clears the other side
	// so a user→org transfer flips both columns atomically.
	TransferRepoOwner(ctx context.Context, db DBTX, arg TransferRepoOwnerParams) error
	UnarchiveRepo(ctx context.Context, db DBTX, id int64) error
	UnpauseRepo(ctx context.Context, db DBTX, id int64) error
	// S24 surface for the required-status-check knobs. Branch-protection
	// edit handler calls this alongside UpdateBranchProtectionRule.
	UpdateBranchProtectionCheckSettings(ctx context.Context, db DBTX, arg UpdateBranchProtectionCheckSettingsParams) error
	// S23 surface for the review-related knobs. Branch-protection edit
	// handler calls this alongside UpdateBranchProtectionRule.
	UpdateBranchProtectionReviewSettings(ctx context.Context, db DBTX, arg UpdateBranchProtectionReviewSettingsParams) error
	UpdateBranchProtectionRule(ctx context.Context, db DBTX, arg UpdateBranchProtectionRuleParams) error
	// Used by the default-branch settings handler. The on-disk HEAD update
	// is a separate step done via `git symbolic-ref` from the orchestrator.
	UpdateRepoDefaultBranch(ctx context.Context, db DBTX, arg UpdateRepoDefaultBranchParams) error
	// Set when push:process detects a commit on the repo's default branch.
	// Pass NULL to clear (e.g. when the branch is force-deleted in a future
	// sprint). The repo home view reads this to decide between empty and
	// populated layouts.
	UpdateRepoDefaultBranchOID(ctx context.Context, db DBTX, arg UpdateRepoDefaultBranchOIDParams) error
	UpdateRepoDiskUsed(ctx context.Context, db DBTX, arg UpdateRepoDiskUsedParams) error
	// S32: General-tab settings persist via this single query so each
	// form post is one round-trip. The merge-method toggles are kept
	// separate from the repo create flow because they're admin-only.
	//
	// PRO-EXT01-06pre: is_template added; the column is unconstrained at
	// the DB level so PRO-EXT01-06 can layer a handler-side gate that
	// restricts private templates to Pro users without a migration.
	UpdateRepoGeneralSettings(ctx context.Context, db DBTX, arg UpdateRepoGeneralSettingsParams) error
	UpdateRepoMergeSettings(ctx context.Context, db DBTX, arg UpdateRepoMergeSettingsParams) error
	UpdateRepoProject(ctx context.Context, db DBTX, arg UpdateRepoProjectParams) (RepoProject, error)
	UpdateRepoWikiPage(ctx context.Context, db DBTX, arg UpdateRepoWikiPageParams) (RepoWikiPage, error)
	UpsertBranchProtectionRule(ctx context.Context, db DBTX, arg UpsertBranchProtectionRuleParams) (int64, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// Idempotent upsert. The verification orchestrator + backfill worker
	// both write through this query; both can safely run concurrently
	// against the same (repo_id, commit_oid) without losing data thanks
	// to the (repo_id, commit_oid) primary key + ON CONFLICT clause.
	UpsertCommitVerification(ctx context.Context, db DBTX, arg UpsertCommitVerificationParams) error
	UpsertProfilePinSetForOrg(ctx context.Context, db DBTX, ownerOrgID pgtype.Int8) (int64, error)
	UpsertProfilePinSetForUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) (int64, error)
	UpsertRepoInsightSnapshot(ctx context.Context, db DBTX, arg UpsertRepoInsightSnapshotParams) (RepoInsightSnapshot, error)
	UpsertRepoSourceRemote(ctx context.Context, db DBTX, arg UpsertRepoSourceRemoteParams) (RepoSourceRemote, error)
}

var _ Querier = (*Queries)(nil)
