// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package reposdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReposForOwnerUser = `-- name: CountReposForOwnerUser :one
SELECT count(*) FROM repos
WHERE owner_user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountReposForOwnerUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) (int64, error) {
	row := db.QueryRow(ctx, countReposForOwnerUser, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepo = `-- name: CreateRepo :one

INSERT INTO repos (
    owner_user_id, owner_org_id, name, description, visibility,
    default_branch, license_key, primary_language
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, owner_user_id, owner_org_id, name, description, visibility,
          default_branch, is_archived, archived_at, deleted_at,
          disk_used_bytes, fork_of_repo_id, license_key, primary_language,
          has_issues, has_pulls, created_at, updated_at
`

type CreateRepoParams struct {
	OwnerUserID     pgtype.Int8
	OwnerOrgID      pgtype.Int8
	Name            string
	Description     string
	Visibility      RepoVisibility
	DefaultBranch   string
	LicenseKey      pgtype.Text
	PrimaryLanguage pgtype.Text
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) CreateRepo(ctx context.Context, db DBTX, arg CreateRepoParams) (Repo, error) {
	row := db.QueryRow(ctx, createRepo,
		arg.OwnerUserID,
		arg.OwnerOrgID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.DefaultBranch,
		arg.LicenseKey,
		arg.PrimaryLanguage,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DiskUsedBytes,
		&i.ForkOfRepoID,
		&i.LicenseKey,
		&i.PrimaryLanguage,
		&i.HasIssues,
		&i.HasPulls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsRepoForOwnerUser = `-- name: ExistsRepoForOwnerUser :one
SELECT EXISTS(
    SELECT 1 FROM repos
    WHERE owner_user_id = $1 AND name = $2 AND deleted_at IS NULL
)
`

type ExistsRepoForOwnerUserParams struct {
	OwnerUserID pgtype.Int8
	Name        string
}

func (q *Queries) ExistsRepoForOwnerUser(ctx context.Context, db DBTX, arg ExistsRepoForOwnerUserParams) (bool, error) {
	row := db.QueryRow(ctx, existsRepoForOwnerUser, arg.OwnerUserID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRepoByOwnerUserAndName = `-- name: GetRepoByOwnerUserAndName :one
SELECT id, owner_user_id, owner_org_id, name, description, visibility,
       default_branch, is_archived, archived_at, deleted_at,
       disk_used_bytes, fork_of_repo_id, license_key, primary_language,
       has_issues, has_pulls, created_at, updated_at
FROM repos
WHERE owner_user_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetRepoByOwnerUserAndNameParams struct {
	OwnerUserID pgtype.Int8
	Name        string
}

func (q *Queries) GetRepoByOwnerUserAndName(ctx context.Context, db DBTX, arg GetRepoByOwnerUserAndNameParams) (Repo, error) {
	row := db.QueryRow(ctx, getRepoByOwnerUserAndName, arg.OwnerUserID, arg.Name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.DefaultBranch,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DiskUsedBytes,
		&i.ForkOfRepoID,
		&i.LicenseKey,
		&i.PrimaryLanguage,
		&i.HasIssues,
		&i.HasPulls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReposForOwnerUser = `-- name: ListReposForOwnerUser :many
SELECT id, owner_user_id, owner_org_id, name, description, visibility,
       default_branch, is_archived, archived_at, deleted_at,
       disk_used_bytes, fork_of_repo_id, license_key, primary_language,
       has_issues, has_pulls, created_at, updated_at
FROM repos
WHERE owner_user_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListReposForOwnerUser(ctx context.Context, db DBTX, ownerUserID pgtype.Int8) ([]Repo, error) {
	rows, err := db.Query(ctx, listReposForOwnerUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.DefaultBranch,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.DiskUsedBytes,
			&i.ForkOfRepoID,
			&i.LicenseKey,
			&i.PrimaryLanguage,
			&i.HasIssues,
			&i.HasPulls,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRepo = `-- name: SoftDeleteRepo :exec
UPDATE repos SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteRepo(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, softDeleteRepo, id)
	return err
}

const updateRepoDiskUsed = `-- name: UpdateRepoDiskUsed :exec
UPDATE repos SET disk_used_bytes = $2 WHERE id = $1
`

type UpdateRepoDiskUsedParams struct {
	ID            int64
	DiskUsedBytes int64
}

func (q *Queries) UpdateRepoDiskUsed(ctx context.Context, db DBTX, arg UpdateRepoDiskUsedParams) error {
	_, err := db.Exec(ctx, updateRepoDiskUsed, arg.ID, arg.DiskUsedBytes)
	return err
}
