// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_artifact_attestations.sql

package reposdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoArtifactAttestationForRepo = `-- name: GetRepoArtifactAttestationForRepo :one
SELECT id, repo_id, subject_name, subject_digest, predicate_type, statement, byte_count, source_run_id, uploaded_by, created_at
FROM repo_artifact_attestations
WHERE repo_id = $1
  AND id = $2
`

type GetRepoArtifactAttestationForRepoParams struct {
	RepoID int64
	ID     int64
}

func (q *Queries) GetRepoArtifactAttestationForRepo(ctx context.Context, db DBTX, arg GetRepoArtifactAttestationForRepoParams) (RepoArtifactAttestation, error) {
	row := db.QueryRow(ctx, getRepoArtifactAttestationForRepo, arg.RepoID, arg.ID)
	var i RepoArtifactAttestation
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.SubjectName,
		&i.SubjectDigest,
		&i.PredicateType,
		&i.Statement,
		&i.ByteCount,
		&i.SourceRunID,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertRepoArtifactAttestation = `-- name: InsertRepoArtifactAttestation :one

INSERT INTO repo_artifact_attestations (
    repo_id,
    subject_name,
    subject_digest,
    predicate_type,
    statement,
    byte_count,
    source_run_id,
    uploaded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, repo_id, subject_name, subject_digest, predicate_type, statement, byte_count, source_run_id, uploaded_by, created_at
`

type InsertRepoArtifactAttestationParams struct {
	RepoID        int64
	SubjectName   string
	SubjectDigest string
	PredicateType string
	Statement     []byte
	ByteCount     int64
	SourceRunID   pgtype.Int8
	UploadedBy    pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SP29 persisted repository artifact attestations.
func (q *Queries) InsertRepoArtifactAttestation(ctx context.Context, db DBTX, arg InsertRepoArtifactAttestationParams) (RepoArtifactAttestation, error) {
	row := db.QueryRow(ctx, insertRepoArtifactAttestation,
		arg.RepoID,
		arg.SubjectName,
		arg.SubjectDigest,
		arg.PredicateType,
		arg.Statement,
		arg.ByteCount,
		arg.SourceRunID,
		arg.UploadedBy,
	)
	var i RepoArtifactAttestation
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.SubjectName,
		&i.SubjectDigest,
		&i.PredicateType,
		&i.Statement,
		&i.ByteCount,
		&i.SourceRunID,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRepoArtifactAttestations = `-- name: ListRepoArtifactAttestations :many
SELECT id, repo_id, subject_name, subject_digest, predicate_type, statement, byte_count, source_run_id, uploaded_by, created_at
FROM repo_artifact_attestations
WHERE repo_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
OFFSET $3
`

type ListRepoArtifactAttestationsParams struct {
	RepoID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListRepoArtifactAttestations(ctx context.Context, db DBTX, arg ListRepoArtifactAttestationsParams) ([]RepoArtifactAttestation, error) {
	rows, err := db.Query(ctx, listRepoArtifactAttestations, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoArtifactAttestation{}
	for rows.Next() {
		var i RepoArtifactAttestation
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.SubjectName,
			&i.SubjectDigest,
			&i.PredicateType,
			&i.Statement,
			&i.ByteCount,
			&i.SourceRunID,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
