// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_sbom_exports.sql

package reposdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoSBOMExport = `-- name: GetRepoSBOMExport :one
SELECT repo_id, format, source_head_sha, dependency_snapshot_generated_at, document, byte_count, generated_by, generated_at, updated_at
FROM repo_sbom_exports
WHERE repo_id = $1
  AND format = $2
`

type GetRepoSBOMExportParams struct {
	RepoID int64
	Format string
}

func (q *Queries) GetRepoSBOMExport(ctx context.Context, db DBTX, arg GetRepoSBOMExportParams) (RepoSbomExport, error) {
	row := db.QueryRow(ctx, getRepoSBOMExport, arg.RepoID, arg.Format)
	var i RepoSbomExport
	err := row.Scan(
		&i.RepoID,
		&i.Format,
		&i.SourceHeadSha,
		&i.DependencySnapshotGeneratedAt,
		&i.Document,
		&i.ByteCount,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepoSBOMExport = `-- name: UpsertRepoSBOMExport :one

INSERT INTO repo_sbom_exports (
    repo_id,
    format,
    source_head_sha,
    dependency_snapshot_generated_at,
    document,
    byte_count,
    generated_by,
    generated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now()
)
ON CONFLICT (repo_id, format) DO UPDATE
SET source_head_sha = EXCLUDED.source_head_sha,
    dependency_snapshot_generated_at = EXCLUDED.dependency_snapshot_generated_at,
    document = EXCLUDED.document,
    byte_count = EXCLUDED.byte_count,
    generated_by = EXCLUDED.generated_by,
    generated_at = now()
RETURNING repo_id, format, source_head_sha, dependency_snapshot_generated_at, document, byte_count, generated_by, generated_at, updated_at
`

type UpsertRepoSBOMExportParams struct {
	RepoID                        int64
	Format                        string
	SourceHeadSha                 string
	DependencySnapshotGeneratedAt pgtype.Timestamptz
	Document                      []byte
	ByteCount                     int64
	GeneratedBy                   pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SP29 persisted repository SBOM exports.
func (q *Queries) UpsertRepoSBOMExport(ctx context.Context, db DBTX, arg UpsertRepoSBOMExportParams) (RepoSbomExport, error) {
	row := db.QueryRow(ctx, upsertRepoSBOMExport,
		arg.RepoID,
		arg.Format,
		arg.SourceHeadSha,
		arg.DependencySnapshotGeneratedAt,
		arg.Document,
		arg.ByteCount,
		arg.GeneratedBy,
	)
	var i RepoSbomExport
	err := row.Scan(
		&i.RepoID,
		&i.Format,
		&i.SourceHeadSha,
		&i.DependencySnapshotGeneratedAt,
		&i.Document,
		&i.ByteCount,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.UpdatedAt,
	)
	return i, err
}
