// SPDX-License-Identifier: AGPL-3.0-or-later

package extensions

// emojiMap is a small curated set of emoji shortcodes mapped to
// their unicode rune sequences. Sourced from the gemoji project's
// stable subset; we deliberately avoid trending/political shortcodes.
//
// Adding a shortcode: append below + bump `markdown.Version`. Bytes
// are direct UTF-8 (no escape sequences) so the file's bytes are
// the rendered output.
var emojiMap = map[string]string{
	// Common reactions
	"+1":                     "👍",
	"-1":                     "👎",
	"thumbsup":               "👍",
	"thumbsdown":             "👎",
	"smile":                  "😄",
	"laughing":               "😆",
	"joy":                    "😂",
	"heart":                  "❤️",
	"heart_eyes":             "😍",
	"tada":                   "🎉",
	"rocket":                 "🚀",
	"fire":                   "🔥",
	"sparkles":               "✨",
	"eyes":                   "👀",
	"thinking":               "🤔",
	"thinking_face":          "🤔",
	"wave":                   "👋",
	"clap":                   "👏",
	"pray":                   "🙏",
	"100":                    "💯",
	"check":                  "✅",
	"x":                      "❌",
	"warning":                "⚠️",
	"bug":                    "🐛",
	"sparkle":                "✨",
	"star":                   "⭐",
	"hammer":                 "🔨",
	"wrench":                 "🔧",
	"package":                "📦",
	"books":                  "📚",
	"book":                   "📖",
	"memo":                   "📝",
	"pencil":                 "✏️",
	"shipit":                 "🚢",
	"ship":                   "🚢",
	"lock":                   "🔒",
	"unlock":                 "🔓",
	"key":                    "🔑",
	"link":                   "🔗",
	"speech_balloon":         "💬",
	"thought_balloon":        "💭",
	"computer":               "💻",
	"keyboard":               "⌨️",
	"floppy_disk":            "💾",
	"cd":                     "💿",
	"dvd":                    "📀",
	"clipboard":              "📋",
	"chart":                  "📈",
	"bar_chart":              "📊",
	"calendar":               "📅",
	"date":                   "📆",
	"hourglass":              "⌛",
	"alarm_clock":            "⏰",
	"clock1":                 "🕐",
	"bell":                   "🔔",
	"no_bell":                "🔕",
	"loudspeaker":            "📢",
	"mega":                   "📣",
	"mailbox":                "📫",
	"envelope":               "✉️",
	"postbox":                "📮",
	"package_2":              "📮",
	"mag":                    "🔍",
	"telescope":              "🔭",
	"microscope":             "🔬",
	"hammer_and_wrench":      "🛠️",
	"gear":                   "⚙️",
	"toolbox":                "🧰",
	"nut_and_bolt":           "🔩",
	"satellite":              "📡",
	"globe":                  "🌍",
	"earth_americas":         "🌎",
	"earth_asia":             "🌏",
	"new":                    "🆕",
	"free":                   "🆓",
	"abc":                    "🔤",
	"abcd":                   "🔡",
	"capital_abcd":           "🔠",
	"information_source":     "ℹ️",
	"interrobang":            "⁉️",
	"question":               "❓",
	"grey_question":          "❔",
	"exclamation":            "❗",
	"grey_exclamation":       "❕",
	"o":                      "⭕",
	"x_circle":               "❌",
	"white_check_mark":       "✅",
	"ballot_box_with_check":  "☑️",
	"heavy_check_mark":       "✔️",
	"heavy_multiplication_x": "✖️",
	"heavy_plus_sign":        "➕",
	"heavy_minus_sign":       "➖",
	"heavy_division_sign":    "➗",
	"recycle":                "♻️",
	"infinity":               "♾️",
	"trophy":                 "🏆",
	"medal":                  "🏅",
	"first_place":            "🥇",
	"second_place":           "🥈",
	"third_place":            "🥉",
	"crown":                  "👑",
	"gem":                    "💎",
	"art":                    "🎨",
	"musical_note":           "🎵",
	"musical_score":          "🎼",
	"sound":                  "🔊",
	"mute":                   "🔇",
	"video_camera":           "📹",
	"camera":                 "📷",
	"camera_flash":           "📸",
	"film_strip":             "🎞️",
	"clapper":                "🎬",
	"microphone":             "🎤",
	"headphones":             "🎧",
	"radio":                  "📻",
	"tv":                     "📺",
	"phone":                  "📞",
	"telephone":              "☎️",
	"iphone":                 "📱",
	"calling":                "📲",
	"battery":                "🔋",
	"electric_plug":          "🔌",
	"bulb":                   "💡",
	"flashlight":             "🔦",
	"candle":                 "🕯️",
	"sun":                    "☀️",
	"sunny":                  "☀️",
	"moon":                   "🌙",
	"star_2":                 "🌟",
	"stars":                  "🌠",
	"cloud":                  "☁️",
	"snowflake":              "❄️",
	"zap":                    "⚡",
	"umbrella":               "☂️",
	"rainbow":                "🌈",
	"droplet":                "💧",
	"ocean":                  "🌊",
	"snowman":                "☃️",
	"comet":                  "☄️",
	"v":                      "✌️",
	"point_up":               "☝️",
	"point_down":             "👇",
	"point_left":             "👈",
	"point_right":            "👉",
	"raised_hand":            "✋",
	"open_hands":             "👐",
	"muscle":                 "💪",
	"writing_hand":           "✍️",
	"selfie":                 "🤳",
	"facepunch":              "👊",
	"fist":                   "✊",
	"poo":                    "💩",
	"hankey":                 "💩",
	"shit":                   "💩",
}

// lookupEmoji returns the unicode replacement for a shortcode,
// or ("", false) if the code isn't in our curated set.
func lookupEmoji(name string) (string, bool) {
	v, ok := emojiMap[name]
	return v, ok
}
