// SPDX-License-Identifier: AGPL-3.0-or-later

// Package hooks owns the bare-repo hook installation contract used by
// the push pipeline (S14). pre-receive and post-receive are tiny shell
// shims that re-invoke shithubd. They're symlinks so a binary upgrade
// doesn't require touching every repo's hooks directory.
//
// Why shell shims and not direct symlinks to the binary: git invokes
// the hook with stdin piped and a particular cwd, and the shim lets us
// preserve the env (the SHITHUB_* vars set by S12/S13) while routing
// to a stable subcommand interface. The shim is generated once at
// install time; we don't depend on its file path matching the binary.
package hooks

import (
	"fmt"
	"os"
	"path/filepath"
)

// SupportedHooks is the canonical list of hooks the push pipeline owns.
// Add new hook names here and they'll be installed on every repo init.
var SupportedHooks = []string{"pre-receive", "post-receive"}

// Install (re)installs every supported hook on the bare repo at gitDir.
// shithubdPath is the absolute path to the shithubd binary the shim
// should invoke. Permissions are forced to 0o755 (owner: rwx; group +
// other: rx) — git refuses to run hooks lacking the executable bit.
//
// Install is idempotent: re-running on a repo that already has up-to-
// date hooks is a no-op. If a hook file exists but doesn't match the
// expected shim, it's overwritten.
func Install(gitDir, shithubdPath string) error {
	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("hooks: mkdir %s: %w", hooksDir, err)
	}
	for _, name := range SupportedHooks {
		path := filepath.Join(hooksDir, name)
		body := shim(shithubdPath, name)
		if err := writeAtomic(path, body, 0o755); err != nil {
			return fmt.Errorf("hooks: write %s: %w", path, err)
		}
	}
	return nil
}

// shim is the body of the wrapper script git executes. It exec's into
// shithubd, replacing itself so signals (and the exit code) propagate
// cleanly. Stdin is the pkt-line stream git passes the hook; we forward
// it untouched.
func shim(shithubdPath, hookName string) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by shithubd hooks.Install. Do not edit by hand — re-run
# 'shithubd hooks reinstall' if the binary path changes.
exec %q hook %s "$@"
`, shithubdPath, hookName)
}

// writeAtomic writes body to path via a same-directory tmpfile + rename
// so a partial write can never expose an unbootable hook to git.
func writeAtomic(path string, body string, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".shithub-hook-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		// If rename succeeded the file is gone and Remove is a no-op error
		// we can swallow.
		_ = os.Remove(tmpName)
	}()
	if _, err := tmp.WriteString(body); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}
