// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratelimitdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// SPDX-License-Identifier: AGPL-3.0-or-later
	//
	// Generic rate-limit counter queries (S35). Two write paths:
	//   * BumpRateLimit — atomic UPSERT that rolls the window forward
	//                     when stale, increments hits otherwise. Returns
	//                     the post-update hits + window_started_at so
	//                     the caller can compute Retry-After without a
	//                     second round trip.
	//   * BumpSignupIPThrottle — same shape against signup_ip_throttle
	//                            keyed by inet/CIDR.
	//
	// Reads (PeekRateLimit, PeekSignupIPThrottle) are kept around for
	// the admin observability surface; the hot path uses Bump-and-decide.
	// Roll-or-increment in one statement. The CASE in the UPDATE branch
	// handles the window roll: when the existing window started before
	// (now - $3 interval), we treat it as a new window and reset hits
	// to 1; otherwise we increment in place.
	BumpRateLimit(ctx context.Context, db DBTX, arg BumpRateLimitParams) (BumpRateLimitRow, error)
	// Same UPSERT shape against the inet-keyed signup throttle.
	BumpSignupIPThrottle(ctx context.Context, db DBTX, arg BumpSignupIPThrottleParams) (BumpSignupIPThrottleRow, error)
	PeekRateLimit(ctx context.Context, db DBTX, arg PeekRateLimitParams) (RateLimit, error)
	PruneRateLimits(ctx context.Context, db DBTX, retention pgtype.Interval) (int64, error)
	PruneSignupIPThrottle(ctx context.Context, db DBTX, retention pgtype.Interval) (int64, error)
}

var _ Querier = (*Queries)(nil)
