// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package socialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDomainEvent = `-- name: InsertDomainEvent :one

INSERT INTO domain_events (
    actor_user_id, kind, repo_id, source_kind, source_id, public, payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, actor_user_id, kind, repo_id, source_kind, source_id, public, payload, created_at
`

type InsertDomainEventParams struct {
	ActorUserID pgtype.Int8
	Kind        string
	RepoID      pgtype.Int8
	SourceKind  string
	SourceID    int64
	Public      bool
	Payload     []byte
}

// ─── domain_events ─────────────────────────────────────────────────
// Returns the inserted row so callers that want to fire a follow-on
// (e.g. NOTIFY for the worker pool) have the id without a re-read.
func (q *Queries) InsertDomainEvent(ctx context.Context, db DBTX, arg InsertDomainEventParams) (DomainEvent, error) {
	row := db.QueryRow(ctx, insertDomainEvent,
		arg.ActorUserID,
		arg.Kind,
		arg.RepoID,
		arg.SourceKind,
		arg.SourceID,
		arg.Public,
		arg.Payload,
	)
	var i DomainEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Kind,
		&i.RepoID,
		&i.SourceKind,
		&i.SourceID,
		&i.Public,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsForRepo = `-- name: ListEventsForRepo :many
SELECT id, actor_user_id, kind, repo_id, source_kind, source_id, public, payload, created_at
FROM domain_events
WHERE repo_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsForRepoParams struct {
	RepoID pgtype.Int8
	Limit  int32
	Offset int32
}

// Repo-scoped events, recency-sorted. No visibility filter — the
// caller has already established read access to the repo.
func (q *Queries) ListEventsForRepo(ctx context.Context, db DBTX, arg ListEventsForRepoParams) ([]DomainEvent, error) {
	rows, err := db.Query(ctx, listEventsForRepo, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEvent{}
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Kind,
			&i.RepoID,
			&i.SourceKind,
			&i.SourceID,
			&i.Public,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEventsForActor = `-- name: ListPublicEventsForActor :many
SELECT id, actor_user_id, kind, repo_id, source_kind, source_id, public, payload, created_at
FROM domain_events
WHERE actor_user_id = $1
  AND public = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPublicEventsForActorParams struct {
	ActorUserID pgtype.Int8
	Limit       int32
	Offset      int32
}

// Public activity-feed slice for a user's profile. Returns only
// public rows, recency-sorted. The handler additionally filters by
// repo visibility against the viewer (a public event row on a repo
// whose visibility flipped to private must not leak).
func (q *Queries) ListPublicEventsForActor(ctx context.Context, db DBTX, arg ListPublicEventsForActorParams) ([]DomainEvent, error) {
	rows, err := db.Query(ctx, listPublicEventsForActor, arg.ActorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainEvent{}
	for rows.Next() {
		var i DomainEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Kind,
			&i.RepoID,
			&i.SourceKind,
			&i.SourceID,
			&i.Public,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
