// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package socialdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowersForOrg = `-- name: CountFollowersForOrg :one
SELECT COUNT(*) FROM follows f
JOIN users u ON u.id = f.follower_user_id
WHERE f.followee_org_id = $1
  AND u.suspended_at IS NULL
  AND u.deleted_at IS NULL
`

func (q *Queries) CountFollowersForOrg(ctx context.Context, db DBTX, followeeOrgID pgtype.Int8) (int64, error) {
	row := db.QueryRow(ctx, countFollowersForOrg, followeeOrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowersForUser = `-- name: CountFollowersForUser :one
SELECT COUNT(*) FROM follows f
JOIN users u ON u.id = f.follower_user_id
WHERE f.followee_user_id = $1
  AND u.suspended_at IS NULL
  AND u.deleted_at IS NULL
`

func (q *Queries) CountFollowersForUser(ctx context.Context, db DBTX, followeeUserID pgtype.Int8) (int64, error) {
	row := db.QueryRow(ctx, countFollowersForUser, followeeUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowingForUser = `-- name: CountFollowingForUser :one
SELECT COUNT(*) FROM follows f
LEFT JOIN users u ON u.id = f.followee_user_id
LEFT JOIN orgs o ON o.id = f.followee_org_id
WHERE f.follower_user_id = $1
  AND (f.followee_user_id IS NULL OR (u.suspended_at IS NULL AND u.deleted_at IS NULL))
  AND (f.followee_org_id IS NULL OR (o.suspended_at IS NULL AND o.deleted_at IS NULL))
`

func (q *Queries) CountFollowingForUser(ctx context.Context, db DBTX, followerUserID int64) (int64, error) {
	row := db.QueryRow(ctx, countFollowingForUser, followerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followOrg = `-- name: FollowOrg :one
WITH inserted AS (
    INSERT INTO follows (follower_user_id, followee_org_id)
    VALUES ($1, $2)
    ON CONFLICT (follower_user_id, followee_org_id)
        WHERE followee_org_id IS NOT NULL
    DO NOTHING
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM inserted) AS inserted
`

type FollowOrgParams struct {
	FollowerUserID int64
	FolloweeOrgID  pgtype.Int8
}

func (q *Queries) FollowOrg(ctx context.Context, db DBTX, arg FollowOrgParams) (bool, error) {
	row := db.QueryRow(ctx, followOrg, arg.FollowerUserID, arg.FolloweeOrgID)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const followUser = `-- name: FollowUser :one

WITH inserted AS (
    INSERT INTO follows (follower_user_id, followee_user_id)
    VALUES ($1, $2)
    ON CONFLICT (follower_user_id, followee_user_id)
        WHERE followee_user_id IS NOT NULL
    DO NOTHING
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM inserted) AS inserted
`

type FollowUserParams struct {
	FollowerUserID int64
	FolloweeUserID pgtype.Int8
}

// ─── follows ───────────────────────────────────────────────────────
func (q *Queries) FollowUser(ctx context.Context, db DBTX, arg FollowUserParams) (bool, error) {
	row := db.QueryRow(ctx, followUser, arg.FollowerUserID, arg.FolloweeUserID)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const isFollowingOrg = `-- name: IsFollowingOrg :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_user_id = $1
      AND followee_org_id = $2
) AS following
`

type IsFollowingOrgParams struct {
	FollowerUserID int64
	FolloweeOrgID  pgtype.Int8
}

func (q *Queries) IsFollowingOrg(ctx context.Context, db DBTX, arg IsFollowingOrgParams) (bool, error) {
	row := db.QueryRow(ctx, isFollowingOrg, arg.FollowerUserID, arg.FolloweeOrgID)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const isFollowingUser = `-- name: IsFollowingUser :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_user_id = $1
      AND followee_user_id = $2
) AS following
`

type IsFollowingUserParams struct {
	FollowerUserID int64
	FolloweeUserID pgtype.Int8
}

func (q *Queries) IsFollowingUser(ctx context.Context, db DBTX, arg IsFollowingUserParams) (bool, error) {
	row := db.QueryRow(ctx, isFollowingUser, arg.FollowerUserID, arg.FolloweeUserID)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const listFollowersForOrg = `-- name: ListFollowersForOrg :many
SELECT f.follower_user_id AS user_id, f.followed_at, u.username, u.display_name
FROM follows f
JOIN users u ON u.id = f.follower_user_id
WHERE f.followee_org_id = $1
  AND u.suspended_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY f.followed_at DESC, f.id DESC
LIMIT $2 OFFSET $3
`

type ListFollowersForOrgParams struct {
	FolloweeOrgID pgtype.Int8
	Limit         int32
	Offset        int32
}

type ListFollowersForOrgRow struct {
	UserID      int64
	FollowedAt  pgtype.Timestamptz
	Username    string
	DisplayName string
}

func (q *Queries) ListFollowersForOrg(ctx context.Context, db DBTX, arg ListFollowersForOrgParams) ([]ListFollowersForOrgRow, error) {
	rows, err := db.Query(ctx, listFollowersForOrg, arg.FolloweeOrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersForOrgRow{}
	for rows.Next() {
		var i ListFollowersForOrgRow
		if err := rows.Scan(
			&i.UserID,
			&i.FollowedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowersForUser = `-- name: ListFollowersForUser :many
SELECT f.follower_user_id AS user_id, f.followed_at, u.username, u.display_name
FROM follows f
JOIN users u ON u.id = f.follower_user_id
WHERE f.followee_user_id = $1
  AND u.suspended_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY f.followed_at DESC, f.id DESC
LIMIT $2 OFFSET $3
`

type ListFollowersForUserParams struct {
	FolloweeUserID pgtype.Int8
	Limit          int32
	Offset         int32
}

type ListFollowersForUserRow struct {
	UserID      int64
	FollowedAt  pgtype.Timestamptz
	Username    string
	DisplayName string
}

func (q *Queries) ListFollowersForUser(ctx context.Context, db DBTX, arg ListFollowersForUserParams) ([]ListFollowersForUserRow, error) {
	rows, err := db.Query(ctx, listFollowersForUser, arg.FolloweeUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersForUserRow{}
	for rows.Next() {
		var i ListFollowersForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.FollowedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingOrgsForUser = `-- name: ListFollowingOrgsForUser :many
SELECT f.followee_org_id AS org_id, f.followed_at, o.slug, o.display_name
FROM follows f
JOIN orgs o ON o.id = f.followee_org_id
WHERE f.follower_user_id = $1
  AND o.suspended_at IS NULL
  AND o.deleted_at IS NULL
ORDER BY f.followed_at DESC, f.id DESC
LIMIT $2 OFFSET $3
`

type ListFollowingOrgsForUserParams struct {
	FollowerUserID int64
	Limit          int32
	Offset         int32
}

type ListFollowingOrgsForUserRow struct {
	OrgID       pgtype.Int8
	FollowedAt  pgtype.Timestamptz
	Slug        string
	DisplayName string
}

func (q *Queries) ListFollowingOrgsForUser(ctx context.Context, db DBTX, arg ListFollowingOrgsForUserParams) ([]ListFollowingOrgsForUserRow, error) {
	rows, err := db.Query(ctx, listFollowingOrgsForUser, arg.FollowerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingOrgsForUserRow{}
	for rows.Next() {
		var i ListFollowingOrgsForUserRow
		if err := rows.Scan(
			&i.OrgID,
			&i.FollowedAt,
			&i.Slug,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingUsersForUser = `-- name: ListFollowingUsersForUser :many
SELECT f.followee_user_id AS user_id, f.followed_at, u.username, u.display_name
FROM follows f
JOIN users u ON u.id = f.followee_user_id
WHERE f.follower_user_id = $1
  AND u.suspended_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY f.followed_at DESC, f.id DESC
LIMIT $2 OFFSET $3
`

type ListFollowingUsersForUserParams struct {
	FollowerUserID int64
	Limit          int32
	Offset         int32
}

type ListFollowingUsersForUserRow struct {
	UserID      pgtype.Int8
	FollowedAt  pgtype.Timestamptz
	Username    string
	DisplayName string
}

func (q *Queries) ListFollowingUsersForUser(ctx context.Context, db DBTX, arg ListFollowingUsersForUserParams) ([]ListFollowingUsersForUserRow, error) {
	rows, err := db.Query(ctx, listFollowingUsersForUser, arg.FollowerUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingUsersForUserRow{}
	for rows.Next() {
		var i ListFollowingUsersForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.FollowedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowOrg = `-- name: UnfollowOrg :execrows
DELETE FROM follows
WHERE follower_user_id = $1
  AND followee_org_id = $2
`

type UnfollowOrgParams struct {
	FollowerUserID int64
	FolloweeOrgID  pgtype.Int8
}

func (q *Queries) UnfollowOrg(ctx context.Context, db DBTX, arg UnfollowOrgParams) (int64, error) {
	result, err := db.Exec(ctx, unfollowOrg, arg.FollowerUserID, arg.FolloweeOrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollowUser = `-- name: UnfollowUser :execrows
DELETE FROM follows
WHERE follower_user_id = $1
  AND followee_user_id = $2
`

type UnfollowUserParams struct {
	FollowerUserID int64
	FolloweeUserID pgtype.Int8
}

func (q *Queries) UnfollowUser(ctx context.Context, db DBTX, arg UnfollowUserParams) (int64, error) {
	result, err := db.Exec(ctx, unfollowUser, arg.FollowerUserID, arg.FolloweeUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
