// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package socialdb

import (
	"context"
)

type Querier interface {
	CountStargazersForRepo(ctx context.Context, db DBTX, repoID int64) (int64, error)
	CountStarsForUser(ctx context.Context, db DBTX, userID int64) (int64, error)
	CountWatchersForRepo(ctx context.Context, db DBTX, repoID int64) (int64, error)
	DeleteStar(ctx context.Context, db DBTX, arg DeleteStarParams) error
	// Used when a user unsets their explicit preference (returning to the
	// implicit `participating` default). Trigger drops the watcher_count
	// when the prior level wasn't 'ignore'.
	DeleteWatch(ctx context.Context, db DBTX, arg DeleteWatchParams) error
	// ─── watches ───────────────────────────────────────────────────────
	GetWatch(ctx context.Context, db DBTX, arg GetWatchParams) (Watch, error)
	HasStar(ctx context.Context, db DBTX, arg HasStarParams) (bool, error)
	// ─── domain_events ─────────────────────────────────────────────────
	// Returns the inserted row so callers that want to fire a follow-on
	// (e.g. NOTIFY for the worker pool) have the id without a re-read.
	InsertDomainEvent(ctx context.Context, db DBTX, arg InsertDomainEventParams) (DomainEvent, error)
	// ─── stars ─────────────────────────────────────────────────────────
	// ON CONFLICT DO NOTHING is the idempotency guard: re-starring an
	// already-starred repo doesn't double-increment the count (the
	// AFTER INSERT trigger only fires on actual insert).
	InsertStar(ctx context.Context, db DBTX, arg InsertStarParams) error
	// Auto-watch flow: only insert if the user doesn't already have a
	// preference. ON CONFLICT DO NOTHING preserves the user's chosen
	// level when the trigger fires repeatedly.
	InsertWatchIfAbsent(ctx context.Context, db DBTX, arg InsertWatchIfAbsentParams) error
	// Repo-scoped events, recency-sorted. No visibility filter — the
	// caller has already established read access to the repo.
	ListEventsForRepo(ctx context.Context, db DBTX, arg ListEventsForRepoParams) ([]DomainEvent, error)
	// Public activity-feed slice for a user's profile. Returns only
	// public rows, recency-sorted. The handler additionally filters by
	// repo visibility against the viewer (a public event row on a repo
	// whose visibility flipped to private must not leak).
	ListPublicEventsForActor(ctx context.Context, db DBTX, arg ListPublicEventsForActorParams) ([]DomainEvent, error)
	// S29 notification-routing consumer: for fan-out, get every watcher
	// of a repo at the requested level (e.g. `level='all'` for new-issue
	// events). This is the cross-package read; expose the user_ids
	// without joining users — fan-out adds the user join itself.
	ListRepoWatchersByLevel(ctx context.Context, db DBTX, arg ListRepoWatchersByLevelParams) ([]int64, error)
	// Public-repo stargazer list. Paginated by `starred_at DESC`.
	// Excludes suspended users so they don't taint public lists. The
	// private-repo gate is at the handler layer (policy.IsVisibleTo).
	ListStargazersForRepo(ctx context.Context, db DBTX, arg ListStargazersForRepoParams) ([]ListStargazersForRepoRow, error)
	// The "Stars" profile tab. The handler layer post-filters for repo
	// visibility against the viewer; this query returns everything the
	// user starred and lets the handler decide what to render. Sort axis
	// is the spec's day-1 lean: most-recently-starred first.
	ListStarsForUser(ctx context.Context, db DBTX, arg ListStarsForUserParams) ([]ListStarsForUserRow, error)
	// Watchers list. `level <> 'ignore'` excludes users who have actively
	// muted the repo. Excludes suspended users from public surfaces.
	ListWatchersForRepo(ctx context.Context, db DBTX, arg ListWatchersForRepoParams) ([]ListWatchersForRepoRow, error)
	// Always-write upsert. The AFTER trigger handles the watcher_count
	// delta on transition into / out of `ignore`.
	UpsertWatch(ctx context.Context, db DBTX, arg UpsertWatchParams) error
}

var _ Querier = (*Queries)(nil)
