// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package notifdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsForRecipient = `-- name: CountNotificationsForRecipient :one
SELECT count(*) FROM notifications
WHERE recipient_user_id = $1
  AND ($2::boolean = false OR unread = true)
`

type CountNotificationsForRecipientParams struct {
	RecipientUserID int64
	Column2         bool
}

func (q *Queries) CountNotificationsForRecipient(ctx context.Context, db DBTX, arg CountNotificationsForRecipientParams) (int64, error) {
	row := db.QueryRow(ctx, countNotificationsForRecipient, arg.RecipientUserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadForRecipient = `-- name: CountUnreadForRecipient :one
SELECT count(*) FROM notifications
WHERE recipient_user_id = $1
  AND unread = true
  AND (tab_label IS NULL OR tab_label <> 'dropped')
  AND (snoozed_until IS NULL OR snoozed_until <= now())
`

// Inbox badge count. PRO-EXT01-16c: matches the default-view filter
// so a user with all their notifications snoozed sees a clean 0 in
// the nav, not a misleading total that includes asleep rows.
func (q *Queries) CountUnreadForRecipient(ctx context.Context, db DBTX, recipientUserID int64) (int64, error) {
	row := db.QueryRow(ctx, countUnreadForRecipient, recipientUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, recipient_user_id, kind, reason, repo_id,
       thread_kind, thread_id, source_event_id, unread,
       last_event_at, last_actor_user_id, summary, created_at, updated_at
FROM notifications WHERE id = $1
`

type GetNotificationRow struct {
	ID              int64
	RecipientUserID int64
	Kind            string
	Reason          string
	RepoID          pgtype.Int8
	ThreadKind      NullNotificationThreadKind
	ThreadID        pgtype.Int8
	SourceEventID   pgtype.Int8
	Unread          bool
	LastEventAt     pgtype.Timestamptz
	LastActorUserID pgtype.Int8
	Summary         []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetNotification(ctx context.Context, db DBTX, id int64) (GetNotificationRow, error) {
	row := db.QueryRow(ctx, getNotification, id)
	var i GetNotificationRow
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.Kind,
		&i.Reason,
		&i.RepoID,
		&i.ThreadKind,
		&i.ThreadID,
		&i.SourceEventID,
		&i.Unread,
		&i.LastEventAt,
		&i.LastActorUserID,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertThreadlessNotification = `-- name: InsertThreadlessNotification :one
INSERT INTO notifications (
    recipient_user_id, kind, reason, repo_id,
    source_event_id, last_actor_user_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, recipient_user_id, kind, reason, repo_id,
          thread_kind, thread_id, source_event_id, unread,
          last_event_at, last_actor_user_id, summary, created_at, updated_at,
          snoozed_until, tab_label, matched_rule_id
`

type InsertThreadlessNotificationParams struct {
	RecipientUserID int64
	Kind            string
	Reason          string
	RepoID          pgtype.Int8
	SourceEventID   pgtype.Int8
	LastActorUserID pgtype.Int8
}

// For events with no thread (e.g. repo-admin lifecycle: archived).
// These don't coalesce; each fires its own row. Used sparingly.
func (q *Queries) InsertThreadlessNotification(ctx context.Context, db DBTX, arg InsertThreadlessNotificationParams) (Notification, error) {
	row := db.QueryRow(ctx, insertThreadlessNotification,
		arg.RecipientUserID,
		arg.Kind,
		arg.Reason,
		arg.RepoID,
		arg.SourceEventID,
		arg.LastActorUserID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.Kind,
		&i.Reason,
		&i.RepoID,
		&i.ThreadKind,
		&i.ThreadID,
		&i.SourceEventID,
		&i.Unread,
		&i.LastEventAt,
		&i.LastActorUserID,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozedUntil,
		&i.TabLabel,
		&i.MatchedRuleID,
	)
	return i, err
}

const listInboxTabsForRecipient = `-- name: ListInboxTabsForRecipient :many
SELECT tab_label::text AS label, count(*)::int AS count
FROM notifications
WHERE recipient_user_id = $1
  AND tab_label IS NOT NULL
  AND tab_label <> 'dropped'
GROUP BY tab_label
ORDER BY tab_label ASC
`

type ListInboxTabsForRecipientRow struct {
	Label string
	Count int32
}

// Surfaces the distinct tab labels the user has rules routing into,
// with a count per tab. The inbox nav renders one chip per result so
// the user can switch tabs. 'dropped' is excluded from the chip list
// (it's auditable via ?tab=dropped but doesn't deserve nav real
// estate by default).
func (q *Queries) ListInboxTabsForRecipient(ctx context.Context, db DBTX, recipientUserID int64) ([]ListInboxTabsForRecipientRow, error) {
	rows, err := db.Query(ctx, listInboxTabsForRecipient, recipientUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxTabsForRecipientRow{}
	for rows.Next() {
		var i ListInboxTabsForRecipientRow
		if err := rows.Scan(&i.Label, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForRecipient = `-- name: ListNotificationsForRecipient :many
SELECT n.id, n.recipient_user_id, n.kind, n.reason, n.repo_id,
       n.thread_kind, n.thread_id, n.source_event_id, n.unread,
       n.last_event_at, n.last_actor_user_id, n.summary,
       n.created_at, n.updated_at,
       n.snoozed_until, n.tab_label, n.matched_rule_id,
       coalesce(u.username, '') AS actor_username,
       coalesce(r.name, '') AS repo_name,
       coalesce(ru.username, '') AS repo_owner_username,
       coalesce(i.number, 0) AS thread_number,
       coalesce(i.title, '') AS thread_title
FROM notifications n
LEFT JOIN users u  ON u.id = n.last_actor_user_id
LEFT JOIN repos r  ON r.id = n.repo_id
LEFT JOIN users ru ON ru.id = r.owner_user_id
LEFT JOIN issues i ON i.id = n.thread_id
WHERE n.recipient_user_id = $1
  AND ($2::boolean = false OR n.unread = true)
  AND (
    -- @tab_filter = '' → default Inbox view: hide dropped + hide
    -- snoozes that haven't yet woken up.
    ($5::text = '' AND (n.tab_label IS NULL OR n.tab_label <> 'dropped')
                 AND (n.snoozed_until IS NULL OR n.snoozed_until <= now()))
    -- Non-empty filter → exact tab match (works for 'dropped' too,
    -- so an investigation user can audit what their rules ate).
    OR ($5::text <> '' AND n.tab_label = $5::text)
  )
ORDER BY n.last_event_at DESC
LIMIT $3 OFFSET $4
`

type ListNotificationsForRecipientParams struct {
	RecipientUserID int64
	Column2         bool
	Limit           int32
	Offset          int32
	Column5         string
}

type ListNotificationsForRecipientRow struct {
	ID                int64
	RecipientUserID   int64
	Kind              string
	Reason            string
	RepoID            pgtype.Int8
	ThreadKind        NullNotificationThreadKind
	ThreadID          pgtype.Int8
	SourceEventID     pgtype.Int8
	Unread            bool
	LastEventAt       pgtype.Timestamptz
	LastActorUserID   pgtype.Int8
	Summary           []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	SnoozedUntil      pgtype.Timestamptz
	TabLabel          pgtype.Text
	MatchedRuleID     pgtype.Int8
	ActorUsername     string
	RepoName          string
	RepoOwnerUsername string
	ThreadNumber      int64
	ThreadTitle       string
}

// Inbox view, recency-sorted. PRO-EXT01-16c extends the original
// with:
//   - snoozed_until / tab_label / matched_rule_id from the rule
//     engine (PRO-EXT01-16a), so the template can render the badges.
//   - @tab_filter — when non-empty, restrict to that tab. Empty
//     string returns the default Inbox view (tab_label IS NULL or
//     awake snoozes), hiding snoozed-but-not-yet-due + dropped rows.
func (q *Queries) ListNotificationsForRecipient(ctx context.Context, db DBTX, arg ListNotificationsForRecipientParams) ([]ListNotificationsForRecipientRow, error) {
	rows, err := db.Query(ctx, listNotificationsForRecipient,
		arg.RecipientUserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsForRecipientRow{}
	for rows.Next() {
		var i ListNotificationsForRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientUserID,
			&i.Kind,
			&i.Reason,
			&i.RepoID,
			&i.ThreadKind,
			&i.ThreadID,
			&i.SourceEventID,
			&i.Unread,
			&i.LastEventAt,
			&i.LastActorUserID,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SnoozedUntil,
			&i.TabLabel,
			&i.MatchedRuleID,
			&i.ActorUsername,
			&i.RepoName,
			&i.RepoOwnerUsername,
			&i.ThreadNumber,
			&i.ThreadTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllReadForRecipient = `-- name: MarkAllReadForRecipient :exec
UPDATE notifications SET unread = false, updated_at = now()
WHERE recipient_user_id = $1 AND unread = true
`

// Bounded sweep: a single call doesn't try to update millions of
// rows. Caller paginates via repeated calls when count > batch.
func (q *Queries) MarkAllReadForRecipient(ctx context.Context, db DBTX, recipientUserID int64) error {
	_, err := db.Exec(ctx, markAllReadForRecipient, recipientUserID)
	return err
}

const setNotificationRead = `-- name: SetNotificationRead :exec
UPDATE notifications SET unread = false, updated_at = now()
WHERE id = $1 AND recipient_user_id = $2
`

type SetNotificationReadParams struct {
	ID              int64
	RecipientUserID int64
}

func (q *Queries) SetNotificationRead(ctx context.Context, db DBTX, arg SetNotificationReadParams) error {
	_, err := db.Exec(ctx, setNotificationRead, arg.ID, arg.RecipientUserID)
	return err
}

const setNotificationUnread = `-- name: SetNotificationUnread :exec
UPDATE notifications SET unread = true, updated_at = now()
WHERE id = $1 AND recipient_user_id = $2
`

type SetNotificationUnreadParams struct {
	ID              int64
	RecipientUserID int64
}

func (q *Queries) SetNotificationUnread(ctx context.Context, db DBTX, arg SetNotificationUnreadParams) error {
	_, err := db.Exec(ctx, setNotificationUnread, arg.ID, arg.RecipientUserID)
	return err
}

const upsertNotificationByThread = `-- name: UpsertNotificationByThread :one

INSERT INTO notifications (
    recipient_user_id, kind, reason, repo_id,
    thread_kind, thread_id, source_event_id,
    last_event_at, last_actor_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now(), $8
)
ON CONFLICT (recipient_user_id, thread_kind, thread_id) WHERE thread_id IS NOT NULL
DO UPDATE SET
    kind               = EXCLUDED.kind,
    reason             = EXCLUDED.reason,
    source_event_id    = EXCLUDED.source_event_id,
    last_event_at      = now(),
    last_actor_user_id = EXCLUDED.last_actor_user_id,
    unread             = true,
    updated_at         = now()
RETURNING id, recipient_user_id, kind, reason, repo_id,
          thread_kind, thread_id, source_event_id, unread,
          last_event_at, last_actor_user_id, summary, created_at, updated_at,
          snoozed_until, tab_label, matched_rule_id
`

type UpsertNotificationByThreadParams struct {
	RecipientUserID int64
	Kind            string
	Reason          string
	RepoID          pgtype.Int8
	ThreadKind      NullNotificationThreadKind
	ThreadID        pgtype.Int8
	SourceEventID   pgtype.Int8
	LastActorUserID pgtype.Int8
}

// ─── notifications ─────────────────────────────────────────────────
// Coalesce-or-insert: if a row exists for (recipient, thread), bump
// last_event_at + last_actor + reason and re-flip unread=true so the
// inbox surfaces it again. Otherwise insert a fresh row.
//
// Returns the resulting row (whether it was created or updated)
// so the caller can chain an email-enqueue without a re-read.
func (q *Queries) UpsertNotificationByThread(ctx context.Context, db DBTX, arg UpsertNotificationByThreadParams) (Notification, error) {
	row := db.QueryRow(ctx, upsertNotificationByThread,
		arg.RecipientUserID,
		arg.Kind,
		arg.Reason,
		arg.RepoID,
		arg.ThreadKind,
		arg.ThreadID,
		arg.SourceEventID,
		arg.LastActorUserID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.Kind,
		&i.Reason,
		&i.RepoID,
		&i.ThreadKind,
		&i.ThreadID,
		&i.SourceEventID,
		&i.Unread,
		&i.LastEventAt,
		&i.LastActorUserID,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SnoozedUntil,
		&i.TabLabel,
		&i.MatchedRuleID,
	)
	return i, err
}
