// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package admindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminDiscardJob = `-- name: AdminDiscardJob :exec
UPDATE jobs
   SET failed_at  = now(),
       last_error = 'discarded by site admin'
 WHERE id = $1
`

// Mark a job dead without running it. Caller has already confirmed.
func (q *Queries) AdminDiscardJob(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, adminDiscardJob, id)
	return err
}

const adminRetryJob = `-- name: AdminRetryJob :exec
UPDATE jobs
   SET run_at       = now(),
       attempts     = 0,
       last_error   = NULL,
       failed_at    = NULL,
       completed_at = NULL,
       locked_by    = NULL,
       locked_at    = NULL
 WHERE id = $1
`

// Re-arm a failed/dead job for immediate retry: clear failure state,
// reset attempts, and set run_at to now() so the pool picks it up
// on the next tick.
func (q *Queries) AdminRetryJob(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, adminRetryJob, id)
	return err
}

const countActiveOrgs = `-- name: CountActiveOrgs :one
SELECT COUNT(*) FROM orgs WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveOrgs(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countActiveOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveRepos = `-- name: CountActiveRepos :one
SELECT COUNT(*) FROM repos WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveRepos(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countActiveRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsers = `-- name: CountActiveUsers :one


SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Admin-only query surface for /admin/*. Non-admin handlers should
// use the per-domain packages (usersdb, reposdb, …) directly. This
// file collects the cross-cutting reads + writes the admin UI needs:
//   - dashboard counts
//   - user/repo listings with admin-only filters (suspended, deleted)
//   - site-admin flag toggle
//   - transactional_email_log read/write
//
// Queries that already exist in their domain package (e.g.
// users.SuspendUser) are reused directly — no duplication here.
// ─── dashboard counts ────────────────────────────────────────────
func (q *Queries) CountActiveUsers(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT
    CASE
        WHEN completed_at IS NOT NULL THEN 'completed'
        WHEN failed_at    IS NOT NULL THEN 'failed'
        WHEN locked_at    IS NOT NULL THEN 'running'
        ELSE 'queued'
    END AS status,
    COUNT(*)::bigint AS n
FROM jobs
GROUP BY 1
`

type CountJobsByStatusRow struct {
	Status string
	N      int64
}

// Status is derived from the timestamp columns since the jobs table
// doesn't carry an enum: completed > failed > running > queued.
func (q *Queries) CountJobsByStatus(ctx context.Context, db DBTX) ([]CountJobsByStatusRow, error) {
	rows, err := db.Query(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSiteAdmins = `-- name: CountSiteAdmins :one
SELECT COUNT(*) FROM users WHERE is_site_admin = true AND deleted_at IS NULL
`

func (q *Queries) CountSiteAdmins(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countSiteAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuspendedUsers = `-- name: CountSuspendedUsers :one
SELECT COUNT(*) FROM users WHERE suspended_at IS NOT NULL AND deleted_at IS NULL
`

func (q *Queries) CountSuspendedUsers(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countSuspendedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJobForAdmin = `-- name: GetJobForAdmin :one
SELECT id, kind, payload, run_at, attempts, max_attempts,
       last_error, locked_by, locked_at, completed_at, failed_at, created_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobForAdmin(ctx context.Context, db DBTX, id int64) (Job, error) {
	row := db.QueryRow(ctx, getJobForAdmin, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.LockedBy,
		&i.LockedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransactionalEmail = `-- name: InsertTransactionalEmail :one

INSERT INTO transactional_email_log (
    recipient_user_id, recipient_email, kind, subject, provider_id,
    status, error_summary
) VALUES (
    $1::bigint,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::text
)
RETURNING id
`

type InsertTransactionalEmailParams struct {
	RecipientUserID pgtype.Int8
	RecipientEmail  string
	Kind            string
	Subject         string
	ProviderID      string
	Status          TransactionalEmailStatus
	ErrorSummary    pgtype.Text
}

// ─── transactional email log ─────────────────────────────────────
func (q *Queries) InsertTransactionalEmail(ctx context.Context, db DBTX, arg InsertTransactionalEmailParams) (int64, error) {
	row := db.QueryRow(ctx, insertTransactionalEmail,
		arg.RecipientUserID,
		arg.RecipientEmail,
		arg.Kind,
		arg.Subject,
		arg.ProviderID,
		arg.Status,
		arg.ErrorSummary,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAuditForAdmin = `-- name: ListAuditForAdmin :many

SELECT id, actor_id, action, target_type, target_id, meta, created_at
FROM auth_audit_log
WHERE
    ($3::bigint  IS NULL OR actor_id = $3::bigint)
    AND ($4::text IS NULL OR action ILIKE $4::text || '%')
    AND ($5::text IS NULL OR target_type = $5::text)
    AND ($6::bigint IS NULL OR target_id = $6::bigint)
    AND ($7::timestamptz IS NULL OR created_at >= $7::timestamptz)
    AND ($8::timestamptz IS NULL OR created_at <  $8::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAuditForAdminParams struct {
	Limit        int32
	Offset       int32
	ActorID      pgtype.Int8
	ActionPrefix pgtype.Text
	TargetType   pgtype.Text
	TargetID     pgtype.Int8
	Since        pgtype.Timestamptz
	Until        pgtype.Timestamptz
}

// ─── audit log viewer ────────────────────────────────────────────
// Filters: actor, action prefix, target type+id, time range. Keyset
// pagination on (created_at, id) keeps deep pages cheap.
func (q *Queries) ListAuditForAdmin(ctx context.Context, db DBTX, arg ListAuditForAdminParams) ([]AuthAuditLog, error) {
	rows, err := db.Query(ctx, listAuditForAdmin,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.ActionPrefix,
		arg.TargetType,
		arg.TargetID,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthAuditLog{}
	for rows.Next() {
		var i AuthAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsForAdmin = `-- name: ListJobsForAdmin :many

SELECT id, kind, payload, run_at, attempts, max_attempts,
       last_error, locked_by, locked_at, completed_at, failed_at, created_at,
       CASE
           WHEN completed_at IS NOT NULL THEN 'completed'
           WHEN failed_at    IS NOT NULL THEN 'failed'
           WHEN locked_at    IS NOT NULL THEN 'running'
           ELSE 'queued'
       END AS status
FROM jobs
WHERE
    ($3::text IS NULL OR kind = $3::text)
    AND (
        $4::text IS NULL
        OR ($4::text = 'queued'    AND completed_at IS NULL AND failed_at IS NULL AND locked_at IS NULL)
        OR ($4::text = 'running'   AND completed_at IS NULL AND failed_at IS NULL AND locked_at IS NOT NULL)
        OR ($4::text = 'failed'    AND failed_at IS NOT NULL)
        OR ($4::text = 'completed' AND completed_at IS NOT NULL)
    )
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListJobsForAdminParams struct {
	Limit        int32
	Offset       int32
	Kind         pgtype.Text
	StatusFilter pgtype.Text
}

type ListJobsForAdminRow struct {
	ID          int64
	Kind        string
	Payload     []byte
	RunAt       pgtype.Timestamptz
	Attempts    int32
	MaxAttempts int32
	LastError   pgtype.Text
	LockedBy    pgtype.Text
	LockedAt    pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	FailedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Status      string
}

// ─── jobs queue inspector ────────────────────────────────────────
// The admin can filter by kind + status (computed from the timestamp
// columns). Status filter values: queued | running | failed | completed.
func (q *Queries) ListJobsForAdmin(ctx context.Context, db DBTX, arg ListJobsForAdminParams) ([]ListJobsForAdminRow, error) {
	rows, err := db.Query(ctx, listJobsForAdmin,
		arg.Limit,
		arg.Offset,
		arg.Kind,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsForAdminRow{}
	for rows.Next() {
		var i ListJobsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.RunAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.LockedBy,
			&i.LockedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactionalEmails = `-- name: ListRecentTransactionalEmails :many
SELECT id, recipient_user_id, recipient_email, kind, subject,
       provider_id, status, error_summary, sent_at, delivered_at
FROM transactional_email_log
WHERE ($2::transactional_email_status IS NULL
       OR status = $2::transactional_email_status)
ORDER BY sent_at DESC
LIMIT $1
`

type ListRecentTransactionalEmailsParams struct {
	Limit  int32
	Status NullTransactionalEmailStatus
}

// Admin email-queue surface. Most recent first; status filter optional.
func (q *Queries) ListRecentTransactionalEmails(ctx context.Context, db DBTX, arg ListRecentTransactionalEmailsParams) ([]TransactionalEmailLog, error) {
	rows, err := db.Query(ctx, listRecentTransactionalEmails, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionalEmailLog{}
	for rows.Next() {
		var i TransactionalEmailLog
		if err := rows.Scan(
			&i.ID,
			&i.RecipientUserID,
			&i.RecipientEmail,
			&i.Kind,
			&i.Subject,
			&i.ProviderID,
			&i.Status,
			&i.ErrorSummary,
			&i.SentAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposForAdmin = `-- name: ListReposForAdmin :many

SELECT r.id, r.owner_user_id, r.owner_org_id, r.name, r.visibility,
       r.is_archived, r.deleted_at, r.disk_used_bytes, r.created_at,
       u.username AS owner_user_username,
       o.slug     AS owner_org_slug
FROM repos r
LEFT JOIN users u ON u.id = r.owner_user_id
LEFT JOIN orgs  o ON o.id = r.owner_org_id
WHERE
    ($3::text IS NULL OR r.name ILIKE $3::text || '%')
    AND ($4::bool IS NOT TRUE OR r.deleted_at IS NOT NULL)
    AND ($5::bool IS NOT TRUE OR r.is_archived = true)
    AND ($6::repo_visibility IS NULL OR r.visibility = $6::repo_visibility)
ORDER BY r.id DESC
LIMIT $1 OFFSET $2
`

type ListReposForAdminParams struct {
	Limit            int32
	Offset           int32
	NamePrefix       pgtype.Text
	DeletedOnly      pgtype.Bool
	ArchivedOnly     pgtype.Bool
	VisibilityFilter NullRepoVisibility
}

type ListReposForAdminRow struct {
	ID                int64
	OwnerUserID       pgtype.Int8
	OwnerOrgID        pgtype.Int8
	Name              string
	Visibility        RepoVisibility
	IsArchived        bool
	DeletedAt         pgtype.Timestamptz
	DiskUsedBytes     int64
	CreatedAt         pgtype.Timestamptz
	OwnerUserUsername pgtype.Text
	OwnerOrgSlug      pgtype.Text
}

// ─── repos list ──────────────────────────────────────────────────
func (q *Queries) ListReposForAdmin(ctx context.Context, db DBTX, arg ListReposForAdminParams) ([]ListReposForAdminRow, error) {
	rows, err := db.Query(ctx, listReposForAdmin,
		arg.Limit,
		arg.Offset,
		arg.NamePrefix,
		arg.DeletedOnly,
		arg.ArchivedOnly,
		arg.VisibilityFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposForAdminRow{}
	for rows.Next() {
		var i ListReposForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.Name,
			&i.Visibility,
			&i.IsArchived,
			&i.DeletedAt,
			&i.DiskUsedBytes,
			&i.CreatedAt,
			&i.OwnerUserUsername,
			&i.OwnerOrgSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many

SELECT id, username, display_name, primary_email_id,
       suspended_at, deleted_at, last_login_at, is_site_admin,
       created_at
FROM users
WHERE
    ($3::text IS NULL OR username::text ILIKE $3::text || '%')
    AND ($4::bool IS NOT TRUE OR suspended_at IS NOT NULL)
    AND ($5::bool IS NOT TRUE OR deleted_at IS NOT NULL)
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListUsersForAdminParams struct {
	Limit          int32
	Offset         int32
	UsernamePrefix pgtype.Text
	SuspendedOnly  pgtype.Bool
	DeletedOnly    pgtype.Bool
}

type ListUsersForAdminRow struct {
	ID             int64
	Username       string
	DisplayName    string
	PrimaryEmailID pgtype.Int8
	SuspendedAt    pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	LastLoginAt    pgtype.Timestamptz
	IsSiteAdmin    bool
	CreatedAt      pgtype.Timestamptz
}

// ─── users list ──────────────────────────────────────────────────
// Filters: optional username prefix, optional suspended/deleted-only.
// All filters use sqlc.narg so the empty case is "no filter".
func (q *Queries) ListUsersForAdmin(ctx context.Context, db DBTX, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := db.Query(ctx, listUsersForAdmin,
		arg.Limit,
		arg.Offset,
		arg.UsernamePrefix,
		arg.SuspendedOnly,
		arg.DeletedOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForAdminRow{}
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PrimaryEmailID,
			&i.SuspendedAt,
			&i.DeletedAt,
			&i.LastLoginAt,
			&i.IsSiteAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionalEmailDelivered = `-- name: MarkTransactionalEmailDelivered :exec
UPDATE transactional_email_log
   SET status        = 'sent',
       delivered_at  = now(),
       error_summary = NULL
 WHERE id = $1
`

func (q *Queries) MarkTransactionalEmailDelivered(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, markTransactionalEmailDelivered, id)
	return err
}

const markTransactionalEmailFailed = `-- name: MarkTransactionalEmailFailed :exec
UPDATE transactional_email_log
   SET status        = $2,
       error_summary = $3
 WHERE id = $1
`

type MarkTransactionalEmailFailedParams struct {
	ID           int64
	Status       TransactionalEmailStatus
	ErrorSummary pgtype.Text
}

func (q *Queries) MarkTransactionalEmailFailed(ctx context.Context, db DBTX, arg MarkTransactionalEmailFailedParams) error {
	_, err := db.Exec(ctx, markTransactionalEmailFailed, arg.ID, arg.Status, arg.ErrorSummary)
	return err
}

const setUserSiteAdmin = `-- name: SetUserSiteAdmin :exec
UPDATE users
   SET is_site_admin = $2,
       updated_at    = now()
 WHERE id = $1
`

type SetUserSiteAdminParams struct {
	ID          int64
	IsSiteAdmin bool
}

func (q *Queries) SetUserSiteAdmin(ctx context.Context, db DBTX, arg SetUserSiteAdminParams) error {
	_, err := db.Exec(ctx, setUserSiteAdmin, arg.ID, arg.IsSiteAdmin)
	return err
}
