// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pullsdb

import (
	"context"
)

type Querier interface {
	// ─── commits + files (refreshed on synchronize) ──────────────────────
	ClearPullRequestCommits(ctx context.Context, db DBTX, prID int64) error
	ClearPullRequestFiles(ctx context.Context, db DBTX, prID int64) error
	CountPullRequestsByRepo(ctx context.Context, db DBTX, arg CountPullRequestsByRepoParams) (int64, error)
	// SPDX-License-Identifier: AGPL-3.0-or-later
	// ─── pull_requests core ──────────────────────────────────────────────
	// Creates the PR-side row keyed on issue_id (the caller already
	// inserted the issues row with kind='pr'). Defaults give a freshly-
	// opened PR `mergeable_state='unknown'` until the mergeability job
	// ticks.
	CreatePullRequest(ctx context.Context, db DBTX, arg CreatePullRequestParams) (PullRequest, error)
	GetPullRequestByIssueID(ctx context.Context, db DBTX, issueID int64) (PullRequest, error)
	// Joins issues + pull_requests so handlers can resolve via the URL
	// {owner}/{repo}/pulls/{number} in one round-trip.
	GetPullRequestByRepoAndNumber(ctx context.Context, db DBTX, arg GetPullRequestByRepoAndNumberParams) (GetPullRequestByRepoAndNumberRow, error)
	InsertPullRequestCommit(ctx context.Context, db DBTX, arg InsertPullRequestCommitParams) error
	InsertPullRequestFile(ctx context.Context, db DBTX, arg InsertPullRequestFileParams) error
	// Returns the issue_ids of every still-open PR whose head_repo_id +
	// head_ref match the pushed ref. push:process uses this to fan-out
	// pr:synchronize jobs after a head-side push.
	ListOpenPRsForHeadRef(ctx context.Context, db DBTX, arg ListOpenPRsForHeadRefParams) ([]int64, error)
	ListPullRequestCommits(ctx context.Context, db DBTX, prID int64) ([]PullRequestCommit, error)
	ListPullRequestFiles(ctx context.Context, db DBTX, prID int64) ([]PullRequestFile, error)
	// Mirrors the issues list query: state filter via narg, pagination,
	// ordered by recent activity.
	ListPullRequestsByRepo(ctx context.Context, db DBTX, arg ListPullRequestsByRepoParams) ([]ListPullRequestsByRepoRow, error)
	// FOR UPDATE row lock + return current shape so the merge job can
	// decide whether to proceed (e.g. someone else just merged it).
	LockPullRequestForMerge(ctx context.Context, db DBTX, issueID int64) (PullRequest, error)
	SetPullRequestDraft(ctx context.Context, db DBTX, arg SetPullRequestDraftParams) error
	SetPullRequestMergeability(ctx context.Context, db DBTX, arg SetPullRequestMergeabilityParams) error
	SetPullRequestMerged(ctx context.Context, db DBTX, arg SetPullRequestMergedParams) error
	// Updates base_oid + head_oid + last_synchronized_at after a
	// synchronize tick.
	SetPullRequestSnapshot(ctx context.Context, db DBTX, arg SetPullRequestSnapshotParams) error
}

var _ Querier = (*Queries)(nil)
