// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runner_jwt_used.sql

package actionsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredRunnerJWTUses = `-- name: DeleteExpiredRunnerJWTUses :exec
DELETE FROM runner_jwt_used WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRunnerJWTUses(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, deleteExpiredRunnerJWTUses)
	return err
}

const markRunnerJWTUsed = `-- name: MarkRunnerJWTUsed :one

INSERT INTO runner_jwt_used (jti, runner_id, job_id, run_id, repo_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (jti) DO NOTHING
RETURNING jti, runner_id, job_id, run_id, repo_id, expires_at, used_at
`

type MarkRunnerJWTUsedParams struct {
	Jti       string
	RunnerID  int64
	JobID     int64
	RunID     int64
	RepoID    int64
	ExpiresAt pgtype.Timestamptz
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) MarkRunnerJWTUsed(ctx context.Context, db DBTX, arg MarkRunnerJWTUsedParams) (RunnerJwtUsed, error) {
	row := db.QueryRow(ctx, markRunnerJWTUsed,
		arg.Jti,
		arg.RunnerID,
		arg.JobID,
		arg.RunID,
		arg.RepoID,
		arg.ExpiresAt,
	)
	var i RunnerJwtUsed
	err := row.Scan(
		&i.Jti,
		&i.RunnerID,
		&i.JobID,
		&i.RunID,
		&i.RepoID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
