// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_insights.sql

package actionsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActionsPerformanceSummaryForRepo = `-- name: GetActionsPerformanceSummaryForRepo :one
SELECT
    COALESCE(AVG(LEAST(
        GREATEST(EXTRACT(EPOCH FROM (job.completed_at - job.started_at)), 0),
        job.timeout_minutes::double precision * 60.0
    )) FILTER (
        WHERE job.started_at IS NOT NULL AND job.completed_at IS NOT NULL
    ), 0)::double precision AS avg_job_seconds,
    COALESCE(AVG(EXTRACT(EPOCH FROM (job.started_at - job.created_at))) FILTER (
        WHERE job.started_at IS NOT NULL AND job.started_at >= job.created_at
    ), 0)::double precision AS avg_queue_seconds,
    COUNT(job.id) FILTER (
        WHERE job.status IN ('completed', 'cancelled', 'skipped')
    )::bigint AS terminal_job_count,
    COUNT(job.id) FILTER (
        WHERE job.status IN ('completed', 'cancelled')
          AND job.conclusion IS NOT NULL
          AND job.conclusion <> 'success'
    )::bigint AS failed_job_count,
    COALESCE(SUM(LEAST(
        GREATEST(EXTRACT(EPOCH FROM (job.completed_at - job.started_at)), 0),
        job.timeout_minutes::double precision * 60.0
    )) FILTER (
        WHERE job.started_at IS NOT NULL
          AND job.completed_at IS NOT NULL
          AND job.conclusion IS NOT NULL
          AND job.conclusion <> 'success'
    ), 0)::bigint AS failed_job_seconds
FROM workflow_runs run
JOIN workflow_jobs job ON job.run_id = run.id
WHERE run.repo_id = $1
  AND run.created_at >= $2
`

type GetActionsPerformanceSummaryForRepoParams struct {
	RepoID    int64
	CreatedAt pgtype.Timestamptz
}

type GetActionsPerformanceSummaryForRepoRow struct {
	AvgJobSeconds    float64
	AvgQueueSeconds  float64
	TerminalJobCount int64
	FailedJobCount   int64
	FailedJobSeconds int64
}

func (q *Queries) GetActionsPerformanceSummaryForRepo(ctx context.Context, db DBTX, arg GetActionsPerformanceSummaryForRepoParams) (GetActionsPerformanceSummaryForRepoRow, error) {
	row := db.QueryRow(ctx, getActionsPerformanceSummaryForRepo, arg.RepoID, arg.CreatedAt)
	var i GetActionsPerformanceSummaryForRepoRow
	err := row.Scan(
		&i.AvgJobSeconds,
		&i.AvgQueueSeconds,
		&i.TerminalJobCount,
		&i.FailedJobCount,
		&i.FailedJobSeconds,
	)
	return i, err
}

const getActionsUsageSummaryForRepo = `-- name: GetActionsUsageSummaryForRepo :one

SELECT
    COUNT(DISTINCT run.id)::bigint AS run_count,
    COUNT(job.id)::bigint AS job_count,
    COALESCE(SUM(LEAST(
        GREATEST(EXTRACT(EPOCH FROM (job.completed_at - job.started_at)), 0),
        job.timeout_minutes::double precision * 60.0
    )) FILTER (
        WHERE job.started_at IS NOT NULL AND job.completed_at IS NOT NULL
    ), 0)::bigint AS completed_job_seconds
FROM workflow_runs run
LEFT JOIN workflow_jobs job ON job.run_id = run.id
WHERE run.repo_id = $1
  AND run.created_at >= $2
`

type GetActionsUsageSummaryForRepoParams struct {
	RepoID    int64
	CreatedAt pgtype.Timestamptz
}

type GetActionsUsageSummaryForRepoRow struct {
	RunCount            int64
	JobCount            int64
	CompletedJobSeconds int64
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) GetActionsUsageSummaryForRepo(ctx context.Context, db DBTX, arg GetActionsUsageSummaryForRepoParams) (GetActionsUsageSummaryForRepoRow, error) {
	row := db.QueryRow(ctx, getActionsUsageSummaryForRepo, arg.RepoID, arg.CreatedAt)
	var i GetActionsUsageSummaryForRepoRow
	err := row.Scan(&i.RunCount, &i.JobCount, &i.CompletedJobSeconds)
	return i, err
}

const listActionsPerformanceWorkflowsForRepo = `-- name: ListActionsPerformanceWorkflowsForRepo :many
SELECT
    run.workflow_file,
    COALESCE(NULLIF(run.workflow_name, ''), run.workflow_file)::text AS workflow_name,
    COUNT(DISTINCT run.id)::bigint AS run_count,
    COUNT(job.id)::bigint AS job_count,
    COALESCE(AVG(LEAST(
        GREATEST(EXTRACT(EPOCH FROM (job.completed_at - job.started_at)), 0),
        job.timeout_minutes::double precision * 60.0
    )) FILTER (
        WHERE job.started_at IS NOT NULL AND job.completed_at IS NOT NULL
    ), 0)::double precision AS avg_job_seconds,
    COALESCE(AVG(EXTRACT(EPOCH FROM (job.started_at - job.created_at))) FILTER (
        WHERE job.started_at IS NOT NULL AND job.started_at >= job.created_at
    ), 0)::double precision AS avg_queue_seconds,
    COUNT(job.id) FILTER (
        WHERE job.status IN ('completed', 'cancelled', 'skipped')
    )::bigint AS terminal_job_count,
    COUNT(job.id) FILTER (
        WHERE job.status IN ('completed', 'cancelled')
          AND job.conclusion IS NOT NULL
          AND job.conclusion <> 'success'
    )::bigint AS failed_job_count
FROM workflow_runs run
JOIN workflow_jobs job ON job.run_id = run.id
WHERE run.repo_id = $1
  AND run.created_at >= $2
GROUP BY run.workflow_file, COALESCE(NULLIF(run.workflow_name, ''), run.workflow_file)
ORDER BY failed_job_count DESC, avg_job_seconds DESC, run_count DESC, lower(COALESCE(NULLIF(run.workflow_name, ''), run.workflow_file)), run.workflow_file
LIMIT $3
`

type ListActionsPerformanceWorkflowsForRepoParams struct {
	RepoID    int64
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

type ListActionsPerformanceWorkflowsForRepoRow struct {
	WorkflowFile     string
	WorkflowName     string
	RunCount         int64
	JobCount         int64
	AvgJobSeconds    float64
	AvgQueueSeconds  float64
	TerminalJobCount int64
	FailedJobCount   int64
}

func (q *Queries) ListActionsPerformanceWorkflowsForRepo(ctx context.Context, db DBTX, arg ListActionsPerformanceWorkflowsForRepoParams) ([]ListActionsPerformanceWorkflowsForRepoRow, error) {
	rows, err := db.Query(ctx, listActionsPerformanceWorkflowsForRepo, arg.RepoID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActionsPerformanceWorkflowsForRepoRow{}
	for rows.Next() {
		var i ListActionsPerformanceWorkflowsForRepoRow
		if err := rows.Scan(
			&i.WorkflowFile,
			&i.WorkflowName,
			&i.RunCount,
			&i.JobCount,
			&i.AvgJobSeconds,
			&i.AvgQueueSeconds,
			&i.TerminalJobCount,
			&i.FailedJobCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionsUsageWorkflowsForRepo = `-- name: ListActionsUsageWorkflowsForRepo :many
SELECT
    run.workflow_file,
    COALESCE(NULLIF(run.workflow_name, ''), run.workflow_file)::text AS workflow_name,
    COUNT(DISTINCT run.id)::bigint AS run_count,
    COUNT(job.id)::bigint AS job_count,
    COALESCE(SUM(LEAST(
        GREATEST(EXTRACT(EPOCH FROM (job.completed_at - job.started_at)), 0),
        job.timeout_minutes::double precision * 60.0
    )) FILTER (
        WHERE job.started_at IS NOT NULL AND job.completed_at IS NOT NULL
    ), 0)::bigint AS completed_job_seconds
FROM workflow_runs run
LEFT JOIN workflow_jobs job ON job.run_id = run.id
WHERE run.repo_id = $1
  AND run.created_at >= $2
GROUP BY run.workflow_file, COALESCE(NULLIF(run.workflow_name, ''), run.workflow_file)
ORDER BY completed_job_seconds DESC, run_count DESC, lower(COALESCE(NULLIF(run.workflow_name, ''), run.workflow_file)), run.workflow_file
LIMIT $3
`

type ListActionsUsageWorkflowsForRepoParams struct {
	RepoID    int64
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

type ListActionsUsageWorkflowsForRepoRow struct {
	WorkflowFile        string
	WorkflowName        string
	RunCount            int64
	JobCount            int64
	CompletedJobSeconds int64
}

func (q *Queries) ListActionsUsageWorkflowsForRepo(ctx context.Context, db DBTX, arg ListActionsUsageWorkflowsForRepoParams) ([]ListActionsUsageWorkflowsForRepoRow, error) {
	rows, err := db.Query(ctx, listActionsUsageWorkflowsForRepo, arg.RepoID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActionsUsageWorkflowsForRepoRow{}
	for rows.Next() {
		var i ListActionsUsageWorkflowsForRepoRow
		if err := rows.Scan(
			&i.WorkflowFile,
			&i.WorkflowName,
			&i.RunCount,
			&i.JobCount,
			&i.CompletedJobSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
