// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_jobs.sql

package actionsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkflowJobByID = `-- name: GetWorkflowJobByID :one
SELECT id, run_id, job_index, job_key, job_name, runs_on,
       runner_id, needs_jobs, if_expr, timeout_minutes, permissions,
       job_env, status, conclusion, cancel_requested,
       started_at, completed_at, version, created_at, updated_at
FROM workflow_jobs
WHERE id = $1
`

func (q *Queries) GetWorkflowJobByID(ctx context.Context, db DBTX, id int64) (WorkflowJob, error) {
	row := db.QueryRow(ctx, getWorkflowJobByID, id)
	var i WorkflowJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobIndex,
		&i.JobKey,
		&i.JobName,
		&i.RunsOn,
		&i.RunnerID,
		&i.NeedsJobs,
		&i.IfExpr,
		&i.TimeoutMinutes,
		&i.Permissions,
		&i.JobEnv,
		&i.Status,
		&i.Conclusion,
		&i.CancelRequested,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkflowJob = `-- name: InsertWorkflowJob :one

INSERT INTO workflow_jobs (
    run_id, job_index, job_key, job_name,
    runs_on, needs_jobs, if_expr, timeout_minutes,
    permissions, job_env
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, run_id, job_index, job_key, job_name, runs_on,
          runner_id, needs_jobs, if_expr, timeout_minutes, permissions,
          job_env, status, conclusion, cancel_requested,
          started_at, completed_at, version, created_at, updated_at
`

type InsertWorkflowJobParams struct {
	RunID          int64
	JobIndex       int32
	JobKey         string
	JobName        string
	RunsOn         string
	NeedsJobs      []string
	IfExpr         string
	TimeoutMinutes int32
	Permissions    []byte
	JobEnv         []byte
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) InsertWorkflowJob(ctx context.Context, db DBTX, arg InsertWorkflowJobParams) (WorkflowJob, error) {
	row := db.QueryRow(ctx, insertWorkflowJob,
		arg.RunID,
		arg.JobIndex,
		arg.JobKey,
		arg.JobName,
		arg.RunsOn,
		arg.NeedsJobs,
		arg.IfExpr,
		arg.TimeoutMinutes,
		arg.Permissions,
		arg.JobEnv,
	)
	var i WorkflowJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobIndex,
		&i.JobKey,
		&i.JobName,
		&i.RunsOn,
		&i.RunnerID,
		&i.NeedsJobs,
		&i.IfExpr,
		&i.TimeoutMinutes,
		&i.Permissions,
		&i.JobEnv,
		&i.Status,
		&i.Conclusion,
		&i.CancelRequested,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsForRun = `-- name: ListJobsForRun :many
SELECT id, run_id, job_index, job_key, job_name, runs_on, status,
       conclusion, started_at, completed_at, created_at
FROM workflow_jobs
WHERE run_id = $1
ORDER BY job_index ASC
`

type ListJobsForRunRow struct {
	ID          int64
	RunID       int64
	JobIndex    int32
	JobKey      string
	JobName     string
	RunsOn      string
	Status      WorkflowJobStatus
	Conclusion  NullCheckConclusion
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListJobsForRun(ctx context.Context, db DBTX, runID int64) ([]ListJobsForRunRow, error) {
	rows, err := db.Query(ctx, listJobsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsForRunRow{}
	for rows.Next() {
		var i ListJobsForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobIndex,
			&i.JobKey,
			&i.JobName,
			&i.RunsOn,
			&i.Status,
			&i.Conclusion,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
