// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_runs.sql

package actionsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkflowRunByID = `-- name: GetWorkflowRunByID :one
SELECT id, repo_id, run_index, workflow_file, workflow_name,
       head_sha, head_ref, event, event_payload,
       actor_user_id, parent_run_id, concurrency_group,
       status, conclusion, pinned, need_approval, approved_by_user_id,
       started_at, completed_at, version, created_at, updated_at
FROM workflow_runs
WHERE id = $1
`

func (q *Queries) GetWorkflowRunByID(ctx context.Context, db DBTX, id int64) (WorkflowRun, error) {
	row := db.QueryRow(ctx, getWorkflowRunByID, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RunIndex,
		&i.WorkflowFile,
		&i.WorkflowName,
		&i.HeadSha,
		&i.HeadRef,
		&i.Event,
		&i.EventPayload,
		&i.ActorUserID,
		&i.ParentRunID,
		&i.ConcurrencyGroup,
		&i.Status,
		&i.Conclusion,
		&i.Pinned,
		&i.NeedApproval,
		&i.ApprovedByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkflowRun = `-- name: InsertWorkflowRun :one

INSERT INTO workflow_runs (
    repo_id, run_index, workflow_file, workflow_name,
    head_sha, head_ref, event, event_payload,
    actor_user_id, parent_run_id, concurrency_group, need_approval
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, repo_id, run_index, workflow_file, workflow_name,
          head_sha, head_ref, event, event_payload,
          actor_user_id, parent_run_id, concurrency_group,
          status, conclusion, pinned, need_approval, approved_by_user_id,
          started_at, completed_at, version, created_at, updated_at
`

type InsertWorkflowRunParams struct {
	RepoID           int64
	RunIndex         int64
	WorkflowFile     string
	WorkflowName     string
	HeadSha          string
	HeadRef          string
	Event            WorkflowRunEvent
	EventPayload     []byte
	ActorUserID      pgtype.Int8
	ParentRunID      pgtype.Int8
	ConcurrencyGroup string
	NeedApproval     bool
}

// SPDX-License-Identifier: AGPL-3.0-or-later
func (q *Queries) InsertWorkflowRun(ctx context.Context, db DBTX, arg InsertWorkflowRunParams) (WorkflowRun, error) {
	row := db.QueryRow(ctx, insertWorkflowRun,
		arg.RepoID,
		arg.RunIndex,
		arg.WorkflowFile,
		arg.WorkflowName,
		arg.HeadSha,
		arg.HeadRef,
		arg.Event,
		arg.EventPayload,
		arg.ActorUserID,
		arg.ParentRunID,
		arg.ConcurrencyGroup,
		arg.NeedApproval,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RunIndex,
		&i.WorkflowFile,
		&i.WorkflowName,
		&i.HeadSha,
		&i.HeadRef,
		&i.Event,
		&i.EventPayload,
		&i.ActorUserID,
		&i.ParentRunID,
		&i.ConcurrencyGroup,
		&i.Status,
		&i.Conclusion,
		&i.Pinned,
		&i.NeedApproval,
		&i.ApprovedByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowRunsForRepo = `-- name: ListWorkflowRunsForRepo :many
SELECT id, repo_id, run_index, workflow_file, workflow_name,
       head_sha, head_ref, event, status, conclusion,
       actor_user_id, started_at, completed_at, created_at
FROM workflow_runs
WHERE repo_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkflowRunsForRepoParams struct {
	RepoID int64
	Limit  int32
	Offset int32
}

type ListWorkflowRunsForRepoRow struct {
	ID           int64
	RepoID       int64
	RunIndex     int64
	WorkflowFile string
	WorkflowName string
	HeadSha      string
	HeadRef      string
	Event        WorkflowRunEvent
	Status       WorkflowRunStatus
	Conclusion   NullCheckConclusion
	ActorUserID  pgtype.Int8
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListWorkflowRunsForRepo(ctx context.Context, db DBTX, arg ListWorkflowRunsForRepoParams) ([]ListWorkflowRunsForRepoRow, error) {
	rows, err := db.Query(ctx, listWorkflowRunsForRepo, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowRunsForRepoRow{}
	for rows.Next() {
		var i ListWorkflowRunsForRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RunIndex,
			&i.WorkflowFile,
			&i.WorkflowName,
			&i.HeadSha,
			&i.HeadRef,
			&i.Event,
			&i.Status,
			&i.Conclusion,
			&i.ActorUserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRunIndexForRepo = `-- name: NextRunIndexForRepo :one
SELECT COALESCE(MAX(run_index), 0) + 1 AS next_index
FROM workflow_runs
WHERE repo_id = $1
`

// Atomic next-index emitter: take the max + 1 for this repo. Pairs
// with the (repo_id, run_index) UNIQUE so concurrent inserts that
// race here will catch a unique-violation and the caller retries.
func (q *Queries) NextRunIndexForRepo(ctx context.Context, db DBTX, repoID int64) (int32, error) {
	row := db.QueryRow(ctx, nextRunIndexForRepo, repoID)
	var next_index int32
	err := row.Scan(&next_index)
	return next_index, err
}
